### ISSUE TITLE
Document Lock > Multiple users are able to access a document (editView) simultaneously, edit content, and unintentionally overwrite each other's changes.

### ISSUE THREAD

**Issue by Alienpups** [payloadcms/payload#8985] opened 2024-11-01 15:01 UTC
### Describe the Bug

Document lock doesn’t seem to work, whether in the dev or prod environment.  To furhter test this, I created a demo project using pnpm create-payload-app@beta with the Website template selected. Document lock doesn’t work in this setup either.

Additionally, it doesn’t make a difference whether Payload is running locally on a PC or in the cloud on an AWS EC2 instance. The result is the same in both cases. I know that document lock worked in previous versions, but I can’t recall exactly which versions. Is it possible that a bug related to document lock was introduced in recent updates?

### Link to the code that reproduces this issue

Official Payload 3.0 Beta 123 Website Template

### Reproduction Steps

1. Install demo project via pnpm create-payload-app@beta
2. Start via pnpm dev or pnpm build/start
3. Seed database using demo seeds.
4. Create second user.
5. Go to pages collection, open home or contact site in editview and leave it open
6. Use another browser (private tab) and login with second user.
7. Go to pages collection (listview).

Second user should now see a lock icon including lock functionality when clicking the locked document but all of this isn't there/available.

### Which area(s) are affected? (Select all that apply)

area: docs

### Environment Info

PS D:\test\123\lock-test> pnpm payload info

> lock-test@1.0.0 payload D:\test\123\lock-test
> cross-env NODE_OPTIONS=--no-deprecation payload "info"

Binaries:
  Node: 20.11.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  payload: 3.0.0-beta.123
  next: 15.0.0
  @payloadcms/db-mongodb: 3.0.0-beta.123
  @payloadcms/email-nodemailer: 3.0.0-beta.123
  @payloadcms/graphql: 3.0.0-beta.123
  @payloadcms/live-preview: 3.0.0-beta.123
  @payloadcms/live-preview-react: 3.0.0-beta.123
  @payloadcms/next/utilities: 3.0.0-beta.123
  @payloadcms/payload-cloud: 3.0.0-beta.123
  @payloadcms/plugin-form-builder: 3.0.0-beta.123
  @payloadcms/plugin-nested-docs: 3.0.0-beta.123
  @payloadcms/plugin-redirects: 3.0.0-beta.123
  @payloadcms/plugin-search: 3.0.0-beta.123
  @payloadcms/plugin-seo: 3.0.0-beta.123
  @payloadcms/richtext-lexical: 3.0.0-beta.123
  @payloadcms/translations: 3.0.0-beta.123
  @payloadcms/ui/shared: 3.0.0-beta.123
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32550
  Available CPU cores: 20

PS D:\test\123\lock-test>

**Comment by Alienpups** [comment] 2024-11-03 14:11
I have now conducted additional tests, working my way down from version 123 to version 117. In **none** of these versions does Document Lock function consistently. In version 118, there was a brief moment when Document Lock was displayed correctly and worked as expected. However, this only occurred during a single "run-through."

**Run-through:** User 1 opens one of the pages or posts in the Pages/Posts collection and remains in the document (edit view). Then, User 2 logs in and goes to Pages, where the lock icon and subsequent modal overlay with options are correctly displayed for the locked document in ListView. When User 1 leaves EditView, the lock disappears for User 2.

This is as expected.

**Now the issue/anomaly:** When User 2 then enters the same document or any other document, nothing happens regarding locking. No lock icon or other indicators appear for User 1.

**The main problem is that Document Lock does not function consistently.**
In most cases, it does **not** work and does **not** appear anywhere.
In very rare, so far unreproducible cases, Document Lock works and is displayed correctly.

**Comment by PatrikKozak** [comment] 2024-11-03 14:19
Hey @Alienpups - so the way we initiate a lock on a document is not when a user enters a document but instead starts editing a document. Simply viewing a document will not lock it.

As User 1, if you enter a document and then edit one of the fields within it (without saving just yet), and now go and check the status of the document as user 2 - it should be locked.

I just tested this on my end and it's working as expected.


Are you saying this isn't the case still?

**Comment by Alienpups** [comment] 2024-11-03 15:14
Hey @PatrikKozak - i just tested it and you are correct. I simply misunderstood the way document lock works and misused it. I can confirm that it works as you described and without any errors. However, I do have a question about it.

How does Document Lock behave if, for example, no versions are used in the collection, but instead only the standard save logic without versions? Could you walk me through this case as well?

Because if no versions are used and therefore not present, how does Payload know when a document should be locked and when it shouldn’t? You probably get where i'm heading to...

**Comment by Alienpups** [comment] 2024-11-03 15:21
Additionally, I noticed that the ListView only updates when the page is refreshed.

This means that, for example, if User 1 enters a document (edit view) and User 2 already had the collection (ListView) open before User 1 entered the document, no lock is shown for User 2 on the document just opened by User 1.

Could it be that the states for users who already had the same collection (ListView) open in parallel are not being updated correctly?

**Comment by Alienpups** [comment] 2024-11-03 16:29
I believe that a document only being locked when a user makes a change is not very robust and can lead to conflicts.

What happens if User 1 opens a document but doesn’t make any changes and just keeps the tab open, while User 2 opens the same document and starts editing fields? User 1 isn’t aware of this and thinks they’re the only user in this document, so they also start editing it.
Result is two user are editing the same document simultaneously and overwrite each other’s changes when they save? Or what happens in this case?

Wouldn't it make more sense to modify Document Lock so that a document is locked as soon as a user enters it without the need to have edited something?
Other users could still open the document in a read-only view via the modal, but this would ensure that users don’t unintentionally overwrite each other’s content.

**Comment by PatrikKozak** [comment] 2024-11-04 03:06
@Alienpups You are correct that currently User 2 would not see the lock icon until a refresh - this is by design at the moment. Here is how it works: 

On initial load of the list view, a request is made to `form-state` which contains the data of whether or not documents are locked. hence the reason you only see the updated lock status on a refresh because a new request is made to `form-state`. We are currently exploring ways to implement continues real-time updates for this but at the moment, this is by design. 

> What happens if User 1 opens a document but doesn’t make any changes and just keeps the tab open, while User 2 opens the same document and starts editing fields? User 1 isn’t aware of this and thinks they’re the only user in this document, so they also start editing it.
Result is two user are editing the same document simultaneously and overwrite each other’s changes when they save? Or what happens in this case?

We handle the above scenario so there wouldn't be conflicts and here is how:

If User 1 and User 2 are both viewing a document at the same time but neither have edited yet, the document isn't locked yet. 

Once User 2 begins editing, the document becomes locked by User 2. At this point, if User 1 tries to edit a field, they’ll see a modal pop up letting them know the document is locked and giving options to either go back to the dashboard or view it in read-only mode.

The lock only activates when a user makes an actual edit, not when they just open the document. This way, multiple users can view the document simultaneously without being restricted. The moment someone starts editing, though, anyone else trying to edit will be notified.

When a user saves or leaves the document, the lock is removed, so it’s freed up again for others to edit.

We have documentation on this [here](https://payloadcms.com/docs/beta/admin/locked-documents), if you'd like to know more about it. 

I could probably add some additional information / explanations in the documentation for clarity - I will look into this tomorrow.

I’ve done some additional testing, and everything seems to be working as expected, so I’ll go ahead and close this issue for now. If you notice any issues that don’t match the behavior outlined above, just let me know here, and I’ll be happy to re-open and take a closer look.

**Closed by PatrikKozak** 2024-11-04 03:06 UTC
Labels: v3, invalid-reproduction
