### ISSUE TITLE
Lexical toolbar z-index problem

### ISSUE THREAD

**Issue by stuckinsnow** [payloadcms/payload#8805] opened 2024-10-21 11:37 UTC
### Describe the Bug

When a select field is above the lexical editor, the lexical editor is partially hidden. This is true for 116.

### Link to the code that reproduces this issue

No

### Reproduction Steps

Create a select field with at least two options to pick from, above the lexical editor, and try to select one of those options.

### Which area(s) are affected? (Select all that apply)

Not sure

### Environment Info

116

**Comment by akhrarovsaid** [comment] 2024-10-21 13:23
Hey @stuckinsnow,

I believe this is a duplicate of #8728 which has [a PR up by Ritsu](https://github.com/payloadcms/payload/pull/8735).

**Closed** 2024-10-21 21:26 UTC
Labels: status: needs-triage, v3
