### ISSUE TITLE
plugin-cloud-storage: S3 adapter not working with create-payload-app template

### ISSUE THREAD

**Issue by vsylvestre** [payloadcms/payload#4851] opened 2024-01-11 02:35 UTC
I'm having the exact same problem as https://github.com/payloadcms/plugin-cloud-storage/issues/38.

I used `create-payload-app` to scaffold the blank TypeScript Payload template. Immediately after, I tried integrating the S3 adapter, and I have the following error:

```
Module not found: Error: Can't resolve 'fs'
```

However, doing _everything_ the same as described in the comments of this issue to solve the problem, it still doesn't work. I'm wondering if this is something to do with the newer versions of the packages? Or did I miss something in my config?

For `payload.config.ts`, I have:

```js
const adapter = s3Adapter({
  config: {
    credentials: {
      accessKeyId: process.env.S3_ACCESS_KEY_ID,
      secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
    },
    region: process.env.S3_REGION
  },
  bucket: process.env.S3_BUCKET,
})

export default buildConfig({
  admin: {
    user: Users.slug,
    bundler: webpackBundler(),
  },
  editor: slateEditor({}),
  collections: [Users, Projects, Media],
  typescript: {
    outputFile: path.resolve(__dirname, 'payload-types.ts'),
  },
  graphQL: {
    schemaOutputFile: path.resolve(__dirname, 'generated-schema.graphql'),
  },
  plugins: [
    payloadCloud(),
    cloudStorage({
      collections: {
        media: {
          adapter
        },
      },
    })
  ],
  db: mongooseAdapter({
    url: process.env.DATABASE_URI,
  }),
})
```

The Media collection, I copied from another repo and didn't change anything:

```js
import { CollectionConfig } from 'payload/types';

export const Media: CollectionConfig = {
  slug: 'media',
  upload: {
    staticURL: '/media',
    staticDir: 'media',
    imageSizes: [
      {
        name: 'thumbnail',
        width: 400,
        height: 300,
        position: 'centre',
      },
      {
        name: 'card',
        width: 768,
        height: 1024,
        position: 'centre',
      },
      {
        name: 'tablet',
        width: 1024,
        // By specifying `undefined` or leaving a height undefined,
        // the image will be sized to a certain width,
        // but it will retain its original aspect ratio
        // and calculate a height automatically.
        height: undefined,
        position: 'centre',
      },
    ],
    adminThumbnail: 'thumbnail',
    mimeTypes: ['image/*'],
  },
  fields: [
    {
      name: 'alt',
      type: 'text',
    },
  ],
};
```

Am I missing something?

Thank you!

**Comment by denolfe** [comment] 2024-04-02 14:45
Dupe of #4215

**Closed by denolfe** 2024-04-02 14:45 UTC
Labels: plugin: cloud-storage
