### ISSUE TITLE
Content added in-place in relation field does not respect current locale

### ISSUE THREAD

**Issue by genox** [payloadcms/payload#7125] opened 2024-07-12 07:04 UTC
### Link to reproduction

https://github.com/netzwerk-schweizer-paerke/ims-tool

### Payload Version

beta.60

### Node Version

latest

### Next.js Version

recommended

### Describe the Bug

Content can be added in-place, e.g. in a modal, in a relation field.

In a scenario where there are multiple languages available (content locales), and one is not using the default locale, content that is added via modal is added in the default locale but - not sure how to verify this, this is just a hunch - it seems like the form tries to get the correct locale after save because it displays an empty form after saving.

### Reproduction Steps

- Launch the linked payload app
- Switch Locale in upper right to German/Deutsch
- Add an "Activity"
- Add a "Flow" and a "Task List" in-place via modal
- Go to the document list view and notice the empty name

### Adapters and Plugins

postgres

**Comment by paulpopus** [comment] 2024-07-23 19:21
@genox so I pulled down your repo as is and I went through the outlined steps and the result I got was that while staying in the german locale, my content was displaying as german

Then I switch back to english and they show up as having an empty name which is entirely expected since I didn't add data for english and only for german.

Are you seeing something different? could you give this another test on a newer beta version as well please?

Also I noticed the `@hapi/hoek` package is missing from your package.json, I'd make sure that you clear your node_modules and install again just in case you've got some older version of payload cached

**Comment by paulpopus** [comment] 2024-07-25 16:23
Closing this for now but will gladly re-open if there's a reproduction for it!

**Closed by paulpopus** 2024-07-25 16:23 UTC
Labels: status: needs-repro, v3
