### ISSUE TITLE
Payload not building in monorepo

### ISSUE THREAD

**Issue by vsylvestre** [payloadcms/payload#4798] opened 2024-01-12 23:02 UTC
### Describe the Bug

I tried integrating Payload CMS in a monorepo setup using Yarn Workspaces, and it doesn't work.

### To Reproduce

Here are the minimal steps to reproduce:

1. Create a yarn repository with basic `package.json`.
2. Set up a dummy package as a workspace.
3. Run `npx create-payload-app@latest` within the monorepo to generate a new workspace from it.
4. Run `yarn` from the root of the monorepo to make sure dependencies are re-distributed.
5. Run `build` within the Payload workspace. It fails with the following error:

```
await _.default.config.admin.bundler.build(config);
                           ^
TypeError: Cannot read properties of undefined (reading 'admin')
    at build (/***/node_modules/payload/dist/bin/build.js:21:28)
```

Of course, it seems that the issue arises from step 4, the redistribution of packages between the root `node_modules` and the workspace's `node_modules`. However, interestingly, if I add _all_ packages into the `nohoist` option of Yarn Workspaces, it still doesn't work.

Any ideas?

Thank you!

### Payload Version

2.8.1

### Adapters and Plugins

bundler-webpack, db-mongodb, plugin-cloud, richtext-slate

**Comment by MarkKropf** [comment] 2024-01-13 17:26
@vsylvestre interesting, I had the exact same build bug and this [commit](https://github.com/payloadcms/payload/commit/775502b1616c1bd35a3044438e253a0e84219f99) that landed in 2.8.1 fixed it for me.

**Comment by ssyberg** [comment] 2024-01-16 17:00
I'm experiencing this in `2.8.0`, there's not a nightly/canary for `2.8.1` right?

**Comment by jamesvclements** [comment] 2024-01-16 18:59
@ssyberg bumping back down to `2.7.0` for now fixed this for me

**Comment by ssyberg** [comment] 2024-01-16 19:30
Same!

**Comment by faizur11786** [comment] 2024-01-24 14:11
I encountered a similar problem, downgrading the version works for me.

**Comment by tomsvogel** [comment] 2024-03-10 08:19
Hey, I had the same issue in a turborepo setup, using now the newest versions works for me. IMPORTANT was to delete also the .turbo folders.

Versions:
```
    "@payloadcms/bundler-webpack": "1.0.6",
    "@payloadcms/db-mongodb": "1.4.3",
    "@payloadcms/plugin-cloud-storage": "1.1.2",
    "@payloadcms/richtext-slate": "1.4.0",
     "payload": "2.11.2",
```

**Comment by tomsvogel** [comment] 2024-03-28 11:07
Finally we found the issue, we have created collection filters and stored them in the collection directory. Moving them out and everything builds as expected...

**Comment by denolfe** [comment] 2024-04-02 18:17
@tomsvogel Glad you found a solution.

Could you share some additional detail on why you think this may have solved your issue?

**Comment by tomsvogel** [comment] 2024-04-02 22:41
i have no clue, why the development server started with some non-collection files in the collection folder 🤷

**Comment by denolfe** [comment] 2024-04-04 20:41
I'd like to try and recreate this if it's still an issue.

@ssyberg @jamesvclements Are either of you able to provide more info about your monorepo setup and/or a recreation of the issue?

**Comment by tomsvogel** [comment] 2024-04-05 04:16
it is a turborepo (latest) with yarn
payload and remix.run


we had this in the collection folder

Base component
```
import {usePreferences} from 'payload/components/preferences';
import type {FC} from 'react';
import React, {useEffect, useState} from 'react';
import './index.scss';

const CollectionFilters: FC<{
  preferenceKey: string;
  links: {lable: string; url: string}[];
}> = ({preferenceKey, links}) => {
  const {getPreference, setPreference} = usePreferences();
  const [pathname, setPathname] = useState<string>();
  const [query, setQuery] = useState<string>();
  useEffect(() => {
    setPathname(window.location.pathname);
    setQuery(window.location.search);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [window.location.pathname, window.location.search]);
  useEffect(() => {
    const asyncGetPreference = async () => {
      const lastFilterFromPreferences = await getPreference(preferenceKey);
      if (
        pathname &&
        (query === '' || query.match(/\?limit=\d+$/)) &&
        lastFilterFromPreferences
      ) {
        window.open(lastFilterFromPreferences, '_self');
      }
    };

    asyncGetPreference();
  }, [getPreference, pathname, preferenceKey, query]);
  useEffect(() => {
    if (pathname && query && !query.match(/\?limit=\d+$/)) {
      setPreference(preferenceKey, '' + pathname + query);
    }
  }, [pathname, preferenceKey, query, setPreference]);

  return (
    <div className='filter-buttons'>
      <div className='list'>
        {links.map(link => (
          <a
            key={link.url}
            href={link.url}
            className='btn btn--style-primary btn--icon-style-without-border btn--size-medium btn--icon-position-right'
            onClick={() => setPreference(preferenceKey, link.url)}>
            {link.lable}
          </a>
        ))}
      </div>
    </div>
  );
};

export default CollectionFilters;
```

Filter example

```
import type {FC} from 'react';
import CollectionFilters from './CollectionFilters';

const ProfilesFilters: FC = () =>
  CollectionFilters({
    preferenceKey: 'lastProfilesFilter',
    links: [
      {
        lable: 'Jahr: 2023',
        url: '/admin/collections/profiles?limit=100&page=1&where%5Bor%5D%5B0%5D%5Band%5D%5B0%5D%5Byear%5D%5Bequals%5D=2023',
      }
    ],
  });

export default ProfilesFilters;
```

**Comment by denolfe** [comment] 2024-04-17 02:28
@tomsvogel If you can provide a minimal reproduction in a repository, this would help a lot.

**Comment by denolfe** [comment] 2024-04-29 14:05
Can reopen if more info provided.

**Closed by denolfe** 2024-04-29 14:05 UTC
Labels: [possible-bug], [cant-reproduce]
