### ISSUE TITLE
Payload lexical link issue: Maximum update depth exceeded

### ISSUE THREAD

**Issue by vibhor-web-headout** [payloadcms/payload#3930] opened 2023-10-30 14:23 UTC
### Describe the Bug

Version:
```
"payload": "^2.0.13",
"@payloadcms/richtext-lexical": "^0.1.15",
```

Default flow of selecting a text and clicking on the "link" option causes the browser to freeze.
It displays the following error message, infinitely.

```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
```

Seems to be triggering via this `useEffect`: https://github.com/payloadcms/payload/blob/31857715515f2d33c000d5504c88ea4b106ee4fe/packages/richtext-lexical/src/field/features/Link/plugins/floatingLinkEditor/LinkEditor/index.tsx#L276

### To Reproduce

1. Install and set payload and payload lexical to the mentioned version
2. Write a text and select it to display the bar containing the link option
3. Click on the link option

### Payload Version

2.0.13

### Adapters and Plugins

@payloadcms/richtext-lexical: ^0.1.15

**Comment by AlessioGr** [comment] 2023-11-04 13:56
Hey, I'm not able to reproduce this issue. Can you link me to a repository which reproduces this?

**Comment by HarleySalas** [comment] 2023-11-08 10:22
It's quite weird to me as well... My Lexical + LinkFeature was working fine as well. Suddenly, it just started crashing the browser tab the second I interact with the link component. I've got the same error message, `Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.`

I **know** it was working in 2.0.14, so I downgraded as well, but that didn't fix it either. I can't be sure *exactly* what causes the issue. I don't believe it's simply the version, there has to be some other factor that is causing it. I even removed all other Lexical features and isolated it to the default LinkFeature, with no modifications. The issue persists.

`"@payloadcms/richtext-lexical": "^0.1.16",`
`"payload": "^2.0.15"`

**Comment by HarleySalas** [comment] 2023-11-08 11:49
> Hey, I'm not able to reproduce this issue. Can you link me to a repository which reproduces this?

I was not able to reproduce on a blank template for you. So, I apologize, it's not a very clean repo, though it is based off of the `website` template.

Under the "Company Information" global is probably the easiest place to try editing some richText. Just add a link element there and it *should* just crash.

To run it;
`docker-compose -f docker-compose.development.yml up`
`yarn dev`

**Comment by AlessioGr** [comment] 2023-11-14 09:09
No update yet! There were a few other issues I'm gonna look at first before moving on to this one

**Comment by AlessioGr** [comment] 2023-11-14 15:41
@vibhor-web-headout @HarleySalas 

I've just investigated this and found out this is an issue with your project, rather than with payload / the lexical plugin, so I'll close this issue.

Here, the problem is the following package you've installed:

`"react-i18next": "^13.3.1"`

This causes your project to use a DIFFERENT react version than what payload uses. These react packages version conflicts very often cause issues like these. In this case, removing this dependency fixes it.

This issue could also happen if you have other conflicting react packages (not just react-i18next).

Apart from removing the conflicting package, another thing you can do is alias the package in the webpack config, so that both payload & your project use the same version of that package

**Closed by AlessioGr** 2023-11-14 15:41 UTC
Labels: reproduced, plugin: richtext-lexical

**Comment by dkelsen** [comment] 2024-05-08 15:49
I ran into a similar issue with the Slate editor. Whenever I tried to insert a link, the browser would freeze. There were no logs that showed an error. Turned out that the dependencies `react-i18next` and `i18next` from `@payloadcms/richtext-slate` were conflicting with the versions installed in the monorepo the CMS is located in. Downgrading the dependencies to the specific versions solved the issue.
