### ISSUE TITLE
Memory leaks that occurs on hot-reloads

### ISSUE THREAD

**Issue by rafalnawojczyk** [payloadcms/payload#3892] opened 2023-10-27 06:57 UTC
### Describe the Bug

When working on a development in Next.js + PayloadCMS, after some hot-reloads I'm getting error about exceeding maximum allocated memory for Heap. It is currently set to 4GB. When monitoring a process using HTOP - you can clearly see that RAM usage is increasing until it crashes.

This bug started affecting my workflow right after upgrading PayloadCMS to the latest version(from 1.14 to 2.0)

### To Reproduce

Simply start the development server and make some changes in code and/or create a page in PayloadCMS and keep editing/saving this page.

### Payload Version

2.0.12

### Adapters and Plugins

bundler-webpack, db-mongodb, s3Adapter, cloudstorage, seo, redirects,

**Comment by JarrodMFlesch** [comment] 2023-11-21 21:47
@rafalnawojczyk I am unable to reproduce. If you are able to share a reproducible repo I will gladly check it out. For now I am going to close this issue. Please let me know if you can provide a reproduction though!

**Closed by JarrodMFlesch** 2023-11-21 21:47 UTC
Labels: possible-bug, cant-reproduce
