### ISSUE TITLE
Access with query throw 500 error instead of 403

### ISSUE THREAD

**Issue by mrTresmo** [payloadcms/payload#2387] opened 2023-03-23 13:05 UTC
### Link to reproduction

https://github.com/mrTresmo/payload.git

### To Reproduce

1. Create a user collection with access query to only allow updating the requesting user. 
`access: {
    update: ({ req }) => {
      return {
        id: {
          equals: req.user.id,
        },
      };
    },
  }`
3. create two users
4. User1 change property in user2
5. The request throw 500

### Describe the Bug

Updating a user who should not have access based on a permissions query results in a 500 error. Expected would be a 403 error.

The test case is implemented in https://github.com/mrTresmo/payload.git 

Run: `yarn dev:generate-types _community`

### Payload Version

1.6.23

**Comment by jmikrut** [comment] 2023-03-23 13:31
Hey @mrTresmo — this is probably just because you are accessing `req.user.id` in cases where `req.user` may not be present. And that would be a 500 caused by the logic in your access control handler. Payload does indeed return 403s if you are not able to access what you're asking for.

Give that a shot! I will close this though as I don't believe it's related to Payload core.

Keep me posted!

**Closed by jmikrut** 2023-03-23 13:31 UTC
Labels: possible-bug

**Comment by mrTresmo** [comment] 2023-03-24 08:29
@jmikrut the issue can be fixed in `src/versions/getLatestCollectionVersion.ts`:
doc can possibly be null. This causes doc._id to throw the error.

```
...

  const doc = await Model.findOne(query, {}, { lean });

  if (!latestVersion || (docHasTimestamps(doc) && latestVersion.updatedAt < doc.updatedAt)) {
    // doc can be possible null. So doc._id throw the error
    if (doc?._id) {
      doc.id = doc._id;
    }
    return doc;
  }

  return {
    ...latestVersion.version,
    id,
    updatedAt: latestVersion.updatedAt,
    createdAt: latestVersion.createdAt,
  };
};
```
