### ISSUE TITLE
Attempted illegal state transition (Nested-Docs + MongoDB Atlas)

### ISSUE THREAD

**Issue by davelsan** [payloadcms/payload#4072] opened 2023-11-09 12:30 UTC
### Link to reproduction

https://github.com/davelsan/payload-issues/tree/main/repros/nested-docs-transaction-error

### Describe the Bug

**I was only able to reproduce this problem when using MongoDB Atlas. I cannot reproduce in my local development environment (Community Edition)**

This bug affects the `@payloadcms/plugin-nested-docs` plugin.

When editing a parent relationship (either add or remove), and after the operation was successful, when I navigate to a collection list sometimes I get this MongoDB runtime error.

```
<path/to/project>/node_modules/mongodb/src/transactions.ts:168
throw new MongoRuntimeError(
^
MongoRuntimeError: Attempted illegal state transition from [TRANSACTION_COMMITTED] to [TRANSACTION_ABORTED]
at Transaction.transition (<path/to/project>/node_modules/mongodb/src/transactions.ts:168:11)
at commandHandler (<path/to/project>/node_modules/mongodb/src/sessions.ts:740:27)
at <path/to/project>/node_modules/mongodb/src/sessions.ts:810:7
at <path/to/project>/node_modules/mongodb/src/utils.ts:462:14
at processTicksAndRejections (node:internal/process/task_queues:95:5)
``` 

It does not always happen, sometimes I have to edit the parent a couple of times before the error is thrown. It also does not matter what collection I navigate to afterwards, but it **only happens in collection views**. That is, if I navigate to the admin home page, no errors until I try requesting a collection list.

For some reason I cannot reproduce this issue using a local database, only the Atlas instance. Both my local and cloud instances have the same collections setup, hooks, etc. There are some data differences, but that's it. In the repro I have a simplified setup with only the nested collection. I still need to test this simplified setup in Atlas.

Any idea what could be happening here?

### To Reproduce

Follow the instruction on the repro.
1. Install dependencies.
2. Create parent and child documents.
3. Navigate to any collection view to get the list of documents.
4. Stuck in loading skeleton?
  [YES] Check console errors.
  [NO] Edit the child location by adding or removing the parent until navigating to the collection view crashes.

### Payload Version

2.1.0

### Adapters and Plugins

"@azure/storage-blob": "^12.16.0", "@payloadcms/bundler-webpack": "1.0.5",     "@payloadcms/db-mongodb": "1.0.7",     "@payloadcms/plugin-cloud": "2.2.6",     "@payloadcms/plugin-cloud-storage": "1.1.1",     "@payloadcms/plugin-form-builder": "^1.0.15",     "@payloadcms/plugin-nested-docs": "^1.0.8",     "@payloadcms/richtext-lexical": "0.1.16", "payload-plugin-resolve-alias": "^0.1.0"

**Comment by davelsan** [comment] 2023-11-09 12:58
I noticed this code in `plugin-nested-docs/src/index.ts`

```ts
beforeChange: [
  async ({ req, data, originalDoc }) =>
    populateBreadcrumbs(req, pluginConfig, collection, data, originalDoc),
    ...(collection?.hooks?.beforeChange || []),
],
```

Judging by the docs and what the other hooks in the plugin, would it be appropriate to `await` the `populateBreadcrumbs` function?

**Comment by matteo-naif** [comment] 2023-11-14 13:13
I have the same problem, any updates?

**Comment by georgeharito** [comment] 2023-11-14 22:46
Same problem here too, however for me it occurs whenever I save any collections that use the nested-docs plugin, and not just when I go to view the list of records in a nested-docs-enabled collection.

**Comment by Rohan-keyideas** [comment] 2023-11-17 05:00
Same problem with me any update?

**Comment by hassanthegooner** [comment] 2023-11-18 20:39
Getting the same issue using a MongoDb Atlas

**Comment by jon8800** [comment] 2023-11-19 10:25
Same issue here. This is related: #4077. @DanRibbens looks like it wasn't resolved with the recent update.

**Comment by DanRibbens** [comment] 2023-11-20 18:50
I tried very hard to reproduce this issue. Since I cannot I am going to commit the suggested fix from @davelsan 
 https://github.com/payloadcms/payload/issues/4072#issuecomment-1803783139. It probably should be awaiting that anyways.

Another thing I considered is that the connection options being used in your mongodb connection string might have something to do with the variance in results. I haven't confirmed this, but I will share it anyways in case somebody else has experienced this or wants to try. I used a combination of `retryWrites=true` and `w=majority` when testing, perhaps there are other settings that are the cause.

**Closed** 2023-11-20 21:32 UTC
Labels: possible-bug, cant-reproduce, plugin: nested-docs, db-mongodb

**Comment by bsides** [comment] 2023-12-06 19:15
Hi guys, I'm getting the same error with payload-demo. I didn't do anything, just ran the project, after a while, it threw this message. Now every time I try to run the app via `pnpm dev` I get the same message. I'm using a new mongodb atlas and fresh install. My connection string is the one given by mongodb atlas, which is something like this: `mongodb+srv://MY_USERNAME:MY_PASSWORD@cluster-CLUSTER_NAME.SOME_STRING.mongodb.net/`

<img width="1198" alt="image" src="https://github.com/payloadcms/payload/assets/87631/ac5c048e-7086-426c-98c9-4e025624c680">
