### ISSUE TITLE
Publish Button Visibility and Permissions Issue

### ISSUE THREAD

**Issue by Bobeta** [payloadcms/payload#6580] opened 2024-05-30 21:01 UTC
### Payload Version

beta v37

### Node Version

21

### Next.js Version

15

### Describe the Bug

I've been experimenting with the solution from the Payload CMS discussion[ [#1009](](url)https://github.com/payloadcms/payload/discussions/1009) in v3. 

The goal is to have permissions that restrict publish access in create/update operations for a collection. The suggested solution initially hides the publish button, allowing only draft saving. However, there are two issues observed:

After saving a draft, the publish button reappears. Clicking on it results in an error.
Despite the absence of publish permissions, users can still publish documents from the list view.

Expected Behavior:
- The publish button should remain hidden for users without publish permissions after saving a draft.
- Users without publish permissions should not be able to publish documents from the list view.

Actual Behavior:
- The publish button reappears after saving a draft and results in an error when clicked.
- Users without publish permissions can publish documents from the list view.

### Reproduction Steps

- Implement access control for create/update operations in a collection to check if _status is 'published' and restrict publish permissions accordingly.
- Save a draft of a document.
- Observe that the publish button reappears.
- Attempt to click the publish button and note the error.
- Navigate to the collection list view and observe that publishing the document is possible without having publish permissions.

**Comment by JarrodMFlesch** [comment] 2024-06-12 13:28
@Bobeta can you give an example of your update/create access functions so I can recreate?

**Comment by JarrodMFlesch** [comment] 2024-07-08 20:36
Closing as I could not reproduce. We can reopen this if a reproduction is provided!

**Closed by JarrodMFlesch** 2024-07-08 20:36 UTC
Labels: status: needs-repro, v3

**Comment by henrik-d** [comment] 2024-08-15 15:23
@JarrodMFlesch I think, I can reproduce the issue in v3 and the issue should be reopened.

This is my access function
```
export const cannotPublish: Access = ({ req, data }) => {
  if (!req.user) {
    return false;
  }

  if (data?._status === "published") {
    return false;
  }

  return true;
};
```

This is the collection's access config:
```
access: {
    read: () => true,
    create: () => true,
    update: cannotPublish,
    delete: () => false,
}
```

**Observation**
1. On load => "Publish changes" is hidden, "Save Draft" is disabled
2. When editing a field => "Publish changes" is hidden, "Save Draft" is enabled
3. After "Save Draft" => "Publish changes" appears ⚠️
4. When clicking "Publish changes" => "You are not allowed to perform this action."
