### ISSUE TITLE
Relationship not showing title when using groups

### ISSUE THREAD

**Issue by ChrisGV04** [payloadcms/payload#2333] opened 2023-03-17 04:32 UTC
# Bug Report

If you create a collection and set the `admin.useAsTitle` to a nested field inside of a group, whenever you try to use a relationship field on another collection, the drop-down selector shows "No title", but the actual collection does render it correctly.

Here's my example:

```ts
// collections/Testimonials.ts

const Testimonials: CollectionConfig = {
  slug: 'testimonials',
  admin: {
    useAsTitle: 'author.name',
  },
  fields: [
    // ...
    {
      name: 'author',
      type: 'group',
      fields: [
        {
          name: 'name',  // stored as `author.name`
          type: 'text',
          required: true,
        },
        // ...
      ],
    },
  ],
};

// globals/Homepage.ts

export const HomePage: GlobalConfig = {
  slug: 'homepage',
  fields: [
    {
      name: 'testimonials',
      type: 'array',
      required: true,
      fields: [
        {
          name: 'comment',
          type: 'relationship',
          required: true,
          relationTo: Testimonials.slug,
          label: { en: 'Comment', es: 'Comentario' },
        },
        {
          name: 'featured',
          type: 'checkbox',
          required: true,
          label: { en: 'Is featured?', es: '¿Es destacado?' },
        },
      ],
    },
  ],
};

```

<img width="762" alt="payload-no-title-relationship" src="https://user-images.githubusercontent.com/47041342/225813096-11a37c4e-e50c-4c20-9c41-84da3bf80a48.png">

## Other Details

Payload @ 1.6.22

**Comment by jacobsfletch** [comment] 2023-03-19 14:20
Duplicate of https://github.com/payloadcms/payload/issues/2205

**Closed** 2023-03-21 02:21 UTC
Labels: possible-bug
