### ISSUE TITLE
Stripe Webhook Error

### ISSUE THREAD

**Issue by mikecebul** [payloadcms/payload#9314] opened 2024-11-18 22:15 UTC
### Describe the Bug

The Stripe Webhooks quit working in my application. My build error is
```bash
src/app/api/webhooks/stripe/route.ts
Type error: File '/home/mike/Code/cvx-junior-golf/src/app/api/webhooks/stripe/route.ts' is not a module.
```

### Link to the code that reproduces this issue

N/A

### Reproduction Steps

- Add the Stripe plugin in the config
```javascript
stripePlugin({
      isTestKey: process.env.STRIPE_SECRET_KEY?.includes('sk_test'),
      stripeSecretKey: process.env.STRIPE_SECRET_KEY || '',
      stripeWebhooksEndpointSecret: process.env.STRIPE_WEBHOOKS_ENDPOINT_SECRET,
      webhooks: {
        'checkout.session.completed': checkoutSessionCompleted,
      },
      logs: true,
    }),
```
This is my webhook
```javascript
import type { StripeWebhookHandler } from '@payloadcms/plugin-stripe/types'
import type Stripe from 'stripe'

export const checkoutSessionCompleted: StripeWebhookHandler<{
  data: {
    object: Stripe.Checkout.Session
  }
}> = async ({ event, payload }) => {
  console.log('checkoutSessionCompleted handler called')

  const { id: sessionId, metadata, amount_total } = event.data.object
  const submissionId = metadata?.submissionId

  if (!submissionId) {
    payload.logger.error('No submissionId found in checkout session metadata')
    return
  }
  try {
    await payload.update({
      collection: 'form-submissions',
      id: submissionId,
      overrideAccess: true,
      data: {
        paymentStatus: 'paid',
        amount: amount_total ? `$${(amount_total / 100).toFixed(2)}` : '$0.00',
      },
    })

    payload.logger.info(
      `Successfully updated form submission ${submissionId} for checkout session ${sessionId}`,
    )
  } catch (error) {
    payload.logger.error(`Error updating form submission: ${error}`)
  }
}
```
- Add the env vars
- Test  the webhook

### Which area(s) are affected? (Select all that apply)

plugin: stripe

### Environment Info

```text
Binaries:
  Node: 20.14.0
  npm: 10.7.0
  Yarn: 1.22.22
  pnpm: 9.7.0
Relevant Packages:
  payload: 3.0.0-beta.134
  next: 15.0.0
  @payloadcms/db-mongodb: 3.0.0-beta.134
  @payloadcms/email-resend: 3.0.0-beta.134
  @payloadcms/graphql: 3.0.0-beta.134
  @payloadcms/live-preview: 3.0.0-beta.134
  @payloadcms/live-preview-react: 3.0.0-beta.134
  @payloadcms/next/utilities: 3.0.0-beta.134
  @payloadcms/plugin-cloud-storage: 3.0.0-beta.134
  @payloadcms/plugin-form-builder: 3.0.0-beta.134
  @payloadcms/plugin-redirects: 3.0.0-beta.134
  @payloadcms/plugin-seo: 3.0.0-beta.134
  @payloadcms/plugin-stripe: 3.0.0-beta.134
  @payloadcms/richtext-lexical: 3.0.0-beta.134
  @payloadcms/storage-s3: 3.0.0-beta.134
  @payloadcms/translations: 3.0.0-beta.134
  @payloadcms/ui/shared: 3.0.0-beta.134
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Tue Nov 5 00:21:55 UTC 2024
  Available memory (MB): 15847
  Available CPU cores: 16
```

**Comment by jacobsfletch** [comment] 2024-11-19 18:26
@mikecebul I was unable to reproduce this. If you could provide a working reproduction, I can look into this further. Closing for now.

**Closed by jacobsfletch** 2024-11-19 18:26 UTC

**Comment by mikecebul** [comment] 2024-11-19 20:47
Thank you Jacob for taking the time to look at this. I tried again just now after updating to 3.0.1 from beta.134 and it's working without issue.

**Comment by mikecebul** [comment] 2024-11-19 23:28
My issue was completely user error. Somehow I ended up with a blank file and folder path to api/webhooks/stripe/route.ts. I'll remember its not worth wasting anyone's time to submit issues without a simple reproduction. Sorry about that.

**Comment by jacobsfletch** [comment] 2024-11-20 14:27
No worries, thanks for confirming!
