### ISSUE TITLE
RichText editor broken after fixing some formats in beforeValidate hook

### ISSUE THREAD

**Issue by Stupidism** [payloadcms/payload#1600] opened 2022-12-06 04:59 UTC
# Bug Report

## Steps to Reproduce

1. Prepare a malformed rich text like this
```
const listNodeWithWrongFormat: FixableList = {
      type: 'unordered-list',
      children: [
        {
          type: 'ul',
          children: [
            {
              type: 'list-item',
              children: [
                {
                  type: 'li',
                  children: [
                    {
                      text:
                        'Despite used-car prices falling a bit in recent months, lightly used versions of seven of the 10 best-selling vehicles in America are still worth more than the sticker price on comparable new 2022 models. That’s down from nine of 10 in June, adding to signs that the worst of the red-hot price increases for used vehicles are likely behind us. But it hardly points to a return to normal. ',
                    },
                  ],
                },
              ],
            },
            {
              type: 'list-item',
              children: [
                {
                  type: 'li',
                  children: [
                    {
                      text:
                        'In another sign of cooling, the market values of eight of those 10 lightly used versions of the best-selling vehicles have fallen since late August, the last time we conducted this study. The exceptions were the Ford F-150 and the Chevrolet Silverado, which both rose in value. ',
                    },
                  ],
                },
              ],
            },
            {
              type: 'list-item',
              children: [
                {
                  type: 'li',
                  children: [
                    {
                      text: 'Strong demand for electric vehicles (EVs) in this year of ',
                    },
                    {
                      type: 'link',
                      linkType: 'custom',
                      url: 'https://www.nytimes.com/interactive/2022/06/14/business/gas-prices.html',
                      children: [
                        {
                          text: 'record-high',
                        },
                      ],
                    },
                    {
                      text:
                        ' gas prices helped turn some of the EV market upside down as well. Three of the top five best-selling EVs from 2021 are now worth more lightly used than the sticker price on comparable new 2022 models. That’s the same number as in late August, although the values of all five used models have fallen since then.',
                    },
                  ],
                },
              ],
            },
            {
              type: 'list-item',
              children: [
                {
                  type: 'li',
                  children: [
                    {
                      text:
                        'The pace of annual price increases for used cars has slowed in recent months. Prices for used cars and trucks rose 7.2% in September from the previous year, down from a 41% jump in February.',
                    },
                  ],
                },
              ],
            },
            {
              type: 'list-item',
              children: [
                {
                  type: 'li',
                  children: [
                    {
                      text:
                        'Prices for used vehicles have actually fallen from the previous month for three straight months, but the declines have been minimal. In September, prices fell 1% from August. That was actually the second-biggest month-on-month decline this year, behind an 8% drop in March.',
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    };
```
2. write a beforeValidate hook

```
import type { FieldHook } from 'payload/types';
import { map, flatten } from 'lodash';

import type { Article, BlockNode, InlineNode, List } from '../some-where';

import { autoFixTableNode } from '../elements/RteTable/autoFixTableNode';

export interface FixableList {
  type: 'unordered-list' | 'ordered-list';
  children: {
    type: 'ul';
    children: {
      type: 'list-item';
      children: {
        type: 'li';
        children: InlineNode[];
        isVoid?: boolean;
      }[];
      isVoid?: boolean;
    }[];
    isVoid?: boolean;
  }[];
  isVoid?: boolean;
}

type FixablePayloadRichText = (BlockNode | FixableList)[];

const autoFixListNode = (node: FixableList): List => {
  const listItems = flatten(map(node.children, 'children'));
  const lis = flatten(map(listItems, 'children'));

  return {
    type: node.type === 'ordered-list' ? 'ol' : 'ul',
    children: lis,
  };
};

export const autoFixRichTextBeforeValidate: FieldHook<Article, FixablePayloadRichText | undefined> = ({ value }) => {
  if (!value) return value;

  return value.map((node) => {
    switch (node.type) {
      case 'unordered-list':
      case 'ordered-list': {
        return autoFixListNode(node) || node;
      }
      default:
        break;
    }

    return node;
  });
};

```

4. The page is blank, but after refresh it works again.
![image](https://user-images.githubusercontent.com/5801015/205819760-4468a566-6bf8-4a8d-b73c-859cdeb860ff.png)

5. After the autofix we can see version compare like this
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/5801015/205819698-152e53df-e76c-4312-91e6-c46353bda994.png">

6.

**Comment by jmikrut** [comment] 2022-12-06 14:45
Hey @Stupidism — I'm not sure what you are looking to see fixed here. Is there anything actionable that we should do? It seems like as far as Payload is concerned, having malformed rich text JSON _**will**_ cause Slate to break in unexpected ways. 

I'm assuming that your `beforeValidate` hook is attempting to rectify the broken rich text JSON but maybe there are still some aspects of it that are not valid, thus causing the Slate error you've shown.

I want to keep Payload issues related to things that are able to be addressed by Payload - so in this case, if you can provide any info about what exactly you are expecting Payload to do here, that would be great - otherwise, we can convert this to a Discussion and try to figure out what remains not valid in your rich text JSON after you attempted to fix it.

**Closed** 2022-12-08 16:39 UTC
Labels: possible-bug

**Comment by jmikrut** [comment] 2022-12-08 16:40
Hey @Stupidism — I figured out what was causing this and fixed it in the above commit. It was caused by having _**different**_ content be returned from the server, but Slate had its same selection. We needed to clear selection when the rich text `initialValue` changed. 

Will be released shortly!
