### ISSUE TITLE
TypeError: process.getuid is not a function

### ISSUE THREAD

**Issue by jurabek105** [payloadcms/payload#5107] opened 2024-02-18 06:21 UTC
### Describe the Bug

This error started appearing after I installed and configured cloud-storage-plugin. I configured s3 adpater + mongodb atlas. It is appearing after signing up/in to admin pages and everything stops to work. I did some research but could find only one page descring the issue which was totally useless.

Here is how I configured the s3 adapter:
```
cloudStorage({
      enabled: process.env.MY_CONDITION === 'true',
      collections: {
        'my-collection-slug': {
          adapter: s3Adapter({
            config: {
              endpoint: process.env.S3_ENDPOINT,
              forcePathStyle: process.env.S3_FORCE_PATH_STYLE === 'true',
              region: process.env.S3_REGION,
              credentials: {
                accessKeyId: process.env.S3_ACCESS_KEY_ID,
                secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
              },
            },
            bucket: process.env.S3_BUCKET,
          }),
        },
      },
    }),
```

If anyone knows at least someone that may help then pls reply me. If the information is not enough you can ask what you need.

### To Reproduce

1. Create E-Commerce template project using payloadcms
2. Install cloud-storage-plugin and connect s3 bucket + mongodb
3. The error should appear after signing in or signing up to admin page

I use npm to install all the packages.

The versions of packages:
@payloadcms/db-mongodb: 1.4.1
@payloadcms/plugin-cloud-storage: 1.1.2

### Payload Version

2.5.0

### Adapters and Plugins

db-mongodb cloud-storage-plugin

**Comment by DanRibbens** [comment] 2024-02-21 03:14
Duplicate of https://github.com/payloadcms/payload/issues/4952

**Closed by DanRibbens** 2024-02-21 03:14 UTC
Labels: [possible-bug], plugin: cloud-storage
