### ISSUE TITLE
[Bug] Discrepancy between code editor view, API view, and API response.

### ISSUE THREAD

**Issue by hunghvu** [payloadcms/payload#4067] opened 2023-11-09 06:20 UTC
### Describe the Bug

Let's have a look at the following images.

## Image 1:  In code editor view, the code field has all the indentation as expected.
![Screenshot from 2023-11-08 21-43-26](https://github.com/payloadcms/payload/assets/62678592/9e987c21-56d0-49a0-8724-38bb39ee421f)

## Image 2: In API view, we only have plain string without any marking of indentation.
![Screenshot from 2023-11-08 21-47-06](https://github.com/payloadcms/payload/assets/62678592/a96046ee-585f-4b8f-8fd6-86b23bc852b3)

_The below is an UTF-8 encoded representation. We only have `\x20`, meaning space character. In other words, the indentation is lost in API view._
```
\x69\x66\x20\x28\x74\x72\x75\x65\x29\x20\x7B\x20\x64\x6F\x20\x74\x68\x69\x73\x20\x7D\x20\x65\x6C\x73\x65\x20\x7B\x20\x64\x6F\x20\x74\x68\x61\x74\x20\x7D\x20\x65\x6C\x73\x65\x20\x69\x66\x20\x7B\x20\x2F\x2F\x20\x31\x32\x33\x20\x31\x32\x33\x20\x7D
```

## Image 3: In API response view, we can see new line characters, but we still lose the indentation using a tab.
![Screenshot from 2023-11-08 21-49-11](https://github.com/payloadcms/payload/assets/62678592/d41a9d52-ebe4-4a5d-bada-9d4b13d65ebd)

___

I'm not certain if this issue is only limited to Code Field (Monaco Editor), or if it is a sign of another problem.

### To Reproduce

Add a code field to any collection. Add content to the code field, and observe the behavior as described in the images.

### Payload Version

2.1.0

**Comment by hunghvu** [comment] 2023-11-10 05:10
![Screenshot from 2023-11-09 21-06-06](https://github.com/payloadcms/payload/assets/62678592/fb97b825-bac1-44ed-8492-9dd70383a77c)


After further look, the text layout is maintained when I expand the view of browser, or view directly in the database. In any case, I suppose the main issue that needs to be focused is making sure API view is as truthful as possible.

**Comment by AlessioGr** [comment] 2023-11-22 07:59
Hey @hunghvu I can't seem to reproduce this on my device. Here's the code field view:

![Screenshot 2023-11-22 at 08 50 00@2x](https://github.com/payloadcms/payload/assets/70709113/f9e80036-1426-4981-9617-ce7455f1ac7d)

and here's the API view:
![Screenshot 2023-11-22 at 08 50 28@2x](https://github.com/payloadcms/payload/assets/70709113/fb3a901b-b232-40fc-8d14-02f76da4a091)


As you can see, it does display the `\n` character in there.

Maybe this issue specific to your device. What's your operating system / browser / system locale?

**Comment by AlessioGr** [comment] 2023-12-09 17:48
Closing this for now, as I can't reproduce it. Feel free to re-open the issue with a reproduction. Here's a [reproduction guide](https://github.com/payloadcms/payload/blob/main/.github/reproduction-guide.md) :)

**Closed by AlessioGr** 2023-12-09 17:48 UTC
Labels: cant-reproduce
