### ISSUE TITLE
Payload cloud public envs undefined

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#4009] opened 2023-11-05 11:40 UTC
### Link to reproduction

n/a

### Describe the Bug

I have a custom react select component. This component fetches the api, using the server url from the env variables. However, all env variables are undefined. And yes, they have the PAYLOAD_PUBLIC_ prefix.

(PS: if there is a better wat to use globals in custom components, without fetching, please let me know. As far as I know local api is not usable here, because it is client-side)

### To Reproduce

- add a custom select component
- deploy to payload cloud
- add `console.log('envs', process.env)` to the React.useEffect function
- the following gets logged
```
envs {}
```

### Payload Version

2.0.13

### Adapters and Plugins

cloud

**Comment by silveltman** [comment] 2023-11-05 11:50
Found a solution [here](https://payloadcms.com/community-help/discord/is-it-possible-to-use-the-local-payload-api-in-custom-react-components-in-the-admin-dashboard-ui), getting serverURL with useConfig() hook.

Issue still seems relevant though.

**Comment by denolfe** [comment] 2024-01-10 20:03
I'm not able to recreate this. I've verified that `PAYLOAD_PUBLIC_*` values do make it to the front end.

1. I created a `ui` field on one of my collections

```tsx
export const EnvTest: React.FC<UIField> = () => {
  useEffect(() => {
    console.log(process.env.PAYLOAD_PUBLIC_SHOWME ?? 'process.env.PAYLOAD_PUBLIC_SHOWME is undefined')
  })

  return <div>{process.env.PAYLOAD_PUBLIC_SHOWME ?? 'process.env.PAYLOAD_PUBLIC_SHOWME is undefined'}</div>
}
```

```ts
{
  name: 'publicEnv',
  type: 'ui',
  admin: {
    components: {
      Field: (args) => EnvTest(args),
    },
  },
},
```

2. Set the `PAYLOAD_PUBLIC_SHOWME` in the Payload Cloud project.
3. Once deployed, loading a document of that collection properly shows the value in the UI as well as logs the value in console.

Closing as can't recreate, but I'd be happy to reopen if you can add more detail.

**Comment by carstenblt** [comment] 2024-02-12 09:08
@denolfe I am having the same problem right now using a `PAYLOAD_PUBLIC_` variable as part of `livePreview.url`. I am using the same variable in the same collection in a hook, where it is accessible.

**Comment by denolfe** [comment] 2024-04-02 14:30
Closing this for now as I could not reproduce, and a workaround is available.

@carstenblt If you can provide more detail, I can reopen.

**Closed by denolfe** 2024-04-02 14:30 UTC
Labels: [cant-reproduce], cloud-platform
