### ISSUE TITLE
Postgres Adapter: there is no parameter $1

### ISSUE THREAD

**Issue by dhatGuy** [payloadcms/payload#5937] opened 2024-04-20 22:34 UTC
### Describe the Bug

After running `yarn dev`, I get this error
```
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node src/server.ts -- -I`
error: there is no parameter $1
    at C:\Users\user\Documents\workspace\payload-sample\node_modules\pg-pool\index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)     
    at DrizzleORMPgClient.query (C:\Users\user\Documents\workspace\payload-sample\node_modules\drizzle-kit\payload.js:34498:21)
    at C:\Users\user\Documents\workspace\payload-sample\node_modules\drizzle-kit\payload.js:2259:46
```

I'm running on Windows

### To Reproduce

1. npx create-payload-app
2. run yarn dev

### Payload Version

2.13.0

### Adapters and Plugins

db-postgres

**Comment by DanRibbens** [comment] 2024-04-21 02:17
I can't reproduce on windows. I used the blank template on v2.13.0 and mine was able to start without an issue. Did you have any errors when installing dependencies?

We'll need more info to recreate the issue in order to fix it. I'm going closing this issue but tag me if you need to repoen it.

Thanks!

**Closed by DanRibbens** 2024-04-21 02:17 UTC
Labels: [possible-bug], [cant-reproduce], [missing-reproduction]

**Comment by dhatGuy** [comment] 2024-04-21 03:27
I was using an existing database. I had to create a new one. Thanks

**Comment by DanRibbens** [comment] 2024-04-21 04:42
@dhatGuy NP! I'm glad it was something simple.

**Comment by thedevdavid** [comment] 2024-04-26 17:52
@DanRibbens, So, how to use Payload when integrating into an existing database?

**Comment by DanRibbens** [comment] 2024-04-26 20:42
> @DanRibbens, So, how to use Payload when integrating into an existing database?

I recommend opening a new discussion and give some background info on what you are trying to achieve.
