### ISSUE TITLE
saving collection makes all collapsed array-fields to 'show'

### ISSUE THREAD

**Issue by vincentvandijck** [payloadcms/payload#809] opened 2022-07-24 20:31 UTC
Saving a collection makes all collapsed array-fields to unfold/show.

before save:
![image](https://user-images.githubusercontent.com/10504064/180664671-edfb03fd-c380-4d0d-9d1e-5b6aac894d7c.png)

after save:
![image](https://user-images.githubusercontent.com/10504064/180664686-7107282c-e701-4215-a3a6-0f229229278d.png)

**Comment by jmikrut** [comment] 2022-07-25 13:47
Got it - this is reproduced and we'll have a fix. I noticed #813 but that is actually not the way to fix this, because that `useEffect` hook _needs_ to be run when `formContext` changes due to the need to recalculate array lengths if hooks change the returned data from the server.

But the Payload team will take a crack into this!

**Comment by jmikrut** [comment] 2022-07-25 22:04
Fixed and will be released in the next patch version. 👍

**Closed** 2022-07-25 22:03 UTC
Labels: bug
