### ISSUE TITLE
Unique index not always generating

### ISSUE THREAD

**Issue by edtorba** [payloadcms/payload#2007] opened 2023-02-02 21:26 UTC
`unique: true` property seems not to be functioning. I have tried using it with `index: true` combination, but no luck 😕

Here's what I got:
```ts
import { Field } from 'payload/types';
import { merge } from 'lodash';
import FormatSlug from '../hooks/formatSlug';

type SlugType = (
  options?: {
    fieldToUse?: string,
    overrides?: Record<string, unknown>,
  }
) => Field;

const Slug: SlugType = ({
  fieldToUse = 'title',
  overrides = {},
} = {}) => {
  const dynamicSlug: Field = {
    name: 'slug',
    label: 'Slug',
    type: 'text',
    unique: true,
    admin: {
      position: 'sidebar',
    },
    hooks: {
      beforeValidate: [
        FormatSlug(fieldToUse),
      ],
    },
  };

  return merge(dynamicSlug, overrides);
};

export default Slug;
```

Properly added to fields list within my collection, e.g.
```ts
fields: [
  ...
  {
    name: 'title',
    type: 'text',
    required: true,
    index: true,
  },
  Slug(),
  ...
]
```

From admin/cms perspective everything is fine. The main problem is that for some reason I am missing index with unique property for my slug field, and to top it up, can't see index for title field either. Have tried numerous things, even dropping collection table, with hopes that freshly generated one will be fine, but unfortunately no cigar. 

<img width="1147" alt="Screenshot 2023-02-02 at 21 16 20" src="https://user-images.githubusercontent.com/2422019/216451455-9974ab04-1074-49a3-8945-b68e3d1732ce.png">

Payload v1.6.3

**Comment by edtorba** [comment] 2023-02-02 21:36
Interestingly, I have just randomly added additional field to my collection

```ts
    {
      name: 'random',
      type: 'text',
    },
```

and that made it generate all missing indexes

<img width="1147" alt="Screenshot 2023-02-02 at 21 36 07" src="https://user-images.githubusercontent.com/2422019/216455047-831fe766-8359-4eed-97f5-42798f9abcbd.png">

**Comment by edtorba** [comment] 2023-02-02 21:57
I believe steps to recreate are:
- create collection
- let payload generate table for it
- add slug field

or
- create collection
- let payload generate table for it
- drop table for the collection
- add slug field

**Comment by DanRibbens** [comment] 2023-02-06 17:16
I can't reproduce your issue.

Your steps dont match this, but the only thing thing I can think is that Payload won't replace an existing index, even if it changes. For example if your collection already had `index: true` on your slug field, then you started again after changing it to `unique: true`. In that case you'd still see the original (non-unique) index until you delete the index (or entire collection) and started again.
Having both index and unique `true` is the same as having just `unique: true`. 

What version of Mongo are you using? Have you set custom settings for your mongoose connection? I can't think of anything else that would be a factor here. 

It is not ideal, but you can always manually manage your indexes as a fallback to having the generated ones.

**Comment by edtorba** [comment] 2023-02-07 09:50
Not on my laptop at the moment, but I'll have another go this evening, will see if I can provide more accurate steps 👍

**Comment by DanRibbens** [comment] 2023-02-07 17:24
I'm going to close this for now since I can't do anything more for it. Feel free to re-open and let me know how it goes!

**Closed by DanRibbens** 2023-02-07 17:24 UTC
Labels: possible-bug, cant-reproduce
