### ISSUE TITLE
ACL access.update args are missing `id` and `data` params

### ISSUE THREAD

**Issue by zazz-ops** [payloadcms/payload#4935] opened 2024-01-28 05:31 UTC
### Describe the Bug

I'm attempting to write a simple RBAC module for the app I'm building and I've run into an issue where the `id` and `data` params are missing from the args in the `access.update` function. The args are supposed to contain `req, id, data`. However, only the `req` param is coming through to any of my access functions, either at the collection level or at the field level.

Here's an illustration:
```
update: ({ req : { user }, id, data }) => {
	console.log(user)
	console.log(id) <-- undefined
	console.log(data) <-- undefined

        return allowedRoles(['author','sysadmin'], user, id, data)
}
```

And then in my `allowedRoles` function I use the `user.id` and `data.createdBy` field to identify a "virtual" `author` role that allows the user to modify any data that they themselves created:
```
const allowedRoles = (roles, user, id, data) => {
	if (roles.includes('author') && user.id === data.createdBy) {
		return true
	}

	if (roles.includes(user.role)) {
		return true
	}

	return false
}

export {
	allowedRoles
}
```

So you can see that without the `data` param being populated, it's impossible for me to identify the author of the original document that the update operation is targetting.

In the documentation it makes it very clear that these params should be expected:
https://payloadcms.com/docs/access-control/collections#update

But Payload simply does not function like this.

I also found another issue where the dev was having a similar issue, and there was much talk about different layers of evaluation for the access functions and that you tested that these values were being populated when a specific document was being update. Except they're not, the values remain `undefined`.

Please advise on when these params can be reliably accessed. I'm dead in the water now because of this and looking around at other solutions ...

### To Reproduce

Use payload.

### Payload Version

2.8.1

**Comment by zazz-ops** [comment] 2024-01-31 04:12
@AlessioGr The recreation is pretty straightforward. Spin up an instance of payload and then log the `id` and `data` args from any `access.update` function.

Here's what my `CollectionConfig` looks like:
```
import { CollectionConfig } from 'payload/types'
import { allowedRoles } from '../../utilities/rbac/rbac.ts'

const accounts: CollectionConfig = {
	slug: 'accounts',
	auth: true,
	access: {
		create: () => true,
		unlock: ({ req: { user } }) => {
			return allowedRoles(['sysadmin'], user)
		},
		read: ({ req: { user } }) => {
			if (user) return true
		},
		update: ({ req : { user }, id, data }) => {
			console.log('user:')
			console.log(user)
			console.log('id:')
			console.log(id)
			console.log('data:')
			console.log(JSON.stringify(data, null, 3))

			return allowedRoles(['self','sysadmin'], user, id)
		},
		admin: ({ req: { user } }) => {
			return allowedRoles(['sysadmin','engineer'], user)
		}
	},
	admin: {
		useAsTitle: 'email'
	},
	fields: [
        ...
```

And when I run my tests I see Payload log the following to my console:
<img width="458" alt="image" src="https://github.com/payloadcms/payload/assets/151117554/0f1a7ca4-172c-43d2-8056-3923da843c71">

**Comment by zazz-ops** [comment] 2024-02-03 04:35
@AlessioGr What do you need from me to address this? I'm at a total standstill with development because of this issue and nothing I've tried has data flowing through the `id` or `data` params in my access functions.

**Comment by jmikrut** [comment] 2024-02-07 20:11
Hey @zazz-ops — here's some info for you.

The `update` access control function certainly does receive `id` and `data`, but as you mentioned:

> I also found another issue where the dev was having a similar issue, and there was much talk about different layers of evaluation for the access functions and that you tested that these values were being populated when a specific document was being update. Except they're not, the values remain undefined.

This is 100% true. I just set up a reproduction:

```ts
export const PostsCollection: CollectionConfig = {
  slug: 'posts',
  access: {
    update: ({ req, id, data }) => {
      console.log({
        user: req.user?.id,
        id,
        data,
      })

      return true
    },
  },
  fields: [
    {
      name: 'text',
      type: 'text',
    },
  ],
}
```

 and I see the following three console logs when going to update a Post:

**Running the `/api/access` function:**

```
{ user: '65c3e32aa91a057cd16dff8c', id: undefined, data: {} }
```

**Loading the document-specific access upon visiting the Edit screen (prior to submitting any data):**

```
{
  user: '65c3e32aa91a057cd16dff8c',
  id: '65c3e32ba91a057cd16dff92',
  data: {}
}
```

**Finally, upon submitting the ACTUAL update request:**

```
{
  user: '65c3e32aa91a057cd16dff8c',
  id: '65c3e32ba91a057cd16dff92',
  data: {
    text: 'example post',
    updatedAt: '2024-02-07T20:08:11.392Z',
    createdAt: '2024-02-07T20:08:11.392Z'
  }
}
```

This is all functioning as intended, so I am going to close this issue. If you can provide a reproduction where the third access execution that I listed above does NOT pass the `id` and `data` as I have shown, then we will re-open and take a peek.

Thank you!

**Closed by jmikrut** 2024-02-07 20:11 UTC
Labels: [possible-bug], [missing-reproduction]

**Comment by zazz-ops** [comment] 2024-02-15 05:59
@jmikrut Ah, I think i see where the disconnect is. I'm not using the UI Console. I'm using mocha to run automated tests against the `/api/*` endpoints.

In fact, I'm not really interested in using the UI Console. My plan was to use Payload as an API layer and build a completely bespoke UI layer. I thought the baked-in UI Console might be useful for sysadmin purposes, but otherwise all I want from Payload is a backend. And it seems that your hooks are designed in a way that it might not be possible to get Payload to do what I need it to.

Considering the CollectionConfig code already posted above, when I run my test and it fires a standard `fetch` request at the Payload API I need the `id` and `data` in the `access.update` hook args to be populated. It only fires once, and those params are always `undefined`.

Here's an example from my tests. It's a `fetch` request, just wrapped in a little sugar client I create called `nova` to keep the code dry.

```
it('should allow publisher to update their own profile.bio', async () => {
		const result = await nova({
			method : 'PATCH',
			path : 'accounts',
			credentials : 'include',
			authToken : $db.accounts.publisher.authToken,
			query : {
				depth: 0,
				where: {
					email: {
						equals: 'ops+publisher@novazine.xyz'
					}
				}
			},
			data : {
				profile : {
					bio : 'Testing testing testing ...'
				}
			}
		})

		if (result.errors?.length) log(result)
		expect(result.errors).to.be.an('array').that.is.empty

		$db.accounts.publisher.account = result.docs[0]
		log($db.accounts.publisher.profile)
	})
```

So if my app is only interfacing with Payload via its API, how would I write an RBAC plugin if the "extra" args in the hooks are never populated unless my user is using the UI Console?

**Comment by DanRibbens** [comment] 2024-02-15 18:16
Hi @zazz-ops,

The admin UI makes http requests to the API the same as you're doing, so that isn't a factor here.

The `PATCH` request that you've shared is the one used for bulk updates. Rather than updating it using a `where` query you shuld instead add the `id` of the user to the URL path. You should have access to the user id and if you don't, you could get it from decoding the authToken in your snippet using `jwt-decode` and get the id of the user that way. 

Then your access function will have an id just like you're looking for.

```ts
		const result = await nova({
			method : 'PATCH',
			path : `accounts/${id}`,
			credentials : 'include',
			authToken : $db.accounts.publisher.authToken,
			query : {
				depth: 0,
			},
			data : {
				profile : {
					bio : 'Testing testing testing ...'
				}
			}
		})
```

Does this help?

**Comment by zazz-ops** [comment] 2024-02-16 06:20
@DanRibbens It sure does! Thanks for this. I'd been assuming that Payload was garnering the `id` from the `authToken`. Perhaps the batch endpoint should throw an error/warning in the case where only a single record is being updated.

So I'm seeing the `id` and the `data` params populated on the third invocation of the `access.update` function. This isn't perfect, but I'm back to moving forward.

It seems a strange architectural choice you've made that params are twice `undefined` until they're not. Would it not be far less confusing to have different hooks for the first two firings?

When I write an access control function for `access.update` my expectation is it runs immediately before any updates only, and always has the promised params populated.
