### ISSUE TITLE
cannot use 'in' operator error

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#7764] opened 2024-08-19 19:19 UTC
### Payload Version

beta.84

### Describe the Bug

const contentTabs: TabsField = {
  type: 'tabs',
  tabs: [
    {
      name: 'somefield',
      fields: [],
    }
]
}

![CleanShot 2024-08-19 at 15 19 44](https://github.com/user-attachments/assets/708a227e-2c94-4da7-bbd4-65c06aae6c79)

https://discord.com/channels/967097582721572934/1215659716538273832/1275171459756458084

**Comment by andershermansen** [comment] 2024-08-19 19:41
I found this as well while testing #7355 and fixed it in that PR.

Fixed line: https://github.com/payloadcms/payload/pull/7355/files#diff-f66be167f6e4f1b3230c9c2ea83789a180cd4b86a7074538d6305cc6a1afc664

**Comment by andershermansen** [comment] 2024-08-19 19:42
Because I thought it was regarding the changes to columns. But I see now that it was reproducable without my changes as well.

**Comment by paulpopus** [comment] 2024-08-20 18:46
Fixed in https://github.com/payloadcms/payload/pull/7776

**Closed by paulpopus** 2024-08-20 18:46 UTC
Labels: v3, created-by: Payload team
