### ISSUE TITLE
Cannot use 'in' operator to search for '_rels' in undefined

### ISSUE THREAD

**Issue by D0nte53** [payloadcms/payload#7742] opened 2024-08-17 13:32 UTC
### Describe the Bug

I was initializing my database when suddenly the mentioned error appeared. After a long debugging session, I found that the potential source of the issue was the simultaneous creation of more than 9 records. 

I would like to confirm if my diagnosis of the problem is correct and if this behavior is expected. If so, I would greatly appreciate a canonical example demonstrating the proper way to create multiple records.

Additionally, I would like to understand why this error is related to simultaneous writes, as this isn't immediately clear to me. Lastly, if possible, please provide a link to the documentation so I can better understand my mistake.

Thank you for reading. Have a great day!

### To Reproduce

```typescript
async () => {
    let prom_arr = []
    for (let i = 0; i < _data.length; i++) {
    
        if (i && i % 9 == 0) await Promise.all(prom_arr) //without this line, the error occurs.
        
        const _item = JSON.parse(JSON.stringify(_data[i]))
        const c = payload.create({
            collection: collection_name,
            data: _item
        })
        
        prom_arr.push(c)
    }
    if (prom_arr.length) await Promise.all(prom_arr)
}
```

NB: I’m working on a PostgreSQL database on Supabase

### Payload Version

2.0.0

### Adapters and Plugins

postgresAdapter

**Comment by r1tsuu** [comment] 2024-08-30 01:14
Hey @D0nte53, thank you for the report.

I can't reproduce the issue on the latest beta + Supabase instance with this code (tried 30 / 60 / 100 concurrent writes):
```ts
const data: { text: string }[] = Array.from({ length: 30 }, () => ({
  text: `some_text_${randomBytes(10).toString('hex')}`,
}))

const promises: Promise<ConcurrentWrite>[] = []

data.forEach((item) =>
  promises.push(payload.create({ collection: 'concurrent-writes', data: item })),
)

await Promise.all(promises)

payload.logger.info(`created ${data.length} docs concurrently`)
```

Also, I would highly recommend you to do these types of operations in a single transaction, like this:
```ts
import { commitTransaction, initTransaction, killTransaction } from 'payload'
import type { PayloadRequest } from 'payload'

const data: { text: string }[] = Array.from({ length: 100 }, () => ({
  text: `some_text_${randomBytes(10).toString('hex')}`,
}))

const promises: Promise<ConcurrentWrite>[] = []

const req = { payload } as PayloadRequest

await initTransaction(req)

data.forEach((item) =>
  promises.push(payload.create({ collection: 'concurrent-writes', req, data: item })),
)

try {
  await Promise.all(promises)
  await commitTransaction(req)
  payload.logger.info(`created ${data.length} docs concurrently`)
} catch (e) {
  await killTransaction(req)
  payload.logger.error(`failed to create the docs, err: `, e)
}
```

It you can reproduce this on the beta, we can look into this again, closing for now.

**Closed by r1tsuu** 2024-08-30 01:14 UTC
Labels: db-postgres, v2
