### ISSUE TITLE
Collection browser fail to reset page when increasing number of entries per page

### ISSUE THREAD

**Issue by william-price-speedoc** [payloadcms/payload#1913] opened 2023-01-19 08:55 UTC
# Bug Report

Collection entries current page doesn't reset to accommodate number of entries shown when the number of results per page is increased

## Steps to Reproduce

1. Open any collection with multiple pages of entries, choose "last page" of entries
2. Change number of entries per page to a higher number (i.e. 5->50, 50-> 100, etc)

## Other Details

Payload 1.5.8

![image](https://user-images.githubusercontent.com/121593213/213397764-fa7cf44b-7fab-437b-bb43-12b5cbc8c297.png)

**Comment by JarrodMFlesch** [comment] 2023-01-19 20:45
Closing - duplicate of [1913](https://github.com/payloadcms/payload/issues/1912) 👀

**Closed by JarrodMFlesch** 2023-01-19 20:45 UTC
Labels: possible-bug
