### ISSUE TITLE
Admin dashboard crashes after clicking "clear" button in "compare version" select

### ISSUE THREAD

**Issue by mateusz-domanski-ip** [payloadcms/payload#3309] opened 2023-09-11 12:55 UTC
### Link to reproduction

https://github.com/payloadcms/public-demo

### To Reproduce

1. visit https://demo.payloadcms.com/admin/collections/pages and open one of the existing pages
2. go to page's versions page (https://demo.payloadcms.com/admin/collections/pages/64ff0219de24cf7b36a5233a/versions)
3. go to the details of any version (https://demo.payloadcms.com/admin/collections/pages/64ff0219de24cf7b36a5233a/versions/64ff0219de24cf7b36a52345)
4. click "x" button in "compare version against" select:

![image](https://github.com/payloadcms/payload/assets/143408850/a899ecf7-6e27-4c5c-90d4-a22a28ff3a5e)

You should see a blank screen with such error in the console:

![image](https://github.com/payloadcms/payload/assets/143408850/8de44211-55d9-4ff2-b5d7-f39bbb94f5b9)

### Describe the Bug

Hi there, I noticed that you can crash admin dashboard by visiting the version comparison page and clicking the "clear" button when selecting a version for comparison.

I hope the public demo is enough for reproduction. Thanks!

### Payload Version

1.15.2

**Comment by limistah** [comment] 2023-09-12 11:08
I can reproduce this bug.

**Comment by PatrikKozak** [comment] 2023-10-30 17:04
Hey @mateusz-domanski-ip - this has been fixed with this [PR](https://github.com/payloadcms/payload/pull/3901) for `2.0` and also this [PR](https://github.com/payloadcms/payload/pull/3413) for `1.x`. We went ahead and just removed the ability to `clear` the compare versions select field since we're just comparing two different versions.

Great find - thank you!

**Closed by PatrikKozak** 2023-10-30 17:04 UTC
Labels: possible-bug
