### ISSUE TITLE
10 New Errors after using Cloud Storage Adapter

### ISSUE THREAD

**Issue by AdvithShetty** [payloadcms/payload#5441] opened 2024-03-24 05:00 UTC
### Describe the Bug

I am trying to connect my digital ocean space as s3 storage to payload and followed this guide - https://resisted-garden-7ad.notion.site/Payload-CMS-Adding-S3-Storage-20f897e979df4f45b8b7c98a83e50f95

But for some reason i am getting 10 Errors as follows :

`[nodemon] restarting due to changes...
webpack building...
[nodemon] starting `ts-node src/server.ts -- -I`
[10:22:55] INFO (payload): Starting Payload...
[10:22:56] INFO (payload): Payload Admin URL: /admin
webpack built 2f291e9de8d167bdcdbc in 3280ms
ERROR in ./node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/s3/handleUpload.js 136:49-62
Module not found: Error: Can't resolve 'fs' in 'C:\Quixta Projects\igauge\igauge-backend\node_modules\@payloadcms\plugin-cloud-storage\dist\adapters\s3'

ERROR in ./node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/s3/webpack.js 64:49-62
Module not found: Error: Can't resolve 'fs' in 'C:\Quixta Projects\igauge\igauge-backend\node_modules\@payloadcms\plugin-cloud-storage\dist\adapters\s3'

ERROR in ./node_modules/detect-file/index.js 7:9-22
Module not found: Error: Can't resolve 'fs' in 'C:\Quixta Projects\igauge\igauge-backend\node_modules\detect-file'

ERROR in ./node_modules/findup-sync/index.js 4:13-26
Module not found: Error: Can't resolve 'fs' in 'C:\Quixta Projects\igauge\igauge-backend\node_modules\findup-sync'

ERROR in ./node_modules/global-prefix/index.js 7:9-22
Module not found: Error: Can't resolve 'fs' in 'C:\Quixta Projects\igauge\igauge-backend\node_modules\global-prefix'

ERROR in ./node_modules/homedir-polyfill/index.js 2:9-22
Module not found: Error: Can't resolve 'os' in 'C:\Quixta Projects\igauge\igauge-backend\node_modules\homedir-polyfill'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
        - install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "os": false }

ERROR in ./node_modules/homedir-polyfill/polyfill.js 2:9-22
Module not found: Error: Can't resolve 'fs' in 'C:\Quixta Projects\igauge\igauge-backend\node_modules\homedir-polyfill'

ERROR in ./node_modules/isexe/index.js 1:9-22
Module not found: Error: Can't resolve 'fs' in 'C:\Quixta Projects\igauge\igauge-backend\node_modules\isexe'

ERROR in ./node_modules/isexe/mode.js 3:9-22
Module not found: Error: Can't resolve 'fs' in 'C:\Quixta Projects\igauge\igauge-backend\node_modules\isexe'

ERROR in ./node_modules/isexe/windows.js 3:9-22
Module not found: Error: Can't resolve 'fs' in 'C:\Quixta Projects\igauge\igauge-backend\node_modules\isexe'

webpack compiled with 10 errors
`

Below is my Code

`import path from 'path'
import { postgresAdapter } from '@payloadcms/db-postgres'
import { webpackBundler } from '@payloadcms/bundler-webpack'
import { slateEditor } from '@payloadcms/richtext-slate'
import { buildConfig } from 'payload/config'
import { s3Adapter } from '@payloadcms/plugin-cloud-storage/s3';
import { cloudStorage } from '@payloadcms/plugin-cloud-storage';
import Users from './collections/Users'
import Institutions from './collections/Institutions'

const storageAdapter = s3Adapter({
  config: {
    endpoint: process.env.S3_ENDPOINT,
    region: process.env.S3_REGION,
    credentials: {
      accessKeyId: process.env.S3_ACCESS_KEY,
      secretAccessKey: process.env.S3_SECRET_KEY,
    }
  },
  bucket: process.env.S3_BUCKET_NAME,
});

// @ts-ignore
export default buildConfig({
  admin: {
    user: Users.slug,
    bundler: webpackBundler(),
  },
  editor: slateEditor({}),
  collections: [Users, Institutions],
  typescript: {
    outputFile: path.resolve(__dirname, 'payload-types.ts'),
  },
  graphQL: {
    schemaOutputFile: path.resolve(__dirname, 'generated-schema.graphql'),
  },

  plugins: [
    cloudStorage({
      collections: {
        'Institutions': {
          adapter: storageAdapter,
        },
      },
    }),
  ],

  db: postgresAdapter({
    pool: {
      connectionString: process.env.DATABASE_URI,
    },
  }),
})`

### To Reproduce

I ran npm run dev to test this

### Payload Version

Latest Version, I installed it yesterday

### Adapters and Plugins

Cloud Storage Adapter

**Comment by denolfe** [comment] 2024-04-03 18:51
Dupe of #4215 . Workaround can be found there.

**Closed by denolfe** 2024-04-03 18:51 UTC
Labels: [possible-bug], plugin: cloud-storage
