### ISSUE TITLE
beta 73 fail to run migrations on postgresql

### ISSUE THREAD

**Issue by WilsonLe** [payloadcms/payload#7492] opened 2024-08-03 03:38 UTC
### Link to reproduction

https://github.com/WilsonLe/payload-reproduce/tree/2-migration-fail

### Payload Version

3.0.0-beta.72 (edit: also not fixed in beta 73)

### Node Version

Node.js v20.15.1

### Next.js Version

15.0.0-canary.53

### Describe the Bug

Running `pnpm payload migrate:create` on projects with existing migrations file fails for payload beta 72. Beta 71 still works.

The error log is:

```sh
file:///~/Code/payload-reproduce/node_modules/.pnpm/payload@3.0.0-beta.72_@swc+core@1.7.5_@swc+helpers@0.5.11__@swc+types@0.1.12_graphql@16.8.1_typescript@5.5.4/node_modules/payload/dist/bin/migrate.js:75
                throw new Error(`Error creating migration: ${err.message}`);
                      ^

Error: Error creating migration: [
  {
    "received": "5",
    "code": "invalid_literal",
    "expected": "7",
    "path": [
      "version"
    ],
    "message": "Invalid literal value, expected \"7\""
  },
  {
    "received": "pg",
    "code": "invalid_literal",
    "expected": "postgresql",
    "path": [
      "dialect"
    ],
    "message": "Invalid literal value, expected \"postgresql\""
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "tables",
      "users",
      "indexes",
      "users_created_at_idx",
      "columns",
      0
    ],
    "message": "Expected object, received string"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "tables",
      "users",
      "indexes",
      "users_email_idx",
      "columns",
      0
    ],
    "message": "Expected object, received string"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "tables",
      "media",
      "indexes",
      "media_created_at_idx",
      "columns",
      0
    ],
    "message": "Expected object, received string"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "tables",
      "media",
      "indexes",
      "media_filename_idx",
      "columns",
      0
    ],
    "message": "Expected object, received string"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "tables",
      "payload_preferences",
      "indexes",
      "payload_preferences_key_idx",
      "columns",
      0
    ],
    "message": "Expected object, received string"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "tables",
      "payload_preferences",
      "indexes",
      "payload_preferences_created_at_idx",
      "columns",
      0
    ],
    "message": "Expected object, received string"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "tables",
      "payload_preferences_rels",
      "indexes",
      "payload_preferences_rels_order_idx",
      "columns",
      0
    ],
    "message": "Expected object, received string"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "tables",
      "payload_preferences_rels",
      "indexes",
      "payload_preferences_rels_parent_idx",
      "columns",
      0
    ],
    "message": "Expected object, received string"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "tables",
      "payload_preferences_rels",
      "indexes",
      "payload_preferences_rels_path_idx",
      "columns",
      0
    ],
    "message": "Expected object, received string"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "tables",
      "payload_migrations",
      "indexes",
      "payload_migrations_created_at_idx",
      "columns",
      0
    ],
    "message": "Expected object, received string"
  }
]
    at migrate (file:///~/Code/payload-reproduce/node_modules/.pnpm/payload@3.0.0-beta.72_@swc+core@1.7.5_@swc+helpers@0.5.11__@swc+types@0.1.12_graphql@16.8.1_typescript@5.5.4/node_modules/payload/dist/bin/migrate.js:75:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.15.1
```

### Reproduction Steps

Clone the reproduce and checkout to the `2-migration-fail` branch. I can still create migrations on beta 71 but once I upgraded to beta 72, it gives me an error.

### Adapters and Plugins

db-postgres

**Comment by WilsonLe** [comment] 2024-08-03 03:41
After some digging I narrowed down the commit that updates `drizzle-orm` and `drizzle-kit` which cause this issue.

https://github.com/payloadcms/payload/commit/0758199

**Comment by genox** [comment] 2024-08-05 06:34
I have the same issue migrating from beta 70 to 73. Additionally, the drizzle-kit version used in 73 seems to have an issue with enums, see https://github.com/drizzle-team/drizzle-orm/issues/2389 - this also throws errors for me.

Regarding migrations, I can create a new initial migration if I delete all existing migrations. But it would be great if there is a way that would not require a db wipe.

**Comment by yobottehg** [comment] 2024-08-05 07:51
Same issue here. Due to multiple issues with postgres / other things we're currently stuck on beta.67

**Comment by DanRibbens** [comment] 2024-08-05 17:06
I was able to reproduce this. We're working with Drizzle on fixing it. Previously we have been able to migrate the versions of schemas that drizzle creates and now it appears we are no longer able to.

It may be possible to generate a new migration snapshot using drizzle-kit's introspection feature prior to creating new migrations in Payload. This is just an idea of a possible workaround until we have a fix.

**Comment by denolfe** [comment] 2024-08-05 18:53
Closed by #7514

**Comment by denolfe** [comment] 2024-08-05 20:24
Apologies, everyone. The above PR is regarding the [enum comment](https://github.com/payloadcms/payload/issues/7492#issuecomment-2268281720), but not the migration creation.

Reopening. Still waiting on Drizzle for this one.

**Comment by WilsonLe** [comment] 2024-08-06 14:38
@denolfe Where can I track drizzle's progress on this issue?

**Comment by yobottehg** [comment] 2024-08-06 14:42
I think the drizzle-kit repo is private. But I'm also interested.

**Comment by faxg** [comment] 2024-08-06 17:30
Still having the issue in beta 74. Is there a manual workaround to migrate schema?

**Comment by r1tsuu** [comment] 2024-08-07 13:59
> I think the drizzle-kit repo is private. But I'm also interested.

Is there any reasons why they don't want to open source it? I feel like we have some complications because of this

**Comment by DanRibbens** [comment] 2024-08-07 14:12
They just *did* open source drizzle-kit a week ago.

https://github.com/drizzle-team/drizzle-orm/tree/main/drizzle-kit

**Comment by yobottehg** [comment] 2024-08-07 19:22
Just to confirm: Beta 75 solves the migration:create issue.

**Comment by DanRibbens** [comment] 2024-08-07 19:41
Thanks @yobottehg!

**Closed by DanRibbens** 2024-08-07 19:41 UTC
Labels: status: verified, v3, dependency-issue, created-by: Contributor
