### ISSUE TITLE
Scroll & performance issue on a page with large number of blocks

### ISSUE THREAD

**Issue by vibhor-web-headout** [payloadcms/payload#5991] opened 2024-04-24 08:27 UTC
### Link to reproduction

https://github.com/vibhor-web-headout/payload-repro/tree/feat-page-perf-bug

### Describe the Bug

Adding a huge number of blocks (~20) to the page causes the page rendering to deteriorate.
The blocks show a blank space for a couple of seconds upon being scrolled. For a complex block (a decent number of fields), the page sometimes crashes.
Sometimes the page is jittery upon scrolling and after rendering the block fields upon scrolling to a certain block, the fields can be unresponsive (click/hover) when interacting.

Mostly observed in blocks that may have a block/array/group field within them.
Upon replicating with a block with a single rich-text field with massive data, the page performance & responsiveness wrt user interaction were not a problem.

The initial hunch is the `Renderfields` component that attaches but doesn't remove a bunch of intersection observers.

Screen recording:

https://github.com/payloadcms/payload/assets/114465851/d9af0fbb-df0c-410b-9737-8c4fe012f5fd

NOTE: The performance in the reproduction is better than the issue faced on my core repo. The example is the same in both the example repo and mine. Not sure at this point, if having items in multiple tabs is the reason.

### To Reproduce

1. Install & launch the branch in development
2. Add a block called `Card section` to the `Content` tab of the page
3. Add a card within a card-section block. Make sure to fill in all the details and significant text to rich-text
4. Duplicate this card within the card section to around 8-10.
5. Duplicate this `card-section` block to go till around 20.

Observe the scrolling behavior.

### Payload Version

2.12.1

**Comment by jmikrut** [comment] 2024-04-24 13:47
Hey @vibhor-web-headout — have you tried this on 3.x yet? We've off-loaded a lot of the causes of re-rendering to the server, which improves the rendering performance of lots of fields pretty significantly.

I also do think that this has to do with having multiple Payload tabs open (especially in development) due to Webpack's HMR being connected to each of your tabs. 

We do clean up our `IntersectionObserver`s, though, and the reason that we use them is actually due to performance in the first place (a block only renders when it appears on the screen). 

How far along are you in your project?  In the event that you still see performance implications on 3.x, are you able to simplify / abstract your content model to remove some of the content from the top-level page? You could also use a single Lexical Rich Text field with `blocks` which would cut down on the amount of fields you are rendering on your edit view.

There are probably a few other options here but I don't think there's anything we can do further to 2.x at this point besides the optimizations that are already in place. However, with 3.x, we do expect performance improvements.

Will you let me know about the above? I will close this for now as at some point, too many fields is just too many fields (even for React). Not much we can do at a certain point.

Does all of this make sense?

**Closed by jmikrut** 2024-04-24 13:47 UTC
Labels: [possible-bug]
