### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'width') when using Preview mode

### ISSUE THREAD

**Issue by Thijmen** [payloadcms/payload#7849] opened 2024-08-24 20:52 UTC
### Payload Version

beta.91

### Node Version

20.12.1

### Next.js Version

15.0.0-canary.104

### Describe the Bug

After leaving the "Preview popup", the following error will present:
```
TypeError: Cannot read properties of undefined (reading 'width') 
```

### Reproduction Steps

1. Create a sample post in the admin panel
2. Press "Live Preview"
3. Wait for the preview to show
4. Open the mobile view ("Responsive dropdown", as shown on image 1)
5. Press the "link"-alike button to open the preview in a popup (as shown on image 2)
6. Wait for the popup to open and the page to have rendered
7. Close the popup

The error message `TypeError: Cannot read properties of undefined (reading 'width')` should be shown now.

# Image 1
<img width="671" alt="image" src="https://github.com/user-attachments/assets/cef411ce-9d10-496c-a865-a90d2786bdff">

# Image 2
<img width="148" alt="image" src="https://github.com/user-attachments/assets/d0e3a778-27e5-48a8-862c-0ae0b7a85311">

**Comment by paulpopus** [comment] 2024-09-12 23:29
Looks like this has been fixed now, probably a previous PR! Let me know if you can still reproduce it on the newest beta

**Closed by paulpopus** 2024-09-12 23:29 UTC
Labels: v3
