### ISSUE TITLE
Payload admin crashes when adding an image to a richtext field inside a Block.

### ISSUE THREAD

**Issue by DennisSnijder** [payloadcms/payload#3991] opened 2023-11-03 15:23 UTC
### Link to reproduction

https://github.com/DennisSnijder/payload-bug-report

### Describe the Bug

When I insert an image into my richtext field within a Block, the Payload admin crashes. After refreshing, it fails to load the collection.

The Payload application displays the following stacktrace:
```
TypeError: Cannot read properties of undefined (reading 'payload')
    at forEach (/~/my-payload-project/node_modules/@payloadcms/richtext-slate/src/data/richTextRelationshipPromise.ts:38:32)
```

It appears that this issue was introduced in version 2.0.12, as it doesn't occur in version 2.0.11. My suspicion is that it may be related to issue #3780.

### To Reproduce

Use the provided reproduction repository, create a new post with a block and upload an image to the richtext field.

### Payload Version

2.0.14

### Adapters and Plugins

richtext-slate

**Comment by AlessioGr** [comment] 2023-11-15 22:01
Hey @DennisSnijder, I was indeed able to reproduce this using your reproduction.

However, once I updated all the payload-related dependencies in your reproduction, the issue no longer appears. Looks like this got fixed in a newer version!

I'll close this for now, but please let me know if you're still able to reproduce it when using the latest versions, then I'll re-open this

**Closed by AlessioGr** 2023-11-15 22:01 UTC
Labels: reproduced, plugin: richtext-slate

**Comment by DennisSnijder** [comment] 2023-11-16 10:35
Hey! @AlessioGr thank you for checking this out!
After upgrading the `@payloadcms/richtext-slate` to 1.1.0 the issue was resolved!

Thank you once again!
