### ISSUE TITLE
docs(beta): dead links to fields#the-field-prop

### ISSUE THREAD

**Issue by Because789** [payloadcms/payload#8685] opened 2024-10-14 14:00 UTC
# Documentation Issue

There are several links to /docs/beta/admin/fields#the-field-prop, a destination that doesn't exist:

- docs/admin/components.mdx (line 435)
- docs/admin/fields.mdx (lines 139, 140, 279, 280. 320, 321, 366, 367, 483, 484)

Edit: the destination does exist, the issue are the backticks. See https://github.com/payloadcms/payload/issues/8685#issuecomment-2411365674.

**Comment by tyteen4a03** [comment] 2024-10-14 14:03
Likely a duplicate of https://github.com/payloadcms/payload/issues/8666

**Comment by Because789** [comment] 2024-10-14 14:19
> Likely a duplicate of [#8666](https://github.com/payloadcms/payload/issues/8666)

You are right, thanks to that input I found the "missing" paragraph, thanks!

**Closed** 2024-10-14 17:12 UTC
Labels: documentation
