### ISSUE TITLE
Value of the file field is undefined inside arguments of the admin.condition function

### ISSUE THREAD

**Issue by svntime** [payloadcms/payload#1737] opened 2022-12-21 12:07 UTC
# Bug Report

I found two unrelated problems with my upload collection (first one should be easy to fix so I'm not creating a separate bug report):
- the same file that was just cleared cannot be reselected
- the value of the file field is `undefined` inside arguments of the `admin.condition` function 

I'm trying to conditionally render the `alt` field if file mimeType starts with 'image'. Here is my config:

```
import path from 'path';
import { buildConfig } from 'payload/config';

export default buildConfig({
  collections: [
    {
      slug: 'media',
      admin: {
        useAsTitle: 'filename',
        group: 'Assets'
      },
      upload: {
        staticDir: path.resolve(__dirname, '../../media'),
        mimeTypes: ['image/*', 'application/pdf']
      },
      fields: [
        {
          name: 'alt',
          type: 'text',
          admin: {
            condition: (data, siblingData) => {
              console.log(data);
              console.log(siblingData);
              console.log('\n');

              const mimeType = data.file?.type || data.mimeType;

              return mimeType?.startsWith('image');
            }
          }
        }
      ]
    }
  ]
});
```

Condition function works as expected when creating a new media item. The problem occurs in the edit view of media item (alt text field is hidden):

![image](https://user-images.githubusercontent.com/42152930/208900933-360fd6c0-6fb0-464e-9a5e-a6903267a8af.png)

![image](https://user-images.githubusercontent.com/42152930/208900972-e6501205-e32a-497b-8eeb-6c965926cb71.png)

## Steps to Reproduce Issue 1

1. Select any file in your file field
2. Press clear button
3. Try to reselect the same file

## Steps to Reproduce Issue 2

1. Use provided buildConfig
2. Upload any image and go to its edit view
3. Check console for `data` logs from `admin.condition` function

## Other Details
Tested with build and dev, behaviour is the same.

Browser: Chrome 108.0.5359.124
Payload version: 1.3.4

I didn't dig into the second problem but I think that setting the `<input type="file" />` value to `null` on each `onClick` event should fix the first one.

**Comment by jacobsfletch** [comment] 2022-12-21 23:04
Hey @svntime I've got issue 1 here fixed with #1745! Looking into the issue 2 next. Thank you for the report!

**Comment by jmikrut** [comment] 2023-01-09 14:18
Hey @svntime — so I have some answers for you on #2. This is actually functioning by design. The only time the `file` will be present in conditional logic is when you are actively uploading a file. That form state is actually representative of a literal file upload, and when you update a document, the file is not re-uploaded and is thus missing intentionally. 

Further, the file data like `mimeType`, `filesize`, `width`, `height`, etc. are populated only on the server after the file has been uploaded. So those fields' data will only be present after the file has been uploaded. 

You've started down the path of using `file` if it is present, and then falling back to `data.mimeType`, which is probably what I'd do if I were you. Does this not work?

Otherwise, there's not much we can do about this on our side I'm afraid. 

What do you think?

**Comment by svntime** [comment] 2023-01-09 15:23
Hi @jmikrut, thanks for coming back with response. 

> You've started down the path of using file if it is present, and then falling back to data.mimeType, which is probably what I'd do if I were you. Does this not work?

The problem is that the `data` changes between rerenders and `mimeType` becomes undefined. As a result, the alt field disappears.

Here you can see the console output after refreshing page with the document that already contains a file (uploaded long time ago). The `data.mimeType` is available only on initial renders:

![image](https://user-images.githubusercontent.com/42152930/211339523-c69c5ded-a08f-44cc-9393-fb3f2565e525.png)

**Comment by jmikrut** [comment] 2023-01-09 15:36
Ahhhh I see.

This should be a quick and easy one to fix 👍 

Give us a minute here!

**Comment by jmikrut** [comment] 2023-01-09 16:15
Fixed and will be released shortly. Thanks for clearing that up for me!

**Closed** 2023-01-09 16:14 UTC
Labels: possible-bug

**Comment by svntime** [comment] 2023-01-09 16:17
Wow, that was quick :smile: Thank you too!
