### ISSUE TITLE
Meta title not working on Payload V3

### ISSUE THREAD

**Issue by mcornielje090404** [payloadcms/payload#6991] opened 2024-07-01 09:52 UTC
### Payload Version

3.0.0-beta.55

### Node Version

20.13.1

### Next.js Version

15.0.0-canary.37

### Describe the Bug

I am attempting to change the title meta on the admin panel in Payload V3 and have noticed that the title suffix is not applied in the tab.

I have also seen that adding a hardcoded title in the admin meta object throws the following error in the console on hitting the admin page.

[10:47:10] ERROR: There were 1 errors validating your Payload config
[10:47:10] ERROR: 1: "admin.meta.title" is not allowed

### Reproduction Steps

- Add "admin.meta.title"
- The error will appear in the console

- Add "admin.meta.titleSuffix"
- The title will not change to add the suffix, nor will the automatic payload titles work.

**Comment by paulpopus** [comment] 2024-07-05 22:29
I just tested those config options on the latest beta and I'm unable to reproduce. Can you test on the latest and provide a reproduction repro so we can see the exact erroring config please? Will close the issue until theres repro

**Closed by paulpopus** 2024-07-05 22:29 UTC
Labels: status: needs-triage, v3
