### ISSUE TITLE
db-postgres: relationship field filterOptions returning unexpected results

### ISSUE THREAD

**Issue by JPrisk** [payloadcms/payload#5248] opened 2024-03-06 02:48 UTC
### Link to reproduction

https://github.com/JPrisk/payload-minimal-reproduction/compare/90c03c8652bba7a3f555517cd0d6eebee2b73ca5...HEAD

### Issue

When using the relationship field with the Postgres adapter, `filterOptions` is returning unexpected results.

When the field is empty the `filterOptions` works as expected, but when the dropdown has a value selected it acts differently (sometimes requires a page refresh to bust cache).

It seems as though when the `not_in` clause gets appended, the `filterOption` clauses aren't being merged correctly.

| ❌ filterOptions not working | ✔️ filterOptions working (unpopulated field) |
| - | - |
| ![Screenshot 2024-03-06 at 3 30 54 PM](https://github.com/payloadcms/payload/assets/22569730/9d7f171d-0bbe-4329-b5c8-3deb5f190a22) |  ![Screenshot 2024-03-06 at 3 29 23 PM](https://github.com/payloadcms/payload/assets/22569730/546aa90f-7d5a-4251-931f-a3799a82f7ad) | 
|  ![Screenshot 2024-03-06 at 3 36 43 PM](https://github.com/payloadcms/payload/assets/22569730/d00bfc26-bb96-4b3f-8028-4c098f80e9ce) | ![Screenshot 2024-03-06 at 3 46 51 PM](https://github.com/payloadcms/payload/assets/22569730/036e3887-c1c9-462b-8266-4763aca9b378) |

### To Reproduce

**Prerequisites:** run Payload locally, seed db

1. Log in to the dashboard `demo@demo.com` / `password`
2. Navigate to 'Pages / Example page'
3. Focus on the 'Featured News' dropdown
4. 👀 Look at the results

![image](https://github.com/payloadcms/payload/assets/22569730/8c7b72ff-c779-4ddf-bd74-ab38345c678a)

### Payload Version

2.11.2

### Adapters and Plugins

`db-postgres`

**Comment by Janisvb** [comment] 2024-03-06 07:50
I think, this could be the same issue as https://github.com/payloadcms/payload/issues/5151

**Comment by PatrikKozak** [comment] 2024-04-18 15:10
Hey @JPrisk - thanks for adding a reproduction, this helps a lot in the debugging process.

After using your steps to try and reproduce, I was unable to reproduce the behavior. The `Featured News` relationship filter dropdown is showing me the correct results.

Can you give this another shot on latest to confirm? Thank you!

**Comment by PatrikKozak** [comment] 2024-04-23 13:27
@JPrisk Going to close this for now, if you can still reproduce this in the near future, we can open this issue back up and I'll take a look into this!

**Closed by PatrikKozak** 2024-04-23 13:27 UTC
Labels: [possible-bug]

**Comment by JPrisk** [comment] 2024-04-25 22:13
Hey @PatrikKozak  - i've been out of action 🤒 hence the delay getting back to you.

Just tried updating to the latest version of `payload` + `@payloadcms/db-postgres` in the project where I encountered it and the problem still persists.

One important thing to note:
When testing, the issue arises once a value is selected and the user is making additional selections.
