### ISSUE TITLE
Client file imports when not using payload.config.ts

### ISSUE THREAD

**Issue by lenovouser** [payloadcms/payload#7437] opened 2024-07-30 15:35 UTC
I can't figure out how to use or emulate what was created in #5701 for a standalone instance where I pass the config directly. For example this here will fail:

```js
import { mongooseAdapter } from "@payloadcms/db-mongodb";
import { lexicalEditor } from "@payloadcms/richtext-lexical";

import {
  BasePayload as Payload,
  buildConfig,
} from "payload";

const config = {
  secret: "testing",
  db: mongooseAdapter({
    url: "mongodb://localhost:27017/testing",
  }),
  editor: lexicalEditor(),
};

const payload = new Payload();

await payload.init({
  config: buildConfig(config),
});
```

Since `importWithoutClientFiles` takes a path it does not work for this, but it also seems to set no option that I could just set myself or anything? Only registering the loader, which does TS transpiration as far as I can see, or would somehow directly importing that loader also fix the issues I am getting with Payload trying to import CSS files?

```
node:internal/modules/esm/get_format:176
  throw new ERR_UNKNOWN_FILE_EXTENSION(ext, filepath);
        ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for /Users/silas/Workspace/temporary/payload-test/node_modules/.pnpm/react-image-crop@10.1.8_react@19.0.0-rc-fb9a90fa48-20240614/node_modules/react-image-crop/dist/ReactCrop.css
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:176:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:219:36)
    at defaultLoad (node:internal/modules/esm/load:133:22)
    at async ModuleLoader.load (node:internal/modules/esm/loader:570:7)
    at async ModuleLoader.moduleProvider (node:internal/modules/esm/loader:445:45) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Node.js v22.4.1
```

I am trying this with the Payload 3 Beta.

It seems like it also ignores the client files, which would fix my issue, now I only have to figure out how to apply that to the payload import itself I suppose? https://github.com/payloadcms/payload/blob/a7b0f8ba3636e5d16e27e35993066daf9d2429be/packages/payload/src/bin/loader/index.ts#L58

**Comment by jmikrut** [comment] 2024-07-30 18:32
Hey @lenovouser — so the problem is actually the Lexical editor, which when imported, comes with CSS. At least right now. We have a monster PR that will make this significantly easier (https://github.com/payloadcms/payload/pull/7246). No loader should be necessary after this is done.

But, in the meantime, you could import the Lexical editor using `import { importWithoutClientFiles } from 'payload/node'`.

Will you give that a shot? Alternatively, you might consider importing your whole script with the `importWithoutClientFiles` function

**Comment by ainsleyclark** [comment] 2024-07-30 18:55
Hey @jmikrut 

I don't think think the `Unknown file extension ".css"` issue is related to Lexical unfortunately. Since `> .67` I can't get Payload to work outside of Next.js as indicated by the [docs](https://payloadcms.com/docs/beta/local-api/outside-nextjs)

It's strange that `importWithoutClientFiles` is still trying to import css files here:

```typescript
// We are importing `getPayload` because we don't need HMR
// for a standalone script. For usage of Payload inside Next.js,
// you should always use `import { getPayloadHMR } from '@payloadcms/next/utilities'` instead.
import {getPayload, type SanitizedConfig} from 'payload';

// This is a helper function that will make sure we can safely load the Payload Config
// and all of its client-side files, such as CSS, SCSS, etc.
import { importWithoutClientFiles } from 'payload/node';

import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';

// In ESM, you can create the "dirname" variable
// like this. We'll use this with `dotenv` to load our `.env` file, if necessary.
const filename = fileURLToPath(import.meta.url);
const dirname = path.dirname(filename);

// If you don't need to load your .env file,
// then you can skip this part!
dotenv.config({
	path: path.resolve(dirname, '../.env'),
});

const seed = async () => {
	const config = await importWithoutClientFiles<SanitizedConfig>(path.resolve(dirname, '../payload.config.ts'));
	const payload = await getPayload({ config });
	// const req = { payload } as PayloadRequest;
};

seed()
	.then(() => process.exit(0))
	.catch((e) => {
		console.error(e);
		process.exit(1);
	});
```

Error:

```
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for /Users/Ainsley/Desktop/ainsley.dev/WebKit/web-kit/node_modules/.pnpm/react-image-crop@10.1.8_react@18.3.1/node_modules/react-image-crop/dist/ReactCrop.css
```

**Comment by jmikrut** [comment] 2024-08-08 21:18
Hey @ainsleyclark in your example it'd be because you are importing Lexical directly above the code that you provided. Lexical currently comes with CSS imports, but with an upcoming PR, it will not. It's related to this discussion:

https://github.com/payloadcms/payload/discussions/6938

I will close this issue because it's about to be fixed by the PR we are making in correspondence with #6938 - keep an eye out!

**Closed by jmikrut** 2024-08-08 21:18 UTC

**Comment by ainsleyclark** [comment] 2024-08-09 06:40
Hey @jmikrut thanks for the update. Is there a PR/Branch to track? Thank you.
