### ISSUE TITLE
Redirects issue

### ISSUE THREAD

**Issue by Hemraj-tequity** [payloadcms/payload#8475] opened 2024-09-30 07:57 UTC
# Documentation Issue

## Additional Details

I am using website template of payload version 3 but that are already have implemented redirect plugin collection but it is not working

**Comment by r1tsuu** [comment] 2024-10-18 00:30
"Not working" is not clear, what's your issue with it. @paulpopus it should work?

**Comment by paulpopus** [comment] 2024-10-18 01:31
Hey I just tested this on the latest version of the template and it seems to work fine for me. I assume it might've been fixed since so I'll close this issue for now but happy to take a deeper look if there's a reproduction

**Closed by paulpopus** 2024-10-18 01:31 UTC
Labels: documentation
