### ISSUE TITLE
Add upload elements to a rich text field makes page unresponsive

### ISSUE THREAD

**Issue by Reilley64** [payloadcms/payload#1070] opened 2022-09-06 11:34 UTC
# Bug Report

Adding a upload element from a Media collection makes all intractable elements on the page unresponsive.

## Expected Behavior

Page should be still intractable when adding a upload element to the rich text field, so that you can save or continue editing the item in the collection.

## Current Behavior

Adding a upload element from a Media collection makes all intractable elements on the page unresponsive.

## Possible Solution

🤷

## Steps to Reproduce

1. Create an upload collection
2. Create a collection with a rich text field
3. Upload an image to the upload collection
4. Try to insert image into the rich text field to the other collection

## Detailed Description

Payload version: 1.0.32
Browser: Firefox

![Screenshot 2022-09-06 at 21-34-13 Editing - Research - Payload](https://user-images.githubusercontent.com/28533679/188625649-7173613c-f973-4d01-8537-ecd750d128f7.png)

**Comment by DanRibbens** [comment] 2022-09-06 19:59
Hey @Reilley64,
I'm not able to reproduce your issue on my end. Can you share your config on both the collection and the upload that is linked? Also if you're able to do a screen recording, that could be invaluable too!

I tried swapping images, uploading new ones, add and removing images to the rich text, it seems to be fine. It is working as intended and I don't see any errors in the console to go off of. 🤷

Thanks!

**Comment by JeffreyArt1** [comment] 2022-09-06 21:26
Same here, page becomes unresponsive and no console or terminal errors are shown.

**Comment by DanRibbens** [comment] 2022-09-06 21:30
Can anyone get a screen recording so we can assess the problem better?

**Comment by Reilley64** [comment] 2022-09-06 22:06
Here's a screen recording of the issue:

https://user-images.githubusercontent.com/28533679/188748706-621d13f8-34d0-4784-a7d0-faaac50de163.mov

**Comment by denolfe** [comment] 2022-09-06 22:41
We were able to recreate this issue. It looks like the nextjs-custom-website repo had a conflicting version of slate installed. This has been reverted. The repo has been updated, or you can make the same change as [this commit](https://github.com/payloadcms/nextjs-custom-server/commit/7697c07b54758d2452dfba65cc10f8dd1462e1f3)

**Comment by Reilley64** [comment] 2022-09-06 22:48
Hey I'm not using the [nextjs-custom-server](https://github.com/payloadcms/nextjs-custom-server) repo. I'm having this issue from the base template after running yarn create payload-app.

**Comment by Reilley64** [comment] 2022-09-06 23:03
I've made a [repo](https://github.com/Reilley64/payload-bug.git) that should help you reproduce the issue.

**Comment by jmikrut** [comment] 2022-09-07 16:43
Hey all - this is fixed in `1.0.34`!

Thank you everyone!

**Closed by jmikrut** 2022-09-07 16:43 UTC
Labels: bug
