### ISSUE TITLE
Email Validation Bug

### ISSUE THREAD

**Issue by VISHNU-P-M** [payloadcms/payload#4666] opened 2024-01-03 10:36 UTC
### Describe the Bug

Email field not validating while auth collection update

### To Reproduce

* Created a new collection "customer" with auth true option
* Customer creation existing email validation check successfully return error
* Customer updation existing email validation check failed, now I've two customer with same email

### Payload Version

2.0.0

**Comment by PatrikKozak** [comment] 2024-01-03 15:47
Hey @VISHNU-P-M,

Here are the results of my own reproduction:

on customer `creation`, email validation successfully returns an error as shown below:

![Screen Shot 2024-01-03 at 10 23 23 AM](https://github.com/payloadcms/payload/assets/35232443/225bb3e4-ca30-4c81-9158-a9eecc475447)

on customer `update`, email validation successfully returns an error as well:

![Screen Shot 2024-01-03 at 10 27 44 AM](https://github.com/payloadcms/payload/assets/35232443/7317569c-c28b-4e1d-89b9-dc2056a268bc)

Is the `update` not returning an error for you? If so, could you please create and link to a reproducible repo?

**Comment by VISHNU-P-M** [comment] 2024-01-03 16:10
I was trying through Rest-API endpoints,
here is my collection
```

import { CollectionConfig } from "payload/types";

const Customers: CollectionConfig = {
  slug: "customers",
  auth: true,
  admin: {
    useAsTitle: "email",
  },
  fields: [
    {
      name: "first_name",
      type: "text",
      required: true,
      saveToJWT: true,
    },
    {
      name: "last_name",
      type: "text",
      required: true,
      saveToJWT: true,
    },
    {
      name: "role",
      type: "select",
      required: true,
      options: ["admin", "procurement_team", "vendor"],
    },
  ],
};

export default Customers;

```

**Comment by PatrikKozak** [comment] 2024-01-04 18:36
@VISHNU-P-M 

Thanks for taking the time with this. I went ahead and tried to reproduce this with REST API endpoints by sending a `post` request to a `users` collection and was not able to reproduce.

Here are some screenshots of what I did:

![Screen Shot 2024-01-04 at 1 31 09 PM](https://github.com/payloadcms/payload/assets/35232443/7ed555a9-2529-4740-b775-c010e9e81cde)

Above is an initial creation of a new user with the email - `test@gmail.com`

![Screen Shot 2024-01-04 at 1 31 18 PM](https://github.com/payloadcms/payload/assets/35232443/a1f5ac87-4b6b-4842-99b1-2d25faad1862)

Upon trying to create another user with the same email, I received the above expected validation error.

Going to close this issue for now as not reproducible. If you can create a reproducible repo with an example of email validation not working as expected, I will reopen the issue and pull down your repo.

**Closed by PatrikKozak** 2024-01-04 18:36 UTC
Labels: possible-bug, cant-reproduce

**Comment by DanRibbens** [comment] 2024-01-04 18:41
Can you verify that Payload added an index with `unique: true` in the database for your users email @VISHNU-P-M? That could just be the issue. I'm not sure why index creation failed for you, but as Pat showed, this is the only way you wouldn't get this error.
