### ISSUE TITLE
relationship search with wrong params

### ISSUE THREAD

**Issue by zhounewz** [payloadcms/payload#2884] opened 2023-06-22 02:41 UTC
### Link to reproduction

https://payloadcms.com/

### To Reproduce

Very simple bug, please see the description below

### Describe the Bug

When searching for keywords in the relationship, no results can be found.
Because I think it is caused by the "page" field in the request parameter.

The page parameter should not be passed here.

<img width="1415" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/31983feb-4d4a-44ac-8136-240be5e626c0">

<img width="1038" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/39c98ce4-e721-42c9-9a41-25e83671e17c">

### Payload Version

1.9.5

**Comment by DanRibbens** [comment] 2023-06-22 11:20
Hi @zhounewz,

I believe this is a duplicate of https://github.com/payloadcms/payload/issues/2859
This was fixed in v1.10.0. Feel free to reopen if you update and still see a problem.

Thanks!

**Closed by DanRibbens** 2023-06-22 11:20 UTC
Labels: possible-bug
