### ISSUE TITLE
Cannot edit image uploads. Save button does not appear, cropping and focal point are not saved.

### ISSUE THREAD

**Issue by stefvw93** [payloadcms/payload#8650] opened 2024-10-11 08:35 UTC
### Link to reproduction

_Sorry, do not have the time at the moment._

### Describe the Bug

We are unable to edit image uploads after they are created. It seems like it is possible to do changes, but there is no way to save the changes as the save button does not appear.

There are no error logs or failed requests in either the client app or the server app.

We are using Payload ^2.30.1, and @payloadcms/plugin-cloud-storage ^1.20 -- but removing the cloud storage plugin does not seem to change/affect the issue at all.

See attached video.

https://github.com/user-attachments/assets/5c8687ac-c821-4817-8836-b6c1b514f40e

Checked several closed issues that seem to be about the same problems, but could not find a solution.
- https://github.com/payloadcms/payload/issues/4422
- https://github.com/payloadcms/payload/issues/5000

### To Reproduce

1. Create an uploads collection
2. Create an image upload
3. Edit the uploaded image -- e.g. change cropping or focal point
4. Click "Save changes" in the image edit view
5. Changes do not seem to be applied in the doc edit view, but when leaving this view the app actually does show the unsaved changes warning, but there is no way to save here.

### Payload Version

2.30.1

### Adapters and Plugins

@payloadcms/plugin-cloud-storage@1.2.0

**Comment by abernh** [comment] 2024-11-07 09:59
Note:
I saw "this" too happening in `v2`, unsure if it was always the Media collection. 

With "this" I mean that the action buttons were missing on the collection edit view. They seems to be rendered in a separate step and this is sometimes triggered late (takes a few seconds until they appear) or not at all. 

But it happens so seldom that it wasn't bothering anyone yet too much.

Reloading the page normally fixes this issue.

**Comment by PatrikKozak** [comment] 2024-11-07 16:20
Hey @stefvw93 and @abernh - been trying to reproduce this behavior and unable to on latest `v2` (`v2.30.3`).

I'd like to get to the bottom of this however. Can either of you send me your uploads config so I can test with your specific configurations - thank you!

**Comment by PatrikKozak** [comment] 2024-11-21 21:02
@stefvw93 @abernh Going to close this issue for now - if either of you could send me a reproduction repo where I can see the above behavior, I'll be happy to re-open the issue and take another look.

**Closed by PatrikKozak** 2024-11-21 21:02 UTC
Labels: status: cant-reproduce, v2
