### ISSUE TITLE
Duplicate collection document breaks with beforeValidate hook in slug field

### ISSUE THREAD

**Issue by creative-andrew** [payloadcms/payload#3288] opened 2023-09-07 09:12 UTC
### To Reproduce

I have the following collection:

```ts
export const Pages: CollectionConfig = {
  slug: "pages",
  admin: {
    useAsTitle: "title",
    preview: doc => formatPreviewURL("pages", doc),
    defaultColumns: ["title", "slug", "createdAt", "updatedAt"],
  },
  versions: {
    drafts: true,
  },
  access: {
    create: isAdmin,
    read: publishedOnly,
    readVersions: isAdmin,
    update: isAdmin,
    delete: isAdmin,
  },
  fields: [
    {
      name: "title",
      type: "text",
      required: true,
      localized: true,
    },
    slugField("title", { localized: true }),
  ],
};
```

My slug field looks like:

```ts
export const slugField: Slug = (fieldToUse = "title", overrides = {}) =>
  deepMerge<Field, Partial<Field>>(
    {
      name: "slug",
      unique: true,
      label: "Slug",
      type: "text",
      index: true,
      admin: {
        position: "sidebar",
      },
      hooks: {
        beforeValidate: [formatSlug(fieldToUse)],
      },
    },
    overrides,
  );
```

And my `formatSlug` function:

```ts
import slugify from "slugify";

const format = (val: string): string =>
  slugify(val, {
    lower: true,
    strict: true,
  });

const formatSlug =
  (fallback: string): FieldHook =>
  ({ operation, value, originalDoc, data }) => {
    if (typeof value === "string") {
      return format(value);
    }

    const fallbackData = data?.[fallback] || originalDoc?.[fallback];

    if (fallbackData && typeof fallbackData === "string") {
      return format(fallbackData);
    }

    return value;
  };

export default formatSlug;
```

When clicking on duplicate I get the following error:

```
 webpack compiled successfully
2023-09-07 10:58:43 backend-payload-1  | [08:58:43] ERROR (payload): ValidationError: The following field is invalid: slug.de_DE
2023-09-07 10:58:43 backend-payload-1  |     at create (/home/node/app/backend/node_modules/payload/src/collections/operations/create.ts:218:11)
2023-09-07 10:58:43 backend-payload-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-07 10:58:43 backend-payload-1  |     at async createHandler (/home/node/app/backend/node_modules/payload/src/collections/requestHandlers/create.ts:19:17)
2023-09-07 10:58:43 backend-payload-1  | [08:58:43] ERROR (payload): NotFound: The requested resource was not found.
2023-09-07 10:58:43 backend-payload-1  |     at findByID (/home/node/app/backend/node_modules/payload/src/collections/operations/findByID.ts:104:13)
2023-09-07 10:58:43 backend-payload-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-07 10:58:43 backend-payload-1  |     at async findByIDHandler (/home/node/app/backend/node_modules/payload/src/collections/requestHandlers/findByID.ts:13:17)
2023-09-07 10:58:43 backend-payload-1  | [08:58:43] ERROR (payload): TypeError: Cannot read properties of null (reading '_id')
2023-09-07 10:58:43 backend-payload-1  |     at getLatestCollectionVersion (/home/node/app/backend/node_modules/payload/src/versions/getLatestCollectionVersion.ts:36:18)
2023-09-07 10:58:43 backend-payload-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-07 10:58:43 backend-payload-1  |     at async updateByID (/home/node/app/backend/node_modules/payload/src/collections/operations/updateByID.ts:112:15)
2023-09-07 10:58:43 backend-payload-1  |     at async updateByIDHandler (/home/node/app/backend/node_modules/payload/src/collections/requestHandlers/updateByID.ts:23:17)
2023-09-07 10:58:43 backend-payload-1  | [08:58:43] ERROR (payload): TypeError: Cannot read properties of null (reading '_id')
2023-09-07 10:58:43 backend-payload-1  |     at getLatestCollectionVersion (/home/node/app/backend/node_modules/payload/src/versions/getLatestCollectionVersion.ts:36:18)
2023-09-07 10:58:43 backend-payload-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-07 10:58:43 backend-payload-1  |     at async updateByID (/home/node/app/backend/node_modules/payload/src/collections/operations/updateByID.ts:112:15)
2023-09-07 10:58:43 backend-payload-1  |     at async updateByIDHandler (/home/node/app/backend/node_modules/payload/src/collections/requestHandlers/updateByID.ts:23:17)
2023-09-07 10:58:43 backend-payload-1  | [08:58:43] ERROR (payload): TypeError: Cannot read properties of null (reading '_id')
2023-09-07 10:58:43 backend-payload-1  |     at getLatestCollectionVersion (/home/node/app/backend/node_modules/payload/src/versions/getLatestCollectionVersion.ts:36:18)
2023-09-07 10:58:43 backend-payload-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-07 10:58:43 backend-payload-1  |     at async updateByID (/home/node/app/backend/node_modules/payload/src/collections/operations/updateByID.ts:112:15)
```
![Recording #74](https://github.com/payloadcms/payload/assets/18492002/36a22c87-ee6e-49b6-9625-1d1b6566ede2)

### Describe the Bug

Duplicating pages collection documents break with slug field while using `beforeValidate` and `localized`
 
### Payload Version

1.9.0

**Comment by JessChowdhury** [comment] 2023-09-11 09:17
Hi @creative-andrew - the cause of this error is that you are trying to duplicate a document containing a **unique** field. The `unique: true` property on the `slug` field enforces that each entry in the Collection has a unique value for this field.

What you will want to do is add a custom function to modify the `slug` field value before duplication occurs. Using the `beforeDuplicate` collection hook, you can take the data, modify it, and return it before the duplicated document is created. 

Simply appending the `slug` value with `_1` or similar should do the trick. Here is an example of how to do this from one of our test suites: https://github.com/payloadcms/payload/blob/master/test/fields/collections/Indexed/index.ts

Let me know if you need any more help here.

**Comment by JarrodMFlesch** [comment] 2023-09-11 12:45
I think this [resolved issue](https://github.com/payloadcms/payload/issues/1243) has a lot of good information on this topic as well. I am going to close this for now, we can still discuss in this thread if you need assistance!

**Closed by JarrodMFlesch** 2023-09-11 12:45 UTC

**Comment by creative-andrew** [comment] 2023-09-12 14:37
One additional thing, 
Is there a way to provide a better validation message for unique fields?


<img width="688" alt="image" src="https://github.com/payloadcms/payload/assets/18492002/495ce785-5784-41ec-b236-1746810d283d">

**Comment by thompsonsj** [comment] 2024-01-04 18:39
Might be overkill but the following works really well for me. In collection beforeChange hooks, I recursively try different slugs until I get one that is unique.

```ts
import payload from "payload"
import { uniqueSlug } from "../../utils"

export const getUniqueSlug = async ({
  originalSlug,
  collection,
  locale,
  id
}: {
  originalSlug: string,
  collection: "content-hub-articles" | "events" | "landing-pages"
  locale: string
  id: string
}) => {
  // unique slug
  let returnSlug = ``
  let slugs = []
  const tryUniqueSlug = async (resolve, reject, slug: string) => {
    slugs.push(slug)

    const exists = await slugExists({
      collection,
      slug,
      locale,
      id,
    });
  
    if (exists) {
      tryUniqueSlug(resolve, reject, uniqueSlug(slug, slugs));
    } else {
      return resolve(slug);
    }
  }

  const runScript = async () => {
    await new Promise((r, j) => tryUniqueSlug(r, j, originalSlug)).then(slug => returnSlug = `${slug}`);
  };

  await runScript();
  return returnSlug
}

const slugExists = async ({
  collection,
  slug,
  locale,
  id
}: {
  collection: "content-hub-articles" | "events" | "landing-pages",
  slug: string,
  locale: string,
  id?: string
}) => {
  const query = {
    slug: {
      equals: slug,
    },
    ...(id && {
      id: {
        not_equals: id
      }
    })
  }
  const docsWithThisSlug = 
    await payload.find({
      collection,
      where: query,
      locale,
    })
  return docsWithThisSlug.totalDocs !== 0
}
```

The `uniqueSlug` function used above is as follows:

```ts
import makeSlug from 'slugify';

export const slugify = (str: string): string | undefined => {
  if (!str) {
    return undefined;
  } else {
    return makeSlug(str, { lower: true, strict: true });
  }
};

const isNonEmptyArray = (el: any): boolean => {
  return Array.isArray(el) && el.length > 0
}

export const uniqueSlug = (str: string, haystack: string[]): string => {
  let slug = slugify(str)
  if (!slug) {
    slug = 'index'
  }
  // rename slug if it exists.
  if (isNonEmptyArray(haystack)) {
    let i = 1
    while (haystack.includes(slug)) {
      i++
      if (slug.match(/-\d+$/)) {
        slug = slug.replace(/-\d+$/, `-${i}`)
      } else {
        slug += `-${i}`
      }
    }
  }
  return slug
}
```
And finally, the way it is used in a [collection beforeChange hook](https://payloadcms.com/docs/hooks/collections#beforechange):

```ts
data.slug = await getUniqueSlug({
    originalSlug: data.slug,
    collection: "events",
    locale: req.locale,
    id: operation === 'update' && originalDoc.id
})
```

If there's interest I might try wrapping this up in a plugin, or making a pull request on https://github.com/NouanceLabs/payload-better-fields-plugin?tab=readme-ov-file#slug-field.

**Comment by DanRibbens** [comment] 2024-01-04 18:44
> One additional thing, Is there a way to provide a better validation message for unique fields?

I think this is a bug when you have any field that is both unique and localized. The admin UI fails to highlight he field and the error  toast is not as nice.
