### ISSUE TITLE
Nested-docs Plugin Issue with Postgres: ValidationError on 2nd Save

### ISSUE THREAD

**Issue by Livog** [payloadcms/payload#3728] opened 2023-10-18 07:57 UTC
### Link to reproduction

*

### To Reproduce

1. Use the postgres db adapter (latest version).
2. Use the `nested-docs` plugin version 1.0.8.
3. Add the following nested docs configuration in `payload.config.ts`:
```typescript
nestedDocs({
  collections: [Pages.slug],
  generateLabel: (_, doc) => doc.title as string,
  generateURL: (docs, lastDoc) => {
    return docs.reduce((url, doc) => `${url}/${doc.slug ?? ''}`,'')
  }
}),
```
4. Add the pages collection to the payload config.
5. Save once - no error should occur.
6. Save a second time.
7. Observe the error `ValidationError: The following field is invalid: breadcrumbs.0.doc` — specifically for the last breadcrumb.

### Describe the Bug

When using the `nested-docs` plugin version 1.0.8 with the latest version of the postgres db adapter and configuring the `nestedDocs` in `payload.config.ts`, an error arises on the second save attempt: `ValidationError: The following field is invalid: breadcrumbs.0.doc`. This issue seems linked to the `nested-docs` `populateBreadcrumbs` function where the current document is appended to the breadcrumbs array. This code snippet appears to be the culprit:

```javascript
const currentDocBreadcrumb = {
    ...originalDoc,
    ...data,
}

if (originalDoc?.id) {
  currentDocBreadcrumb.id = originalDoc?.id
}

breadcrumbDocs.push(currentDocBreadcrumb)
```

In the context of Postgres, the `originalDoc.id` should be an int, but is a string in this case, which is leading to the error.

### Payload Version

2.0.10

### Adapters and Plugins

db-postgres, nested-docs

**Comment by Livog** [comment] 2023-10-18 07:58
A temporary solution:

1. Create a new file at `/src/hooks/fixBreadcrumbsForPostgres.ts` and add the following code:
```typescript
import type { BeforeChangeHook } from 'payload/dist/collections/config/types'

const fixBreadcrumbForPostgres: BeforeChangeHook = ({ data }) => {
  if (data.breadcrumbs) {
    data.breadcrumbs = data.breadcrumbs.map((breadcrumb: any) => {
      const newBreadcrumb = {
        ...breadcrumb,
        doc: breadcrumb?.doc ? parseInt(breadcrumb.doc) : undefined
      }
      return newBreadcrumb
    })
  }
  return data
}

export default fixBreadcrumbForPostgres
```

2. Inside the collections that use `nested-docs`, modify the hooks:
```javascript
hooks: {
  beforeChange: [
    fixBreadcrumbForPostgres // This is temporary until nested-docs fixes Postgres support.
  ]
},
```

**Comment by DanRibbens** [comment] 2023-12-27 18:33
I think this was fixed with this change to how arrays are saved https://github.com/payloadcms/payload/pull/4302 or possibly another fix from an earlier version.

I can't reproduce the problem. on latest.

**Comment by DanRibbens** [comment] 2023-12-27 18:34
Please tag me with updated reproduction steps if this is still a problem and I will reopen the issue.

**Closed by DanRibbens** 2023-12-27 18:34 UTC
Labels: possible-bug

**Comment by joshdavenport** [comment] 2024-02-23 16:32
Currently getting this issue.

![Screenshot 2024-02-23 at 16 30 24](https://github.com/payloadcms/payload/assets/757828/11f7b081-a235-4ec3-bf67-f9ef56854237)

Nothing unusual in my config, I'm just adding nestedDocs like so:

```
    nestedDocs({
      collections: ['pages'],
      generateLabel: (_, doc) => doc.title as string,
      generateURL: (docs) =>
        docs.reduce((url, doc) => `${url}/${doc.slug}`, ''),
    }),
```

All I have to do to trigger the error is: create a page, save as draft, then hit publish.

**Comment by akhrarovsaid** [comment] 2024-03-06 16:11
@DanRibbens I'm also currently experiencing this issue. Same as above - the field fails validation and mentions the last breadcrumb.

Using payload@2.11.2, db-postgres@0.7.0, plugin-nested-docs@1.0.12
