### ISSUE TITLE
`filterOptions` doesn't respect `locale` on validation

### ISSUE THREAD

**Issue by ssyberg** [payloadcms/payload#4204] opened 2023-11-17 21:55 UTC
### Describe the Bug

`filterOptions` doesn't respect `locale` on validation, though it does appear to respect it on what is displayed on the drop down, on `filterOptions` based validation it  appears to use the default locale

### To Reproduce

**Collection 1**
```
const Sandbox = {
    slug: 'sandbox',
    fields: [
        {
            name: 'testCollectionRelationship',
            type: 'relationship',
            relationTo: 'testCollection',
            localized: true,
            filterOptions: () => {
                return { published: { equals: true } };
            },
        },
    ],
};

export default Sandbox;
```

**Collection 2**
```
const TestCollection = {
    slug: 'testCollection',
    admin: {
        useAsTitle: 'title',
        group: 'Admin',
    },
    fields: [
        {
            name: 'title',
            type: 'text',
            localized: true,
        },
        {
            name: 'published',
            type: 'checkbox',
            localized: true,
        },
    ],
};

export default TestCollection;
```

Enable localizations and set up at least 2. Add a `testCollection` and set both titles, but set `published` only on the _non-default locale._ Now in admin navigate to Sandbox and create a new record. You can verify that in the default locale the drop down is empty, but in the non-default locale, it shows your `testCollection` record (which it should). Select it and try to save and you will get an error that it's an invalid selection. Now, go back to `testCollection` and set to published in the default locale, go back to `sandbox` and you can now save in the other (non-default) locale.

### Payload Version

2.1.1

### Adapters and Plugins

db-mongodb

**Comment by AlessioGr** [comment] 2023-11-22 07:10
Hey @ssyberg unfortunately I'm not able to reproduce this. Here's a video of how I did it:

https://github.com/payloadcms/payload/assets/70709113/6171e5be-8b04-4f35-882c-30d4048ae281

Collection & Localization configs (used that in the _community test suite):

```ts
localization: {
    locales: ['en', 'de'],
    defaultLocale: 'en',
  },
collections: [
    PostsCollection,
    MediaCollection,
    {
      slug: 'sandbox',
      fields: [
        {
          name: 'testCollectionRelationship',
          type: 'relationship',
          relationTo: 'testCollection',
          localized: true,
          filterOptions: () => {
            return { published: { equals: true } }
          },
        },
      ],
    },
    {
      slug: 'testCollection',
      admin: {
        useAsTitle: 'title',
        group: 'Admin',
      },
      fields: [
        {
          name: 'title',
          type: 'text',
          localized: true,
        },
        {
          name: 'published',
          type: 'checkbox',
          localized: true,
        },
      ],
    },
  ],  
```

Is there anything I need to change to be able to reproduce this?

**Comment by AlessioGr** [comment] 2023-12-09 17:48
Closing this for now, as I can't reproduce it. Feel free to re-open the issue with a reproduction. Here's a [reproduction guide](https://github.com/payloadcms/payload/blob/main/.github/reproduction-guide.md) :)

**Closed by AlessioGr** 2023-12-09 17:48 UTC
Labels: cant-reproduce
