### ISSUE TITLE
Problems with postgres starters (Error: swc-minify-webpack-plugin tried to access @swc/core)

### ISSUE THREAD

**Issue by rburgst** [payloadcms/payload#4714] opened 2024-01-07 10:18 UTC
### Describe the Bug

After creating a blank project (postgres) I get the following error
```
Error: swc-minify-webpack-plugin tried to access @swc/core
```

### To Reproduce

1. create a blank project

```
npx create-payload-app@latest

  Welcome to Payload. Let's create a project!

✔ Project name? … sports-payload
✔ Choose project template › blank
✔ Select a database › PostgreSQL (beta)
✔ Enter PostgreSQL connection string … postgres://127.0.0.1:5432/sports-payload

  Creating project in /Users/rainer/git/private/turnen/sports-payload

✔ Dependencies installed
✔ .env file created
✔ Payload project successfully created

  ★ Launch Application:

    - cd ./sports-payload
    - yarn dev or follow directions in README.md: file:///Users/rainer/git/private/turnen/sports-payload/README.md

  ★ Documentation:

    - Getting Started: https://payloadcms.com/docs/getting-started/what-is-payload
    - Configuration: https://payloadcms.com/docs/configuration/overview
```
2. now run `yarn dev`
```
yarn dev
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node src/server.ts -- -I`

/Users/rainer/git/private/turnen/sports-payload/.pnp.cjs:24449
      Error.captureStackTrace(firstError);
            ^
Error: swc-minify-webpack-plugin tried to access @swc/core (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: @swc/core
Required by: swc-minify-webpack-plugin@virtual:60473337ce2cd480de1562e14cfd99db8e1d590e5cf0f2d440e898432dd500d6157841c9426eaee187c5efd0f3030769e3b5df4dd132fd9c192d
```

### Payload Version

2.6.0

### Adapters and Plugins

db-postgres

**Comment by rburgst** [comment] 2024-01-07 10:20
after that I did
```
yarn add @swc/core
```

then I get
```
yarn dev
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node src/server.ts -- -I`

/Users/rainer/git/private/turnen/sports-payload/.pnp.cjs:24571
      Error.captureStackTrace(firstError);
            ^
Error: slate-react tried to access react-dom (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: react-dom
```
The out of box experience leaves something to be desired. Also tried the website starter with similar problems.

**Comment by rburgst** [comment] 2024-01-07 10:23
Then these are the other dependencies I needed to add manually:
* react-dom
* react 
* drizzle-orm
* @libsql/client

after I added all of these dependencies the server starts up with the following error:
```
yarn dev               
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node src/server.ts -- -I`
(node:38575) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
webpack built fae3b8b2ec9d1c58d668 in 209ms
ERROR in main
Module not found: Error: Can't resolve '/Users/rainer/git/private/turnen/sports-payload/payload/dist/admin' in '/Users/rainer/git/private/turnen/sports-payload'

webpack compiled with 1 error
[10:22:53] INFO (payload): Starting Payload...
[10:22:53] INFO (payload): Payload Admin URL: /admin
```

**Comment by rburgst** [comment] 2024-01-07 10:26
when I then try to do a `yarn build` I get the following
```
yarn build
(node:39352) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
assets by status 380 bytes [cached] 2 assets

ERROR in main
Module not found: Error: Can't resolve '/Users/rainer/git/private/turnen/sports-payload/payload/dist/admin' in '/Users/rainer/git/private/turnen/sports-payload'
resolve '/Users/rainer/git/private/turnen/sports-payload/payload/dist/admin' in '/Users/rainer/git/private/turnen/sports-payload'
  using description file: /Users/rainer/git/private/turnen/sports-payload/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    root path /Users/rainer/git/private/turnen/sports-payload
      using description file: /Users/rainer/git/private/turnen/sports-payload/package.json (relative path: ./Users/rainer/git/private/turnen/sports-payload/payload/dist/admin)
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          /Users/rainer/git/private/turnen/sports-payload/Users/rainer/git/private/turnen/sports-payload/payload/dist/admin doesn't exist
        .ts
```

**Comment by rburgst** [comment] 2024-01-07 10:40
ok, wiped everything and didnt use `yarn` but `pnpm`, also you have to delete `.pnp*`, then it works properly.

At any rate the documentation and current generated app dont work. It would be good to directly point people to use `pnpm` and not generate the pnp files at all.

**Comment by jmikrut** [comment] 2024-01-08 17:08
Hey @rburgst — what version of Yarn are you using? I can't reproduce using Yarn on my computer but I'm guessing there might be something amiss with a specific Yarn version.

Let us know - thank you!

**Comment by denolfe** [comment] 2024-01-08 19:28
I was able to recreate this by using yarn 4 and setting `nodeLinker: pnp` in `.yarnrc.yml`.  You can work around this for the time being by setting this to `node-modules` in that file or running `yarn config set nodeLinker node-modules`.

We are actively reworking our templates to use the latest yarn already, so it looks like we need to ensure things work with pnp or proactively set this to `node-modules` in the `.yarnrc.yml` file.

Let me know if the solution above works for you. Either way, I will keep this open until the templates are updated to support latest yarn.

**Comment by rburgst** [comment] 2024-01-09 05:51
My yarn version is 3.3.0. I didnt actively switch to pnp but these files were generated automatically by the generator. Also I didnt have any `.yarnrc.yml` in the repo that was being generated.
For now I prefer using pnpm anyway.

<img width="773" alt="image" src="https://github.com/payloadcms/payload/assets/22971/7868d7a8-4142-4b72-b4c9-7ee64a4afb82">
This is the repo just after running `npx create-payload-app@latest`
<img width="413" alt="image" src="https://github.com/payloadcms/payload/assets/22971/e4022533-2f0f-476a-8ecd-9165da8022ec">
Notice the lack of `.yarnrc.yml` and the generated `.pnp.cjs` and `.pnp.loader.mjs`.

**Comment by denolfe** [comment] 2024-01-10 18:44
It sounds like if you have your yarn version set to latest at a higher level than your new project dir, it will take those defaults. 

Unfortunately, `pnp` being the default for yarn modern causes issues here, as it's a multi-step process to get this all to work.

1. cd into dir and run `yarn set version stable`, which scaffolds `.yarn/`, `.yarnrc.yml`, and sets yarn version in `package.json`
2. The `yarn.lock` file then needs to be updated with `yarn install`. Sometimes this just flat out fails, so you have to delete the `yarn.lock`, create a blank one, then `yarn install`

Quite a bit of orchestration, but _it is possible_. I'd much rather us move to `pnpm` completely for our templates. Closing this for now as there is a workaround documented above, but I agree there is work to be done to make this better with yarn modern.

**Closed by denolfe** 2024-01-10 18:44 UTC
Labels: possible-bug
