### ISSUE TITLE
mimeType field being configured throws an exception on media creation on admin UI on 1.5.7

### ISSUE THREAD

**Issue by bencun** [payloadcms/payload#1867] opened 2023-01-13 00:53 UTC
# Bug Report

When setting a `mimeType` field of a media collection to any value, even an empty array, and trying to create a new entry in the media collection the following error pops up:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filename')
    at Object.validate (mimeTypeValidator.js:5:1)
    at addFieldStatePromise (addFieldStatePromise.js:29:1)
    at async Promise.all (index 3)
    at async iterateFields (iterateFields.js:28:1)
    at async addFieldStatePromise (addFieldStatePromise.js:142:1)
    at async Promise.all (index 0)
    at async iterateFields (iterateFields.js:28:1)
    at async addFieldStatePromise (addFieldStatePromise.js:142:1)
    at async Promise.all (index 8)
    at async iterateFields (iterateFields.js:28:1)
```

This happens only on 1.5.7, everything works just fine on 1.5.4.

## Steps to Reproduce

1. Use Payload 1.5.7
2. Create a media collection
3. Configure `mimeType` field to any value, even an `[]` empty array works
4. Open the admin panel, go to your collection and click "Create"
5. Observe the error

## Other Details

Chrome, Payload 1.5.7

Not sure what caused this regression in 1.5.7

**Comment by AltanS** [comment] 2023-01-13 13:48
I had a similar issue today. After debugging for a bit, I found out that the last working version for me was `1.3.4`, so something on the `1.4.0` release broke my import scripts. The relevant lines for me in the changes were

https://github.com/payloadcms/payload/blob/master/src/uploads/generateFileData.ts#L93-L106

In the else block, `mime` is set to the `mimetype` of the file being uploaded.

If you take a look at the previous version of the file from releases prior to `1.4.0` the variable `mime` is set differently.
https://github.com/payloadcms/payload/blob/bab34d82f5fddad32ceafd116ad97e87cab4c862/src/uploads/generateFileData.ts#L84-L86

I'm not sure if it should have never worked in the first place, but the fix for me was to pass a `contentType` for the file field of the form-data being sent to the collection endpoint.

```js
...
    formData.append('file', mediaBuffer, { filename: media.filename, contentType: media.mime_type });
...
```

**Comment by TartagliaEG** [comment] 2023-01-14 20:04
Just updated from 1.5.1 to 1.5.8 and noticed the same problem. I also tested the releases in between and was able to narrow the problem down to version 1.5.5 at this SHA-d40e1369472f212b5f85bfc72fac01dc708aa507.

That commit changed the `getBaseUploadFields` function to mark some fields as hidden instead of disabled. It seems that, as a result, some validations that were not being triggered before started to run.

Setting the mimeType field configuration back to disabled makes the media creation page to work again.
<img width="655" alt="image" src="https://user-images.githubusercontent.com/18357965/212493800-0e431c5a-49f3-4aa8-aa32-d543d0379ac5.png">

The failing script, as pointed by the stack trace,  is this one 'src/uploads/mimeTypeValidator.ts'. The problem happens when we try to create a new media (**during the page load**).  Viewing or editing a pre-existing media doesn't crash the app.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/18357965/212492414-eb490e22-0473-427d-9288-8eeafe1adff1.png">

It seems that the `mimeTypeValidator` should no be called during the page load, given that there's nothing to validate yet, but I'm not familiar with the source code to be sure.

**Comment by jmikrut** [comment] 2023-01-15 14:43
Hey @TartagliaEG @AltanS @bencun — thank you for the detailed analysis here! You are spot on. There was a regression caused by changing our base upload fields to `hidden` rather than `disabled`. The mime type validator now runs on the frontend, as it should, but the problem was caused by how we construct initial form state / form data.

This is now fixed and a patch is being deployed now. Thank you!

**Closed by jmikrut** 2023-01-15 14:43 UTC
Labels: possible-bug
