### ISSUE TITLE
Admin panel, filtering of references in overlay does not work (at least if its a uploadable collection)

### ISSUE THREAD

**Issue by dominikzogg** [payloadcms/payload#3384] opened 2023-09-22 06:09 UTC
### Link to reproduction

-

### To Reproduce

Filtering the list by filename works great when in the collection view of the media collection.
Filtering the list by filename (or any other filter like id) does not work when viewing in overlay (try to reuse existing upload)

I got a guess, that its cause the filtering within the field (code, but i am not sure)

```
const mediaCollection = {
    slug: 'media',
    upload: {
        adminThumbnail: 'thumbnail',
        imageSizes: [
            {
                name: 'thumbnail',
                width: 175,
            },
        ],
        mimeTypes: ['image/jpeg', 'image/png', 'application/pdf'],
    },
    fields: [],
};

const mediaField = {
    name: 'logo',
    type: 'upload',
    relationTo: 'media',
    filterOptions: {
        or: [{ mimeType: { equals: 'image/jpeg' } }, { mimeType: { equals: 'image/png' } }],
    },
};
```

### Describe the Bug

We got an application which more than 4k files (many images) and its nearly impossible to find an existing file without the possibility to filter it.

### Payload Version

1.15.6

**Comment by jacobsfletch** [comment] 2023-10-12 20:48
Hey @dominikzogg we'll get to the bottom of this. Thanks for the report 👍

**Comment by jacobsfletch** [comment] 2023-10-16 19:03
@dominikzogg are you on Payload 2.x? So far I've been unable to reproduce this. If you could provide a reproduction on latest I would be happy to continue debugging here.

**Comment by jacobsfletch** [comment] 2023-10-16 19:07
Here's a quick screen recording from my end:

https://github.com/payloadcms/payload/assets/15735305/23cfedcd-8ec0-4f54-bce7-dc8a643416b9

**Comment by dominikzogg** [comment] 2023-10-16 20:38
@jacobsfletch I am using payload@^1.15.8 with @payloadcms/plugin-cloud-storage^1.0.19, but i guess in context of search if should not be relevant to use the plugin with S3 (DigitalOcean Spaces).

Have you tried it with a prefiltered field?

```
  filterOptions: {
        or: [{ mimeType: { equals: 'image/jpeg' } }, { mimeType: { equals: 'image/png' } }],
    },
    ``

**Comment by jacobsfletch** [comment] 2023-10-23 21:45
Yea @dominikzogg I am using the `filterOptions` there. I went ahead and pulled this down again today and was still unable to recreate 🤔 would you be able to create a reproduction on 2.0 for me to see? I can smash out a fix for this if I can reproduce. We have the `_community` test suite that makes this super easy: https://github.com/payloadcms/payload/tree/main/test/_community

**Comment by dominikzogg** [comment] 2023-10-31 08:10
@jacobsfletch i am on 1.x, but currently prepare the update to payload v2. There are some issues currently which block the update but onces those are fixed. I try it again.

**Comment by jacobsfletch** [comment] 2023-11-09 05:19
Sounds good @dominikzogg 👍 I'm going to mark this as closed but let me know if you're still having troubles with this once you've upgraded.

**Closed by jacobsfletch** 2023-11-09 05:19 UTC
Labels: cant-reproduce

**Comment by dominikzogg** [comment] 2023-11-09 05:26
@jacobsfletch blocker for testing it on staging/production https://github.com/payloadcms/payload/issues/3942 but i should been able to already test it locally. Thanks for your effort so far.

**Comment by dominikzogg** [comment] 2023-11-09 06:18
@jacobsfletch filter for names seems to work in the v2 (as overlay and as normal list view), but search for ID i get the following, when i am typing (as overlay and as normal list view).

```
/api/media?page=1&where[and][1][or][0][mimeType][equals]=image/jpeg&where[and][1][or][1][mimeType][equals]=image/png&where[and][1][or][2][mimeType][equals]=image/webp&where[and][2][or][0][undefined][like]=1
```

```
TypeError: Cannot read properties of undefined (reading 'type')
    at sanitizeQueryValue (/app/node_modules/@payloadcms/db-mongodb/src/queries/sanitizeQueryValue.ts:43:13)
    at buildSearchParam (/app/node_modules/@payloadcms/db-mongodb/src/queries/buildSearchParams.ts:95:46)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async parseParams (/app/node_modules/@payloadcms/db-mongodb/src/queries/parseParams.ts:60:35)
    at async buildAndOrConditions (/app/node_modules/@payloadcms/db-mongodb/src/queries/buildAndOrConditions.ts:29:22)
    at async parseParams (/app/node_modules/@payloadcms/db-mongodb/src/queries/parseParams.ts:43:33)
    at async buildAndOrConditions (/app/node_modules/@payloadcms/db-mongodb/src/queries/buildAndOrConditions.ts:29:22)
    at async parseParams (/app/node_modules/@payloadcms/db-mongodb/src/queries/parseParams.ts:43:33)
    at async buildAndOrConditions (/app/node_modules/@payloadcms/db-mongodb/src/queries/buildAndOrConditions.ts:29:22)
    at async parseParams (/app/node_modules/@payloadcms/db-mongodb/src/queries/parseParams.ts:43:33)
    at async Function.buildQuery (/app/node_modules/@payloadcms/db-mongodb/src/queries/buildQuery.ts:43:22)
    at async Object.find (/app/node_modules/@payloadcms/db-mongodb/src/find.ts:39:17)
    at async find (/app/node_modules/payload/src/collections/operations/find.ts:144:16)
    at async findHandler (/app/node_modules/payload/src/collections/requestHandlers/find.ts:30:20)
```
