### ISSUE TITLE
Filtering Records Using Number Fields in Admin List

### ISSUE THREAD

**Issue by giti-coder** [payloadcms/payload#3305] opened 2023-09-11 04:49 UTC
### Link to reproduction

N/A

### To Reproduce

1. Create a field in a collection with type `number`
2. Using that field, create records with numbers (for example) 2, 3 & 4. Now you will have 3 records.
3.  Using the filter in the admin list:
- Select the number field.
- Choose `is greater than or equal to` operator.
- Enter the number 3.

**Expected Result:** The filter should eliminate all records with values less than 3 (i.e. record with number 2 in our case).
**Current Result:** The filter keeps all records as is without filtering records less than the value indicated.

### Describe the Bug

Using the filter operator `is greater than or equal to`, the filter does not eliminate all records with numbers less than the value indicated.

### Payload Version

1.15.5

**Comment by JessChowdhury** [comment] 2023-09-11 10:18
Hey @giti-coder - thank you for reporting this! I was able to find the cause of this issue, it was a small discrepancy in the filter names. We will release a fix for this shortly - stay tuned.

**Comment by giti-coder** [comment] 2023-09-11 10:22
@JessChowdhury Great! Thanks for your very fast response and action! Looking forward to the fix release! 🔥

**Closed** 2023-09-11 17:08 UTC
Labels: bug
