### ISSUE TITLE
Payload still expects config file when using prebuilt config

### ISSUE THREAD

**Issue by malymato** [payloadcms/payload#1838] opened 2023-01-10 02:45 UTC
# Bug Report

> Error: cannot find Payload config. Please create a configuration file located at the root of your current working directory called "payload.config.js" or "payload.config.ts".

## Steps to reproduce 

1. `payload.init({
    config,
    ..
 });`

2. Run NPM script: `"build:payload": "payload build"`

## Other Details
Payload Version 1.5.4

**Comment by jmikrut** [comment] 2023-01-10 14:45
Hey @malymato — this is an experimental and un-documented feature at this point because it's not fully done. We are using it to test some VERY cool things in the background right now. 

But yes, as you've discovered, you still need to have your config path available even when passing the config directly to Payload. The reason is that Webpack is a _**file-based**_ bundler, and it needs to actually be able to load files from disk in order to package them up. So the Payload config is needed within Webpack itself. 

I am going to close this because this is intended behavior at this point, but there is more to come from Payload here over the next few months. In the meantime, passing the `config` will give you performance increases on cold-start times in production, but that's really the only utility here at this point. And if you decide to pass your config directly, you do need to have a config present still.

**Closed by jmikrut** 2023-01-10 14:45 UTC
Labels: possible-bug
