### ISSUE TITLE
Unique option doesn't work

### ISSUE THREAD

**Issue by 383bd03d** [payloadcms/payload#1282] opened 2022-10-20 12:08 UTC
`
fields: [
        {
            type: "email",
            name: "email",
            unique: true,
        }
    ]
`
This example allows create same entries marked as unique in version 1.1.15

**Comment by DanRibbens** [comment] 2022-10-28 20:50
Hey @383bd03d,
I was not able to reproduce this issue.

Did it make a `unique` index on collection?

![image](https://user-images.githubusercontent.com/6434612/198729671-a9cc9c6c-fd83-4f11-bbec-f7ac447ad219.png)

Any other information you can provide would be helpful for us to troubleshoot why your indexes aren't being made.

Thanks!

**Comment by DanRibbens** [comment] 2022-10-31 13:11
I'm going to close this as we can't reproduce it. If you have more for us feel free to reopen for us to look again.

Thanks!

**Closed by DanRibbens** 2022-10-31 13:11 UTC
Labels: possible-bug

**Comment by richadr** [comment] 2022-12-30 11:12
After running into this and trying out a couple of things, I figured out that (1) you need to use this in combination with `index: true` and (2) it will create the unique index only when creating a new document, not when updating your Payload config.  Hope this helps.
