### ISSUE TITLE
Blocks Field: … > Duplicate > Save won’t save, but errors instead

### ISSUE THREAD

**Issue by robinscholz** [payloadcms/payload#8125] opened 2024-09-09 06:15 UTC
### Environment Info

```text
Payload: "3.0.0-beta.84",
Next: 15.0.0-canary.120
Node: v20.17.0
```

### Describe the Bug

When cloning blocks via the context (…) menu, payload is not able to save the duplicated data. The api request returns a 500 error. The payload of the request almost seems irrelevant, since this happens with any block we are trying to duplicate.

https://github.com/user-attachments/assets/36122556-258d-46d2-a868-c2beaa00103c

### Reproduction Steps

1. Add a blocks field to a collection
2. Add a first block and safe
3. Duplicate the block via the … menu
4. Press save

**Comment by paulpopus** [comment] 2024-09-09 06:24
Can you make sure you test the latest beta please?

If it still happens can you provide a reproduction? I just tested this on the latest beta and I can't reproduce the bug

**Comment by robinscholz** [comment] 2024-09-09 06:39
Getting a more precise error response with the latest version:

```
{
    "errors": [
        {
            "name": "ValidationError",
            "data": {
                "id": 24,
                "errors": [
                    {
                        "field": "id",
                        "message": "Value must be unique"
                    }
                ]
            },
            "message": "The following field is invalid: id"
        }
    ]
}
```

**Comment by alsherif-khalaf** [comment] 2024-09-19 06:57
> https://github.com/alsherif-khalaf/fresh-payload-website-localized
tested with 107 and it is exist

**Comment by alsherif-khalaf** [comment] 2024-09-19 07:50
works only after adding locale to fields

```ts

    {
      name: 'columns',
      type: 'array',
      localized: true,
      fields: columnFields,
    },

```

**Comment by tim-the-arcane** [comment] 2024-10-01 09:04
Still an issue on 3.0.0-beta.110. 

Adding `localized: true` only works for non-nested fields. 

But the JSON of nested blocks gets duplicated 1:1 inside the payload of the PATCH request, including the `id` field of nested blocks. 

It should instead only recreate the structure and regenerate a new UUID per block all the way down, when clicking the duplicate button.

**Comment by r1tsuu** [comment] 2024-10-31 23:21
I believe this was fixed here https://github.com/payloadcms/payload/pull/8790, closing.

**Closed by r1tsuu** 2024-10-31 23:21 UTC
Labels: status: needs-repro, v3
