### ISSUE TITLE
Rich text editor table cannot be updated after it was saved

### ISSUE THREAD

**Issue by radudevit** [payloadcms/payload#7920] opened 2024-08-28 14:36 UTC
### Environment Info

```text
Payload: v3.0.0-beta.94
Node: v20.15.1
Next: 15.0.0-canary.104
```

### Describe the Bug

After adding a table in rich text editor and saving it, the table cannot be edited anymore.

### Reproduction Steps

1. Create a table in rich text editor
2. Save the item
3. Try to remove a row/column. Click on the menu button
![image](https://github.com/user-attachments/assets/5a3b1abc-5fb9-48fa-b526-0aaf75d2470a)
4. The menu is not appearing, and table cannot be edited.

**Comment by GermanJablo** [comment] 2024-08-28 17:36
@radudevit I can't reproduce it

https://www.loom.com/share/9960b1c8bbbd4083afee913c6a99be1f

You may want to take a look at the [reproduction guide](https://github.com/payloadcms/payload/blob/main/.github/reproduction-guide.md)

**Comment by GermanJablo** [comment] 2024-09-12 22:13
Closing due to lack of repro. Feel free to open a new issue if you have more insight to give us.

**Closed by GermanJablo** 2024-09-12 22:13 UTC
Labels: status: cant-reproduce, plugin: richtext-lexical, v3, prioritized
