### ISSUE TITLE
If `field.hidden === true` and `field.admin.hidden === false` the field is hidden in the admin ui.

### ISSUE THREAD

**Issue by ApplY3D** [payloadcms/payload#8518] opened 2024-10-02 13:27 UTC
### Environment Info

```text
Binaries:
  Node: 20.14.0
  npm: 10.7.0
  Yarn: 1.22.10
  pnpm: 8.10.5
Relevant Packages:
  payload: 3.0.0-beta.110
  next: 15.0.0-canary.160
  @payloadcms/db-mongodb: 3.0.0-beta.110
  @payloadcms/email-nodemailer: 3.0.0-beta.110
  @payloadcms/graphql: 3.0.0-beta.110
  @payloadcms/next/utilities: 3.0.0-beta.110
  @payloadcms/plugin-cloud: 3.0.0-beta.110
  @payloadcms/plugin-nested-docs: 3.0.0-beta.110
  @payloadcms/richtext-lexical: 3.0.0-beta.110
  @payloadcms/translations: 3.0.0-beta.110
  @payloadcms/ui/shared: 3.0.0-beta.110
  react: 19.0.0-rc-5dcb0097-20240918
  react-dom: 19.0.0-rc-5dcb0097-20240918
```

### Describe the Bug

If `field.hidden === true` and `field.admin.hidden === false` the field is hidden in the admin ui.

### Reproduction Steps

Short version:
```ts
{
  name: 'someField',
  type: 'array',
  fields: [/** relationship, required + text, required */],
  hidden: true,
  admin: { hidden: false, readOnly: true, position: 'sidebar' },
}
```

**Comment by akhrarovsaid** [comment] 2024-10-02 14:33
Hey @ApplY3D,

According to the docs:

`admin.hidden` - "Will transform the field into a hidden input type. Its value will still submit with requests in the Admin Panel, but the field itself will not be visible to editors." ([See docs](https://payloadcms.com/docs/beta/admin/fields#admin-options))

Field-level `hidden` - "Restrict this field's visibility **from all APIs entirely**. Will still be saved to the database, but **will not appear in any API or the Admin Panel.**" ([See docs](https://payloadcms.com/docs/beta/fields/checkbox#config-options))

You have `hidden: true` on the field itself - according to the docs you **shouldn't** be able to see the field in the Admin UI. This is the expected behavior if I'm not mistaken. Is this really a bug?

**Comment by denolfe** [comment] 2024-10-02 14:44
You are correct @akhrarovsaid , this is the desired behavior.

Closing as this is the intended functionality.

**Closed by denolfe** 2024-10-02 14:44 UTC
Labels: status: needs-triage, v3
