### ISSUE TITLE
The LinkFeature modal doesn't appear when it's triggered from within another modal

### ISSUE THREAD

**Issue by Mng-dev-ai** [payloadcms/payload#4271] opened 2023-11-27 01:26 UTC
### Link to reproduction

https://github.com/Mng-dev-ai/payload-reproduction

### Describe the Bug

https://github.com/payloadcms/payload/assets/50384638/b9573014-748b-4e3f-a9b9-49e434eed45e

As demonstrated in the video above, I'm creating a new feature in lexical and the link modal fails to display when it is triggered from within another modal

### To Reproduce

That's the part where i render the modal
```
        <Modal slug={MODAL_SLUG} className={`${BASE_CLASS}__modal`}>
            <MinimalTemplate className={`${BASE_CLASS}__template`} width="wide">
                <header className={`${BASE_CLASS}__header`}>
                    <h3>{header}</h3>
                    <Button buttonStyle="none" onClick={handleClose}>
                        <X />
                    </Button>
                </header>
                <Form onSubmit={onSubmit} initialState={initialState}>
                    <RichText
                        name="footnote"
                        label="Footnote"
                        editor={lexicalEditor({
                            features: [LinkFeature({}), ItalicTextFeature(), BoldTextFeature()],
                        })}
                        type="richText"
                        admin={{
                            className: `${BASE_CLASS}__rich-text`,
                        }}
                    />
                    <Submit>Submit</Submit>
                </Form>
            </MinimalTemplate>
        </Modal>

```

### Payload Version

2.2.1

**Comment by AlessioGr** [comment] 2023-11-30 11:24
Hello! I haven't been able to reproduce this.

Could you attach a reproduction to your issue? You can find our reproduction guide [here](https://github.com/payloadcms/payload/blob/main/.github/reproduction-guide.md) :)

**Comment by AlessioGr** [comment] 2023-12-09 17:37
@Mng-dev-ai I've tested it out. While I was able to reproduce it, it seems to be an issue with your code rather than lexical:

```ts
 <Form onSubmit={onSubmit} initialState={initialState}>
                    <RichText
                        name="footnote"
                        label="Footnote"
                        editor={lexicalEditor({
                            features: [LinkFeature({}), ItalicTextFeature(), BoldTextFeature()],
                        })}
                        type="richText"
                        admin={{
                            className: `${BASE_CLASS}__rich-text`,
                        }}
                    />
                    <Submit>Submit</Submit>
</Form
```

The link drawer and closes immediately, because this:

```ts
{lexicalEditor({
                            features: [LinkFeature({}), ItalicTextFeature(), BoldTextFeature()],
                        })}
```
                        
Contains the lexical editor which is re-created every time the parent is re-rendered, thus causing the drawer to close itself immediately.

You will have to initialize the `lexicalEditor` function **OUTSIDE** of the react component, so that it doesn't keep re-initializing itself (and thus the lexical editor component which is initialized inside of the `lexicalEditor` function) for every re-render.

Additionally, you might also want to give the `<Form` element a `fields` property, containing your fieldschema. Otherwise, you could be facing issue with fields using rows in the future (e.g. Arrays and Blocks). Make sure you re-use that same `lexicalEditor` property in that fieldschema.

**Closed by AlessioGr** 2023-12-09 17:37 UTC
Labels: reproduced, plugin: richtext-lexical

**Comment by Mng-dev-ai** [comment] 2023-12-09 18:04
@AlessioGr ohhh that's correct, confirming that initializing the lexical editor outside of the react component fixed it, thank you
