### ISSUE TITLE
Admin panel RTL issue

### ISSUE THREAD

**Issue by MahdiZangeneh** [payloadcms/payload#4564] opened 2023-12-20 03:33 UTC
### Describe the Bug

When collapsing the admin side navbar in RTL locale, the UI design appears disorderly, as illustrated in the image below. This issue is likely attributed to incorrect CSS property configurations in the RTL version.
<img width="1783" alt="1" src="https://github.com/payloadcms/payload/assets/131523744/82492613-f551-4c67-9af5-103b6d602d53">

### To Reproduce

- In admin > account screen > Payload Setting  (admin/account), change the language to either Farsi or Arabic
- Collapse side navbar

### Payload Version

1.0.0

**Comment by PatrikKozak** [comment] 2024-01-02 15:19
Hey @MahdiZangeneh - are you still experiencing this issue? If so, what version of Payload are you on?

You specified version 1.0.0 in the description but by the looks of your image, the collapsible nav bar exists which wasn't introduced till 2.0.0.

**Comment by PatrikKozak** [comment] 2024-01-04 14:40
@MahdiZangeneh I was unable to reproduce this so I'm going to close this for now. Iif you are able to reproduce still in the future and can provide a reproducible repo, I'll reopen this issue for you!

**Closed by PatrikKozak** 2024-01-04 14:40 UTC
Labels: possible-bug, cant-reproduce

**Comment by MahdiZangeneh** [comment] 2024-01-04 14:44
@PatrikKozak sorry for the late response and thanks for investigating the issue. last time I checked the issue was fixed in a way that the whole side navbar repositioned to the left (like LTR mode)
I will re-check again and let you know
