### ISSUE TITLE
Postgres migration error: "column \"_path\" does not exist"

### ISSUE THREAD

**Issue by edxv** [payloadcms/payload#3899] opened 2023-10-27 13:00 UTC
### Describe the Bug

Hi team,

I'm trying out Payload 2.0 and the Postgres adapter. We've got an existing v1 schema that runs on Mongo. After generating migration files for Postgres and running `payload migrate` I get the following error:

```
[12:37:54] ERROR (payload): Error running migration 20231027_123745 column "_path" does not exist.
    err: {
      "type": "DatabaseError",
      "message": "column \"_path\" does not exist",
      "stack":
          error: column "_path" does not exist
              at /REDACTED/node_modules/.pnpm/pg-pool@3.6.1_pg@8.11.3/node_modules/pg-pool/index.js:45:11
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      "length": 95,
      "name": "error",
      "severity": "ERROR",
      "code": "42703",
      "file": "indexcmds.c",
      "line": "1756",
      "routine": "ComputeIndexAttrs"
    }
```
I tried generating the migration file with both plain `payload migrate:create` and `payload migrate:create --file @payloadcms/db-mongodb/versions-v1-v2` but the same error happens. 

There's a bunch of `CREATE INDEX IF NOT EXISTS "path_idx" ON ... ("_path");`  towards the end of the migration file, which is the only place I can see the column being referenced. In all previous instances, it's in a `CREATE TABLE IF NOT EXISTS ...` statement. One example:

```
CREATE TABLE IF NOT EXISTS "lesson_checkpoints_blocks_lesson_checkpoint_body_achievement_card_block" (
    "_order" integer NOT NULL,
    "_parent_id" varchar NOT NULL,
    "_path" text NOT NULL,
    "id" varchar PRIMARY KEY NOT NULL,
    "include_in_recap" boolean,
    "block_name" varchar
);
```

and later:
```
CREATE INDEX IF NOT EXISTS "path_idx" ON "lesson_checkpoints_blocks_lesson_checkpoint_body_achievement_card_block" ("_path");
```

The migration script must be trying to create this index on `_path` for a table that doesn't have the column? Any ideas how to diagnose or fix?

Thanks!

---

Discord thread: https://discord.com/channels/967097582721572934/1167444838480879717

### To Reproduce

1. Set up a v1 Payload schema (with Mongo) which includes entries with Blocks fields.
2. Upgrade to v2, add Postgres adapter.
3. Generate a migration file with `payload migrate:create`.
4. Run migration with `payload migrate`.

### Payload Version

^2.0.13

### Adapters and Plugins

@payloadcms/db-postgres, @payloadcms/bundler-webpack, @payloadcms/richtext-slate, @payloadcms/plugin-cloud-storage

**Comment by edxv** [comment] 2023-11-02 13:25
Apologies, this does not appear to be a bug with Payload. This was seemingly caused by preexisting table names in our Postgres DB clashing with the Payload table names generated by `payload migrate:create`. On a fresh DB instance, there is no error.

**Comment by DanRibbens** [comment] 2023-11-02 13:37
Thank you for the update @edxv!

**Comment by edxv** [comment] 2023-11-02 13:44
Sorry @DanRibbens I spoke too soon. The reason it worked on a fresh instance was because I had been playing with the generated migration file and deleted all lines like the following:

`CREATE INDEX IF NOT EXISTS "path_idx" ON "_[ENTITY]_block" ("_path");`

If I remove these `CREATE INDEX ...` lines then the migration works. It only seems to be happening on Blocks fields.

**Comment by edxv** [comment] 2023-11-02 14:19
I'm not sure if this is related but I am also seeing errors when accessing any collection containing a Blocks field.

For example, when I try to access our Lesson Checkpoints collection in Payload admin (which contains a Blocks field), I get:

```log
ERROR (payload): error: column _lesson_checkpoints_v__blocks_lessonCheckpointBodyLayoutBlock._path does not exist
```

Block config:
```ts
const LessonCheckpointBodyLayoutBlock: Block = {
  slug: 'lessonCheckpointBodyLayoutBlock',

  labels: {
    singular: 'Layout',
    plural: 'Layouts'
  },

  fields: [
    {
      name: 'type',
      label: 'Select a layout',
      type: 'select',
      options: [
        {
          label: 'Vertical stack',
          value: 'stack_vertical'
        },
        {
          label: 'Horizontal stack',
          value: 'stack_horizontal'
        },
        {
          label: 'Simple grid',
          value: 'grid'
        }
      ],
      defaultValue: 'stack_vertical'
    },
    {
      name: 'spacing',
      label: 'Spacing',
      type: 'number',
      defaultValue: 6,
      required: true,
      admin: {
        condition: (_, siblingData) => siblingData.type !== 'grid'
      }
    },
    {
      name: 'grid_columns',
      label: 'Grid columns',
      type: 'number',
      defaultValue: 2,
      admin: {
        condition: (_, siblingData) => siblingData.type === 'grid'
      }
    },
    {
      name: 'content_width',
      label: 'Content width',
      type: 'select',
      options: [
        { value: 'full', label: 'Full' },
        { value: 'narrow', label: 'Narrow' }
      ],
      defaultValue: 'narrow',
      required: true
    },
    {
      name: 'cells',
      label: 'Layout cells',
      labels: {
        singular: 'Cell',
        plural: 'Cells'
      },
      type: 'array',
      fields: [
        {
          name: 'body',
          label: 'Content',
          labels: {
            singular: 'Content',
            plural: 'Content'
          },
          type: 'blocks',
          minRows: 1,
          blocks: [
            LessonCheckpointBodyCardBlock,
            LessonCheckpointBodyStackBlock,
            ...InnerDefaultContentBlocks
          ]
        }
      ]
    }
  ]
}
```

Relevant lines in migration file:
```sql
...

CREATE TABLE IF NOT EXISTS "lesson_checkpoints_blocks_lesson_checkpoint_body_layout_block" (
	"_order" integer NOT NULL,
	"_parent_id" varchar NOT NULL,
	"_path" text NOT NULL,
	"id" varchar PRIMARY KEY NOT NULL,
	"type" "enum_lesson_checkpoints_blocks_lesson_checkpoint_body_layout_block_type",
	"spacing" numeric,
	"grid_columns" numeric,
	"content_width" "enum_lesson_checkpoints_blocks_lesson_checkpoint_body_layout_block_content_width",
	"block_name" varchar
);

CREATE INDEX IF NOT EXISTS "order_idx" ON "lesson_checkpoints_blocks_lesson_checkpoint_body_layout_block" ("_order");
CREATE INDEX IF NOT EXISTS "parent_id_idx" ON "lesson_checkpoints_blocks_lesson_checkpoint_body_layout_block" ("_parent_id");
```

I note that the block slug is camelcase but the generated table names are snake case.

**Comment by jmikrut** [comment] 2024-01-08 21:55
Hey @edxv — this is probably caused by your table name length.

Postgres has a max table length of 64 characters, so this one is going to be problematic:

```
lesson_checkpoints_blocks_lesson_checkpoint_body_layout_block
```

#4525 is about to be merged, and when it is, you can define custom table names for the tables you are creating that are super long. Once that's done, I am guessing that the issue in this thread will go away. So let's defer to that PR to track progress and I will close this issue in the meantime.

Thank you for bringing this up!

**Closed by jmikrut** 2024-01-08 21:55 UTC
Labels: possible-bug, db-postgres
