### ISSUE TITLE
Lexical error with Blank CMS

### ISSUE THREAD

**Issue by muperdev** [payloadcms/payload#4807] opened 2024-01-14 06:33 UTC
### Describe the Bug

When I try to use the blank cms template first of all it didn't build it in cloud
second of all when I clone to development and added lexical editor as editor in config, it shows me this error on the console:
![image](https://github.com/payloadcms/payload/assets/85489543/295054dc-830f-4f1b-badb-33761b4b9bbd)
then I upload the payload version to 2.8.0 then it fixed!

### To Reproduce

1. clone blank CMS template
2. add lexical as editor
3. 
![image](https://github.com/payloadcms/payload/assets/85489543/6bb890ab-1a36-4e53-ae03-3f65dfa69196)

### Payload Version

2.0.0

**Comment by AlessioGr** [comment] 2024-02-12 15:40
Closing this, as I cannot reproduce this issue. You likely had a payload version which was too old in your yarn/pnpm cache or something like that, and it used that, instead of installing the new version.

At this stage, new, breaking lexical updates may require the payload version to be updated as well. What's important is that it doesn't happen the other way around: updating payload to a new, minor version, shouldn't require the lexical plugin to be updated.

**Closed by AlessioGr** 2024-02-12 15:40 UTC
Labels: [cant-reproduce], [missing-reproduction], plugin: richtext-lexical
