### ISSUE TITLE
Next.js 15.0-canary.104 Causes an "Error: Maximum call stack size exceeded" in the Nodemailer adapter

### ISSUE THREAD

**Issue by yobottehg** [payloadcms/payload#7580] opened 2024-08-08 07:09 UTC
### Payload Version

3.0 beta 76

### Node Version

20 LTS

### Next.js Version

15.0.0-104

### Describe the Bug

After adding a nodemailer Adapter and clicking some pages the site crashes with "Error: Maximum call stack size exceeded". Removing the NodeMailer Adapter solves this problem.

See also the discord thread: https://discord.com/channels/967097582721572934/1031993785971900556/threads/1270936640021336105

### Reproduction Steps

- Use latest 3.0 release
- Add a Nodemailer with transport options configuration
- Open payload, the first visit will work
- Reload the page -> See the error
- Remove email config from payload config file
- Reload the page -> Error gone.

**Comment by tomekwlod** [comment] 2024-08-08 11:20
I am not sure if this is related, but I am experiencing a similar error type but caused by `node_modules/deepmerge` lib. Everything was working fine until version 3.0 beta 67. For me, the error occurs in dev mode as soon as I start the server and save any file in my IDE. If I don't trigger a server reload, everything operates normally.

Here is the error message I am receiving:
```
RangeError: Maximum call stack size exceeded
    at Array.filter (<anonymous>)
    at getEnumerableOwnPropertySymbols (webpack-internal:///(rsc)/./node_modules/deepmerge/dist/cjs.js:54:42)
.....
  52 | function getEnumerableOwnPropertySymbols(target) {
  53 | 	return Object.getOwnPropertySymbols
> 54 | 		? Object.getOwnPropertySymbols(target).filter(function(symbol) {
     | ^
  55 | 			return Object.propertyIsEnumerable.call(target, symbol)
  56 | 		})
  57 | 		: []
 ⨯ node_modules/deepmerge/dist/cjs.js (54:1) @ getEnumerableOwnPropertySymbols
 ⨯ RangeError: Maximum call stack size exceeded
    at Array.filter (<anonymous>)
    at Array.forEach (<anonymous>)
......
```

Forgive me if my case is not related. I will create a new issue if needed.

**Comment by yobottehg** [comment] 2024-08-08 11:26
It is related

**Comment by yobottehg** [comment] 2024-08-08 13:34
I guess this is a Next.js problem in the later versions. For me it only affects the dev server. The prod build runs smooth.

**Comment by lctone** [comment] 2024-08-08 16:45
![Screenshot 2024-08-08 234141](https://github.com/user-attachments/assets/3b6da4c4-11d6-4413-8bf9-5802f2ad4bf5)

I'm not sure where the error comes from

**Comment by jomapps** [comment] 2024-08-09 21:33
I can second this issue. Happening to me.

**Comment by 58bits** [comment] 2024-08-10 08:53
Also seeing this...

**Comment by credli** [comment] 2024-08-10 15:55
.

**Comment by paulpopus** [comment] 2024-08-10 23:07
Hey all, we're going to take a look at this ASAP

**Comment by 58bits** [comment] 2024-08-11 02:40
Hi @paulpopus - thanks for the quick response. 

For interest, commenting out the email and nodemailerAdapter configuration also seems to prevent  `Maximum call stack size exceeded`  for us.

However, on the latest beta 77 and Next canary.104 ., I'm seeing another (possibly related?) problem. On production builds _only_ - i.e. `pnpm build && pnpm start` - the Payload admin app will not load if there is more than one collection with a richText field. 

For example - we created test Foo and Bar collections - based on the built-in Lexical richtext editor  and in each there are only two fields: title (text) and content as (richText).

For and Bar collections each have the following richtext field definition:

```
 {
      type: 'richText',
      name: 'richText',
      label: 'RichText',
      required: true,
    },
```

We can compile and load the admin dashboard if we load just the Foo collection or just the Bar collection - but not both. We can only load both along with the admin dashboard in development. :-(

In a production build - the request for the /admin URL remains stuck at 'pending'.

If this is totally unrelated to this issue, I'll go ahead and raise a separate issue with a demo repo.

**Comment by 58bits** [comment] 2024-08-11 03:11
@paulpopus @denolfe  - here's a forked Demo 3 repo with the admin dashboard problem above: 

https://github.com/infonomic/payload-3.0-demo

`pnpm install && pnpm build && pnpm start` - should reproduce the problem. All that's changed is another collection with a richText field was added to the `payload.config.ts`

**Comment by remarcable** [comment] 2024-08-11 08:19
@58bits you might be referring to this bug: https://github.com/payloadcms/payload/issues/7578

**Comment by 58bits** [comment] 2024-08-11 08:26
@remarcable - thanks -  I've just looked at https://github.com/payloadcms/payload/issues/7578 - and their description is similar - but in the reproducible repo above richtext does not have to appear in a block although I'll post my comment above and link there.

**Comment by yobottehg** [comment] 2024-08-12 18:09
Any update on this? Any hint on how to mitigate this without sacrificing the ability to send emails would be greatly appreciated.

**Comment by jmikrut** [comment] 2024-08-12 19:18
Actively looking into this now!

**Comment by jmikrut** [comment] 2024-08-12 20:51
This is now fixed and will be released shortly. Thank you everyone!

The Lexical / Rich Text issues are going to be addressed separately via https://github.com/payloadcms/payload/pull/7620.

That should hopefully be merged tomorrow!

**Closed by jmikrut** 2024-08-12 20:51 UTC
Labels: status: verified, v3, prioritized

**Comment by denolfe** [comment] 2024-08-13 13:28
Released in https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.78
