### ISSUE TITLE
Wrong direction in textarea on localized rtl text

### ISSUE THREAD

**Issue by hfkhrni** [payloadcms/payload#8473] opened 2024-09-29 17:15 UTC
### Environment Info

```text
Binaries:
  Node: 22.8.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: 9.10.0
Relevant Packages:
  payload: 3.0.0-beta.109
  next: 15.0.0-canary.160
  @payloadcms/db-mongodb: 3.0.0-beta.109
  @payloadcms/email-nodemailer: 3.0.0-beta.109
  @payloadcms/graphql: 3.0.0-beta.109
  @payloadcms/next/utilities: 3.0.0-beta.109
  @payloadcms/plugin-cloud: 3.0.0-beta.109
  @payloadcms/plugin-cloud-storage: 3.0.0-beta.109
  @payloadcms/richtext-lexical: 3.0.0-beta.109
  @payloadcms/storage-s3: 3.0.0-beta.109
  @payloadcms/translations: 3.0.0-beta.109
  @payloadcms/ui/shared: 3.0.0-beta.109
  react: 19.0.0-rc-5dcb0097-20240918
  react-dom: 19.0.0-rc-5dcb0097-20240918
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Thu Sep 12 18:26:09 UTC 2024
  Available memory (MB): 23695
  Available CPU cores: 12
```

### Describe the Bug

Wrong direction in textarea on localized rtl text, screenshot attached shows the difference between text and textarea, it should be like textarea
![Screenshot from 2024-09-29 16-40-02](https://github.com/user-attachments/assets/c294df90-8f80-46f6-a886-9c896acba1c1)

### Reproduction Steps

same beta version in env info, put a textarea field in a collection then write inside it in an rtl language

**Comment by paulpopus** [comment] 2024-09-29 18:45
I tested with arrays, blocks and normal fields and I can't reproduce this. Can you share your problematic config please?

![image](https://github.com/user-attachments/assets/b2471670-5998-4f68-81d8-4d3647502b3e)

**Comment by hfkhrni** [comment] 2024-09-29 18:50
my payload UI is in english, the problem is when you write inside the text area in arabic

`collection.ts`
```
{
      name: 'layout',
      labels: {
        singular: 'block',
        plural: 'blocks',
      },
      type: 'blocks',
      blocks: [Paragraph, Heading],
    } 
```
`parapgraph.ts`
```
import { Block } from 'payload'

export const Paragraph: Block = {
  slug: 'paragraph',
  fields: [
    {
      name: 'paragraph',
      type: 'textarea',
      localized: true,
    },
  ],
}
```
`heading.ts`
```
import { Block } from 'payload'

export const Heading: Block = {
  slug: 'heading',
  fields: [
    {
      name: 'heading',
      type: 'text',
      localized: true,
    },
  ],
}
```

text is working correctly and textarea is not

here's Arabic text you can test with

> يولد جميع الناس أحرارًا متساوين في الكرامة والحقوق. وقد وهبوا عقلاً وضميرًا وعليهم أن يعامل بعضهم بعضًا بروح الإخاء.

> كل الناس سواسية أمام القانون ولهم الحق في التمتع بحماية متكافئة عنه دون أية تفرقة، كما أن لهم جميعاً الحق في حماية متساوية ضد أي تمييز يُخل بهذا الإعلان وضد أي تحريض على تمييز كهذا.

**Comment by hfkhrni** [comment] 2024-09-29 18:51
sorry, closed the issue by mistake

**Comment by paulpopus** [comment] 2024-09-29 19:10
Thanks this will be fixed in https://github.com/payloadcms/payload/pull/8474

**Closed by paulpopus** 2024-09-29 19:10 UTC
Labels: status: needs-triage, v3
