### ISSUE TITLE
richtext-lexical: Custom components calling external API in blocks causes page to hang

### ISSUE THREAD

**Issue by denvoros** [payloadcms/payload#4261] opened 2023-11-24 17:38 UTC
### Describe the Bug

I'm trying to write my own blocks to be used in the Lexical editor. In particular, my blocks need to call an external API to get custom options for my editors. To try and incorporate this, I followed the example in the published YouTube video by the Payload team here:

<https://www.youtube.com/watch?v=Efn9OxSjA6Y>
(code here: <https://github.com/JessChowdhury/custom-select/>)

I then built a simple custom block that used the `CustomSelectField` code provided and added it to a custom block and then made the Lexical rich-text field aware of the block. When trying to add this block to a test page, my browser (Firefox) sits and hangs and the page cannot be interacted with.

After letting Firefox run for a while, it eventually tells me the page is slowing down my browser and lets me step through the code. When I do so I see the following message in the terminal:

 `Uncaught Error: Should not already be working.`

After pressing Play again, it finishes rendering after a minute with the custom select options. I'm certainly not proficient enough with React or Lexical to really understand what's going on, but my cursory look tells me it is some sort of circular dependency when it tries to render the block UI and the CustomSelect together. The block works fine outside the Lexical editor.

I appreciate any advice on getting this to work, or if this is truly a bug that my report helps to make the editor even better. Thanks for this excellent plugin, loving using Lexical otherwise!

### To Reproduce

Use the code provided by the Payload team in my description, and add a Lexical rich-text field that adds in a custom block that includes the custom select. Then, with the app running, try to add one of those blocks while in the editor (via slash command) in the admin panel.

### Payload Version

2.2.1

### Adapters and Plugins

db-mongodb, bundler-webpack, richtext-lexical

**Comment by AlessioGr** [comment] 2023-11-25 09:19
Hey @denvoros 

can you check if this bug only happens in Firefox, or if it happens in Chrome as well?

**Comment by denvoros** [comment] 2023-11-25 15:10
Just tried it in Chrome, and the same thing is happening. Eventually Chrome says that the page is taking too long and gives me the option to wait or to exit.

**Comment by AlessioGr** [comment] 2023-11-30 11:04
https://github.com/payloadcms/payload/assets/70709113/4c2bf63b-8d84-46b7-b1d5-e92c8a01b696

Sadly I'm not able to reproduce this - it works for me. Could you attach a reproduction to your issue? You can find a reproduction guide [here](https://github.com/payloadcms/payload/blob/main/.github/reproduction-guide.md) :)

**Comment by AlessioGr** [comment] 2023-12-17 20:58
Closing this for now due to missing reproduction, feel free to re-open this issue if you have one, though!

**Closed by AlessioGr** 2023-12-17 20:58 UTC
Labels: cant-reproduce, missing-reproduction, plugin: richtext-lexical
