### ISSUE TITLE
Data in Array does not get saved

### ISSUE THREAD

**Issue by jacobhytter** [payloadcms/payload#7747] opened 2024-08-18 18:44 UTC
### Payload Version

3.0.0-beta.73

### Node Version

v22.5.1

### Next.js Version

15.0.0-canary.77

### Describe the Bug

When im saveing rows in an array, the rows get saved but the data inside it is not. 
```
  {
    name: 'buttons',
    type: 'array',
    label: 'Call to action',
    fields: [
      {
        type: 'row',
        fields: [
          { name: 'label', type: 'text', localized: true },
          { name: 'url', type: 'text', localized: true },
        ],
      },
    ],
  },
```

I have this code in a seperated const, so i can use it in 3 places. What i have notice is that in the first name: 'subscriber', all works fine, but the other 2 will not save the data. 

```
const GroupField: Field[] = [
  { name: 'title', type: 'text', localized: true },
  { name: 'headline', type: 'text', localized: true },
  { name: 'text', type: 'textarea', localized: true },
  {
    name: 'textColor',
    type: 'select',
    options: [
      { label: 'White', value: 'white' },
      { label: 'Black', value: 'black' },
    ],
    defaultValue: 'white',
  },
  BackgroundColorField,
  {
    name: 'buttons',
    type: 'array',
    label: 'Call to action',
    fields: [
      {
        type: 'row',
        fields: [
          { name: 'label', type: 'text', localized: true },
          { name: 'url', type: 'text', localized: true },
        ],
      },
    ],
  },
];

export const BannerCollection: CollectionConfig = {
  slug: 'banner',
  admin: {
    useAsTitle: 'name',
    group: 'Call To Actions',
  },
  access: {
    delete: () => true,
    create: () => true,
    read: () => true,
    update: () => true,
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
    },
    {
      name: 'subscriber',
      type: 'group',
      fields: GroupField,
    },
    {
      name: 'freeTrial',
      type: 'group',
      fields: GroupField,
    },
    {
      name: 'nonSubscriber',
      type: 'group',
      fields: GroupField,
    },
  ],
};
```
Before Save:
![image](https://github.com/user-attachments/assets/1d329e54-c4a3-44a1-98b2-77dbb1afa466)

After Save:
![image](https://github.com/user-attachments/assets/63a5510a-6e1b-4283-b800-e219b990fa14)

I know this is just beta, and there will be bugs, but just wanted to know if this is known or I should start remove things in my project to see if something hinder the save. 

ps. I have not problem with other arrays in other places. And i have tried change name, delete and create again. remove the extra component and have all the code duplicated 3 times. No change. 

### Reproduction Steps

.

**Comment by paulpopus** [comment] 2024-08-20 17:43
Hey @jacobhytter I'm not able to reproduce this at all on the latest beta. Could you update and make sure you've pinned your next and react versions

```
"next": "15.0.0-canary.104",
"react": "19.0.0-rc-06d0b89e-20240801",
"react-dom": "19.0.0-rc-06d0b89e-20240801",
```

Or if you can provide a reproduction repo, I'd be happy to take a look! Closing this for now but I'll reopen with a reproduction

**Closed by paulpopus** 2024-08-20 17:43 UTC
Labels: v3
