### ISSUE TITLE
Records duplication when apply sort query param in url

### ISSUE THREAD

**Issue by Emadkhanqai** [payloadcms/payload#3209] opened 2023-08-22 13:26 UTC
### Link to reproduction

https://github.com/payloadcms/payload/fork

### To Reproduce

https://github.com/payloadcms/payload/fork

### Describe the Bug

I have a query which I use to get all projects from my payload, basically its a real estate website payload data, now there are many projects which are marked as featured inside mongodb, now I want to sort them first then show other projects, but when I apply the query param it duplicates few projects on every page.

Please help

### Payload Version

1.0.14

**Comment by AlessioGr** [comment] 2023-08-22 18:39
Hey @Emadkhanqai 

Could you include a reproduction of the issue, and make sure it's on the latest payload version?

**Comment by DanRibbens** [comment] 2023-08-28 13:59
You might want to try updating to the latest version of Payload and verify that you don't have duplicate documents in your database.

I'm going to close this for now, feel free to reopen when you have reproduction steps for us to try.

Thanks!

**Closed by DanRibbens** 2023-08-28 13:59 UTC
Labels: possible-bug, missing-reproduction

**Comment by edwardbc** [comment] 2023-09-18 03:08
@DanRibbens I think I know how duplicates can happen.

Example:
- Events collection, sorted by `startDate` 

In a scenario where you have several events happening on the same time (let's say some saturday 8pm), and using a limit of 10, I notice duplicates on items 10 and 11 or 20 and 21 and so on. 

I'm assuming this happens because the sorting algorithm is not enough in such case. I'm trying to replicate but I can see it happen on production, not in local yet.

In such case, a proper solution would be supporting multiple fields for sorting (startDate and name in this case). 

While this is solved, a sub-optimal solution is creating a composite sorting field to avoid duplication and ensure sort orders are always the same, but wouldn't provide a secondary sort criteria.
