### ISSUE TITLE
Can't use nested `group` field in `defaultColumns`

### ISSUE THREAD

**Issue by DrJume** [payloadcms/payload#1818] opened 2023-01-06 20:22 UTC
# Bug Report

When using a `group` field in a collection to combine multiple fields, it is not possible to use one of the group fields in `admin.defaultColumns`. Only the group itself, which doesn't have a value.

## Steps to Reproduce

1. Create a collection
2. Add a field of type `group` with name `group`.
3. Add a field of type `text` with name `group_text` to the group `group`.
4. Add `group_text` to `admin.defaultColumns`.
5. It is not shown shown in the overview of the collection. (One level above editor)
6. When adding `group` to `admin.defaultColumns`, a JSON string of the group is shown as the value.

## Other Details

Payload version: `v1.5.4`

---
### Possible cause

`admin.defaultColumns` are passed to `buildColumns`:
https://github.com/payloadcms/payload/blob/a823e75d2bb7ef07e39e3053d192e6414d2da3ec/src/admin/components/elements/ListDrawer/DrawerContent.tsx#L96-L103

Before matching the fields, the collection fields are flattened:
https://github.com/payloadcms/payload/blob/a823e75d2bb7ef07e39e3053d192e6414d2da3ec/src/admin/components/views/collections/List/buildColumns.tsx#L22-L23

To be then matched/searched by:
https://github.com/payloadcms/payload/blob/a823e75d2bb7ef07e39e3053d192e6414d2da3ec/src/admin/components/views/collections/List/buildColumns.tsx#L41-L48

The Problem seems to be in `flattenFields()`. The fields inside group should be flattened in:
https://github.com/payloadcms/payload/blob/a823e75d2bb7ef07e39e3053d192e6414d2da3ec/src/utilities/flattenTopLevelFields.ts#L20-L25

But the for the given group the code is not reached, because it is caught in the condition above, which does not recurse into the nested fields:
https://github.com/payloadcms/payload/blob/a823e75d2bb7ef07e39e3053d192e6414d2da3ec/src/utilities/flattenTopLevelFields.ts#L13-L18

The question is, if this behaviour is expected or not. The flattening could lead to a collision of field names. E.g a field with name `text` inside `group` and a top level field also called `text`. A solution could be namespacing of the field names: 
```ts
admin: { 
    defaultColumns: ['group.text', 'text']
}
```

**Comment by jacobsfletch** [comment] 2023-01-09 13:36
@DrJume your last comment is spot on, we'd likely just support dot notation in `defaultColumns`. This is a feature and not a bug. A challenging aspect to this would be the UI — we wouldn't want to outright display every field of every group because this would get unwieldy for complex collections. We currently only show top-level fields partly for this reason.

**Comment by DavidOliver** [comment] 2023-01-09 14:14
Related: https://github.com/payloadcms/payload/discussions/1617

**Comment by jmikrut** [comment] 2023-01-09 14:40
Yep. I think this is a duplicate of #1617 so I'm going to close this and defer conversation there instead. I've added it to the roadmap so it will happen eventually for sure. In the meantime there are some workarounds available to you to look at in that thread!

**Closed by jmikrut** 2023-01-09 14:40 UTC
Labels: possible-bug
