### ISSUE TITLE
Locale: Fallback not working

### ISSUE THREAD

**Issue by mikkelwf** [payloadcms/payload#9060] opened 2024-11-07 10:14 UTC
### Describe the Bug

The `fallback: false` under localization in payload doesn't work.

The local api always returns/defaults to data from the `defaultLocale`. When `fallback: false` is set its expected that querying doesn't provide fallback data.

Force setting `fallbackLocale` to `false` or `'none'` allows you to perform the query without getting fallback data, but the `fallbackLocale` type doesn't allow these values.

### Link to the code that reproduces this issue

https://github.com/re-cph/payload/tree/bug/local_api_locale_fallback

### Reproduction Steps

Run tests

### Which area(s) are affected? (Select all that apply)

area: core, db-mongodb, db-postgres

### Environment Info

Payload: beta 126
Nodejs: 20.10.0
nextjs: 15.0.1

**Comment by paulpopus** [comment] 2024-11-08 16:14
Closing as duplicate of https://github.com/payloadcms/payload/issues/8443 
We have a fix in progress here: https://github.com/payloadcms/payload/pull/8591

**Closed by paulpopus** 2024-11-08 16:14 UTC
Labels: status: needs-triage, v3
