### ISSUE TITLE
Add new from Join Field does not honor default or conditions

### ISSUE THREAD

**Issue by nathanclevenger** [payloadcms/payload#9081] opened 2024-11-08 07:49 UTC
### Describe the Bug

Add new from Join Field:
![Image](https://github.com/user-attachments/assets/cc449e1a-2ea6-4034-920b-c05aa54eb0ca)

Create new from Collection:
![Image](https://github.com/user-attachments/assets/0eb7b4b8-4bed-4dce-82e8-90ee74a5ab10)

```typescript
export const Resources: CollectionConfig = {
  slug: 'resources',
  fields: [
    { name: 'id', type: 'text', required: true },
    { type: 'row', fields: [
      { name: 'type', type: 'select', options: ['data', 'content'], required: true, defaultValue: 'data' },
      { name: 'dataset', type: 'relationship', relationTo: 'datasets', required: true },
    ]},
    { name: 'markdown', type: 'code', admin: { language: 'markdown', condition: data => data.type === 'content' } },
    { name: 'data', type: 'json', required: true },
  ],
}
```

### Link to the code that reproduces this issue

https://github.com/nathanclevenger/payload-repro/blob/main/collections/Resources.ts

### Reproduction Steps

In this example, select `Add new` for Resources from within a detail view of an item in the `Datasets` collection, and the default and condition behavior is not honored, like it is if you create a new Resource directly from the Collection Create New

### Which area(s) are affected? (Select all that apply)

area: ui

### Environment Info

Payload: 3.0.0-beta.126
Node: v20.13.1
Next: 15.0.0

**Comment by akhrarovsaid** [comment] 2024-11-08 13:51
Hey @nathanclevenger I believe this is a possible duplicate of #8612

**Comment by nathanclevenger** [comment] 2024-11-08 17:08
ahh @akhrarovsaid I didn't see the other ticket in my search because I initially noticed that `condition` wasn't honored, and then I noticed `default` wasn't working either when I was making the repro ... does the PR to fix #8612 also fix `condition`?

**Comment by akhrarovsaid** [comment] 2024-11-15 21:05
Hey @nathanclevenger,

I'm not able to reproduce either the default values not populating, nor the `condition` issue as of `beta.128`. Want to try updating your Payload versions and seeing if you're still experiencing this issue?

**Comment by jacobsfletch** [comment] 2024-11-22 18:29
Same. Thanks for confirming @akhrarovsaid.

**Closed by jacobsfletch** 2024-11-22 18:29 UTC
Labels: created-by: Contributor
