### ISSUE TITLE
Nested relation field automatically paginated

### ISSUE THREAD

**Issue by sibergenome** [payloadcms/payload#2885] opened 2023-06-22 07:20 UTC
### Link to reproduction

https://payloadcms.com/docs/queries/pagination

### To Reproduce

I have 2 collections: Lineups and Artists. A Lineup has many artists through a relationship. Here are the collections (simplified):

```ts
const Lineups: CollectionConfig = {
  slug: 'lineups',
  access: {
    ...
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
      unique: true,
    },
    {
      name: 'artists',
      type: 'relationship',
      relationTo: 'artistprofiles',
      hasMany: true,
    }
};
```

```ts
const ArtistProfiles: CollectionConfig = {
  slug: 'artistprofiles',
  admin: {
    useAsTitle: 'name',
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
      unique: true,
      maxLength: 50,
    }
  ],
};
```

### Describe the Bug

Querying lineups with GET `http://localhost:3000/api/lineups/{lineup_id}?depth=3` returns:

```json
{
    "id": "0",
    "artists": [
        "1",
        {+ 9 more IDs...}
    ],
    "createdAt": "2023-06-19T08:29:08.340Z",
    "updatedAt": "2023-06-19T08:29:08.340Z"
}
```

I am not able to query any more than 10 artists within a lineup, and am unable to paginate them either. How can I specify the limit on the number of sub-fields here?

I get the same behaviour through the local API also.

Is this intended behaviour? Or is there a feature I'm missing that enables me to control the limit on nested fields?

Linked reproduction to pagination docs, as that's where I think there should be some info on this.

Issue on discord: https://discord.com/channels/967097582721572934/1120267399778795581/1120267399778795581

### Payload Version

1.7.1

**Comment by JessChowdhury** [comment] 2023-06-26 15:48
Hi @sibergenome - I booted up a fresh project from `npx create-payload-app` and matched your Payload version `1.7.1`, then I added a lineup collection with a relationship (hasMany: true) to another artists collection. However, I am not getting the same behavior - my queries are returning _all_ artists and not getting limited to 10.

Are you able to reproduce this issue in a basic project? If yes, please share a minimal reproduction so we can dig into this further.

**Comment by sibergenome** [comment] 2023-06-28 03:22
Will do when I've got a moment, thanks heaps.

**Comment by JessChowdhury** [comment] 2023-07-24 11:10
Hey @sibergenome, since this issue hasn't had any activity in the last month we are going to close it. If you are able to reproduce this issue, absolutely feel free to reopen this 👍

**Closed by JessChowdhury** 2023-07-24 11:10 UTC
Labels: possible-bug, cant-reproduce
