### ISSUE TITLE
Cannot use link component inside rich text field

### ISSUE THREAD

**Issue by itsaalexk** [payloadcms/payload#8850] opened 2024-10-24 08:45 UTC
### Describe the Bug

Link button not working in rich text component with SlateEditor.

We are trying to use link component in rich text field but it does not open when I click on it.

Instead this error is displayed on the console and nothing else happens. We recently updated to the "payload": "^2.30.3", version  and also updated this postgres plugin to the following version. "@payloadcms/db-postgres": "^0.8.9",

When I click the link component in RichText field I expect to open a modal but instead I get this error on the console.
I have noticed that you are using this library to open such modal @faceless-ui/modal

We are also using this adapter , but it seems to be updated to the latest version @payloadcms/richtext-slate

THIS IS THE ERROR MESSAGE IM GETTING:
![Image](https://github.com/user-attachments/assets/dc3db70d-e654-4816-b608-5b4629a792c2)

### To Reproduce

Just try to open the link component on RichText field with the latest version and nothing will happen.

Instead i get this error on the console 

![Image](https://github.com/user-attachments/assets/15468591-c00c-4bd2-9f10-ec66744a0f22)

### Payload Version

^2.30.3

### Adapters and Plugins

@payloadcms/db-postgres @payloadcms/richtext-slate

**Comment by antonnystedt** [comment] 2024-10-25 20:31
+1, also seing this issue with v2.30.3

**Comment by marcmaceira** [comment] 2024-10-27 16:11
This issue is a duplicate of #8576. Make sure to follow it and check out the recommended workaround.

**Closed** 2024-10-28 19:03 UTC
Labels: status: needs-triage, v2
