### ISSUE TITLE
generate:types fails when richText fields don't have editor set explicitly

### ISSUE THREAD

**Issue by carstenblt** [payloadcms/payload#5050] opened 2024-02-11 14:33 UTC
### Describe the Bug

When `editor` is only set in payload.config, generate:types fails with

```
node_modules/payload/dist/utilities/configToJSONSchema.js:154
                        if (field.editor.outputSchema) {
                                         ^

TypeError: Cannot read properties of undefined (reading 'outputSchema')
```

When editor is set in all richText fields, it succeeds.

### To Reproduce

Set `editor` in `payload.config`. Add `richText` field without `editor`.

### Payload Version

2.11.0

**Comment by revnelson** [comment] 2024-02-15 20:22
Getting this with richtext-lexical v0.6.0 and v0.6.1. Reverting to v0.5.2 (event with payload v2.11.0) allows types to be generated without crashing.

**Comment by AlessioGr** [comment] 2024-02-15 22:04
I wasn't able to reproduce this. I'll look into this again once a minimal reproduction repository has been added!

**Comment by carstenblt** [comment] 2024-02-16 18:37
I'll try to do this Monday!

**Comment by carstenblt** [comment] 2024-02-19 12:09
Ah, indeed it works in richText fields. But it fails in Blocks that are included in a lexicalEditor.

```
export const TestBlock: Block = {
  slug: 'Image',
  fields: [
    {
      name: 'text',
      type: 'richText',
    },
  ],
}
```

and

```
...
editor: lexicalEditor({
        features: ({ defaultFeatures }) => [
          ...defaultFeatures.filter((feature) => feature.key !== 'upload'),
          BlocksFeature({
            blocks: [TestBlock],
          }),
        ],
      })
...
```

Here is a reproduction:

https://github.com/carstenblt/payload/tree/reproduction-lexical-types

**Comment by tomperalta** [comment] 2024-03-06 20:10
Happening to me as well.

**Comment by BrianJM** [comment] 2024-03-07 01:25
I cannot reproduce this in `2.11.1` in my current project. None of the `richText` fields have an `editor` declaration, and types are generated regularly without error. I'm also using `features` and `blocks` defined in `payload.config.ts`.

**Comment by BrianJM** [comment] 2024-03-07 11:20
> See my reproduction

I missed that. For some reason, the comments didn't load except the most recent. I see the reproduction now, thanks!

**Comment by linobino1** [comment] 2024-03-19 14:01
I can reproduce this using `"payload": "^2.11.2"` and `"@payloadcms/richtext-lexical": "^0.7.0"`

**Comment by AlessioGr** [comment] 2024-04-05 19:55
Looks like this has been fixed now, so I'll be closing this!

@carstenblt I pulled down your repo and tested it out - the issue does appear there! However, if I merge in all the latest changes from upstream, that fixed it. The issue must have been fixed somewhere down the line.

If this does happen again on richtext-lexical 0.8.0 and payload 12.2.1 or any newer version, I'd appreciate if you can open up a fresh issue with a reproduction!

**Closed by AlessioGr** 2024-04-05 19:55 UTC
Labels: [possible-bug], plugin: richtext-lexical
