### ISSUE TITLE
`plugin-seo` does not respect basePath config in NextJS for generation (potentially all `endpoint` paths)

### ISSUE THREAD

**Issue by neverether** [payloadcms/payload#7825] opened 2024-08-23 01:53 UTC
### Payload Version

3.0.0-beta.90

### Node Version

20

### Next.js Version

15.0.0-canary.120

### Describe the Bug

While using `plugin-seo`'s generate* functions, the endpoint path is set to `/api/plugin-seo/generate-*`

When using a basePath configuration this will 404 or in my case, hit the wrong application.

### Reproduction Steps

1. App Setup as a multi-zone app (in my case a monorepo):
- Main Client App (localhost:3000)
- Payload App w/basePath `/blog` (localhost:3001/blog) 
2. Enable plugin-seo and configure generateTItle
3. When clicking Generate Title:
```bash
blog:dev:  POST /api/payload-preferences/collection-blog-posts-66c742481f4097f096b85aba 200 in 113ms
client:dev:  POST /api/plugin-seo/generate-title 404 in 28ms
```
The endpoint is requesting localhost:3000/api/... and hits the wrong client
4. As a workaround, adding a rewrite to the client app to add the basePath manually, but this may not be an option depending on the users' situations:
```tsx
{
  source: "/api/plugin-seo/:path*",
  destination: `${blogHost}/api/plugin-seo/:path*`,
},
```
will then correctly hit the endpoint
```bash
blog:dev:  POST /api/payload-preferences/collection-blog-posts-66c742481f4097f096b85aba 200 in 33ms
blog:dev:  POST /api/plugin-seo/generate-title 200 in 20ms
```

Note: I looked at the code https://github.com/payloadcms/payload/blob/9de3ffdcfe8cda147616e29e0c86d067e9650dec/packages/plugin-seo/src/index.tsx#L132-L148 and based on the configuration, there may be a larger issue here where `endpoint` configs all don't respect basePath. I don't have any experience with the endpoint feature yet so I can't confirm this is the case.

### Adapters and Plugins

plugin-seo

**Comment by paulpopus** [comment] 2024-08-26 20:09
From first impressions it doesn't seem like a plugin issue here. If you want the `api` to be served from another route you need to configure this in Payload https://payloadcms.com/docs/beta/admin/overview#root-level-routes

Note that the admin panel should also not work as it will also try to hit `/api` in this case without configuring the above

If you can provide a bit more information about your setup or a reproduction repo I can give you better feedback

**Comment by neverether** [comment] 2024-08-27 04:12
@paulpopus Thanks for your message

> Note that the admin panel should also not work as it will also try to hit /api in this case without configuring the above

I don't believe this is true, the admin panel handles the basePath after the changes in this PR https://github.com/payloadcms/payload/pull/6628 additionally, the `formatAdminURL` utility seems to handle it https://github.com/payloadcms/payload/blob/ea48cfbfe9acabaf75c7adb008ce15f8103744a1/packages/ui/src/utilities/formatAdminURL.ts#L4

If you still need a repro it'll take a moment but I might be able to provide one next week.

**Comment by paulpopus** [comment] 2024-08-27 04:21
I moved this to discussion because it wouldn't make sense to me that the plugin's endpoints wouldnt be hooked up to the same route as the rest of the API.

But im totally happy to jump back in and take a look if you provide a repo whenever you can 👍

**Comment by grzegorzbialy** [comment] 2024-09-09 09:37
I second @neverether and think that plugin should use configured basePath. Right now it needs to be forked or copied locally to add support for this. I think if it uses NextJS it should respect that option.

**Comment by l-you** [comment] 2024-09-18 07:14
Same here. Plugin should respect the basePath like any other plugin.

**Comment by paulpopus** [comment] 2024-10-03 23:34
I think I misunderstood the original issue. This is going to be fixed in https://github.com/payloadcms/payload/pull/8546

Let me know if you encounter any further issues after this is merged as it will be using serverURL and the `api` route as configured in Payload.

**Closed by paulpopus** 2024-10-03 23:34 UTC
Labels: status: verified, v3
