### ISSUE TITLE
locale=all was not iterating through relationship field

### ISSUE THREAD

**Issue by horsehcj** [payloadcms/payload#3269] opened 2023-09-04 15:36 UTC
### Link to reproduction

https://p01--demo--qx6bfsv879s8.code.run/api/examples/64a7927d09f1787bbf64b90c?locale=all

### To Reproduce

Similar to #2980 , it affects the relationship field as well

https://p01--demo--qx6bfsv879s8.code.run/api/examples/64a7927d09f1787bbf64b90c?locale=all

<img width="689" alt="Screenshot 2023-09-04 at 11 33 06 PM" src="https://github.com/payloadcms/payload/assets/2873831/644c0177-9227-4ba2-a8dc-a2470f4d0510">

### Describe the Bug

The arrayField was fixed in #2980, however the relationshipField is still showing the id only instead of the object

```
fields: [
    ...,
    {
      name: "relationshipField",
      label: "Relationship Field",
      type: "relationship",
      relationTo: "cities",
      hasMany: true,
    },
]
```

### Payload Version

1.15.2

**Comment by JessChowdhury** [comment] 2023-09-11 08:50
Hi @horsehcj - I pulled down your reproduction from [here](https://github.com/horsehcj/Payload-issue-demo). Initially I get the same result as you - an array of IDs. 

However, the `relationshipField` in question seems to be missing `localized: true`. Once I add this, I can see it's returning the full object. Try updating the field on your end, then check out the data again - let me know how that goes!

**Comment by JessChowdhury** [comment] 2023-09-18 09:07
@horsehcj I'm going to close this issue - if you're still experiencing this after adding `localized: true`, let me know and we can get this reopened.

**Closed by JessChowdhury** 2023-09-18 09:07 UTC
Labels: cant-reproduce

**Comment by horsehcj** [comment] 2023-09-22 02:41
hi @JessChowdhury , thank you for checking on this

Should the relationship field returning the full object even if it is not `localized: true`? 

I'm expecting the behaviour is controlled by `depth`, and in my case the relationship field doesn't need to be localised, let me know if it make sense to you, thank you

**Comment by JessChowdhury** [comment] 2023-09-22 10:28
Hey @horsehcj that is correct - if you don't need to localize your relationship field, you can increase the `depth` parameter to return the full data instead of just the ID. Is that working for you?

**Comment by horsehcj** [comment] 2023-09-22 12:26
@JessChowdhury no, it doesn't

even if I try
https://p01--demo--qx6bfsv879s8.code.run/api/examples/64a7927d09f1787bbf64b90c?locale=all&depth=10
