### ISSUE TITLE
Templates break upon next export

### ISSUE THREAD

**Issue by MarkKropf** [payloadcms/payload#4671] opened 2024-01-03 18:13 UTC
### Describe the Bug

A vanilla latest build with a template breaks the NEXT export upon ```pnpm build```

### Short Log
```bash
pnpm build

> deleteme@1.0.0 build /Volumes/PayloadCMS/deleteme
> cross-env NODE_ENV=production yarn build:payload && yarn build:server && yarn copyfiles && yarn build:next

yarn run v1.22.21
$ cross-env PAYLOAD_CONFIG_PATH=src/payload/payload.config.ts payload build
(node:17959) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[18:02:23] INFO (payload): Starting Payload...
✨  Done in 7.61s.
yarn run v1.22.21
$ tsc --project tsconfig.server.json
✨  Done in 1.62s.
yarn run v1.22.21
$ copyfiles -u 1 "src/**/*.{html,css,scss,ttf,woff,woff2,eot,svg,jpg,png,js}" dist/
✨  Done in 0.17s.
yarn run v1.22.21
$ cross-env PAYLOAD_CONFIG_PATH=dist/payload/payload.config.js NEXT_BUILD=true node dist/server.js
(node:18005) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
   Creating an optimized production build ..[18:02:33] INFO (payload): Connected to MongoDB server successfully!
[18:02:33] INFO (payload): Starting Payload...
[18:02:33] INFO (payload): Payload Admin URL: http://localhost:3000/admin
[18:02:33] INFO (payload): Next.js is now building...
   Creating an optimized production build ...webpack built 3f5b282b8e2edbed0ba6 in 8300ms
webpack compiled successfully
 ✓ Creating an optimized production build
 ✓ Compiled successfully
   Linting and checking validity of types ...<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: No serializer registered for ConcatSource
<w> while serializing webpack/lib/util/registerExternalSerializer.webpack-sources/ConcatSource -> Array { 2 items } -> ConcatSource
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (0/19) [    ] ⨯ TypeError: Cannot read properties of null (reading 'useContext')
    at y (/Volumes/PayloadCMS/deleteme/.next/server/chunks/7591.js:1:20916)
    at c (/Volumes/PayloadCMS/deleteme/.next/server/chunks/7591.js:1:12153)
 ⨯ TypeError: Cannot read properties of null (reading 'useContext')
    at y (/Volumes/PayloadCMS/deleteme/.next/server/chunks/7591.js:1:20916)
    at c (/Volumes/PayloadCMS/deleteme/.next/server/chunks/7591.js:1:12153)
 ⨯ TypeError: Cannot read properties of null (reading 'useContext')
    at y (/Volumes/PayloadCMS/deleteme/.next/server/chunks/7591.js:1:20916)
    at c (/Volumes/PayloadCMS/deleteme/.next/server/chunks/7591.js:1:12153)
TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/Volumes/PayloadCMS/deleteme/node_modules/.pnpm/next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:1:228040)
    at y (/Volumes/PayloadCMS/deleteme/.next/server/chunks/7591.js:1:20916)
    at c (/Volumes/PayloadCMS/deleteme/.next/server/chunks/7591.js:1:12153)
    at Qi (/Volumes/PayloadCMS/deleteme/node_modules/.pnpm/next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:258120)
    at /Volumes/PayloadCMS/deleteme/node_modules/.pnpm/next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:262927
    at ps (/Volumes/PayloadCMS/deleteme/node_modules/.pnpm/next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:264682)
    at ys (/Volumes/PayloadCMS/deleteme/node_modules/.pnpm/next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:272177)
    at ms (/Volumes/PayloadCMS/deleteme/node_modules/.pnpm/next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:270395)
    at us (/Volumes/PayloadCMS/deleteme/node_modules/.pnpm/next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:259508)
    at /Volumes/PayloadCMS/deleteme/node_modules/.pnpm/next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:264658
```

### Full log
[payloadcms - pnpm build failure.log](https://github.com/payloadcms/payload/files/13822097/payloadcms.-.pnpm.build.failure.log)

## Broken Path
```bash
npx create-payload-app@latest -n deleteme -t website --use-pnpm
cd ./deleteme/
pnpm generate:types
pnpm build
```

### Payload Version

@latest

### Adapters and Plugins

db-mongodb, pnpm

**Comment by MarkKropf** [comment] 2024-01-03 18:15
###Impacted paths

```bash
✓ Generating static pages (19/19)
unhandledRejection ExportError: Export encountered errors on following paths:
	/(pages)/account/page: /account
	/(pages)/login/page: /login
	/(pages)/logout/page: /logout
	/(pages)/recover-password/page: /recover-password
	/(pages)/reset-password/page: /reset-password
	/(pages)/styleguide/buttons/page: /styleguide/buttons
	/(pages)/styleguide/call-to-action/page: /styleguide/call-to-action
	/(pages)/styleguide/content-block/page: /styleguide/content-block
	/(pages)/styleguide/media-block/page: /styleguide/media-block
	/(pages)/styleguide/message/page: /styleguide/message
	/(pages)/styleguide/page: /styleguide
	/(pages)/styleguide/typography/page: /styleguide/typography
	/_error: /404
	/_error: /500
	/_not-found
	/page: /
    at /Volumes/Supaku/deleteme/node_modules/.pnpm/next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/export/index.js:630:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/Volumes/Supaku/deleteme/node_modules/.pnpm/next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:105:20)
    at async /Volumes/Supaku/deleteme/node_modules/.pnpm/next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/index.js:1665:21
    at async Span.traceAsyncFn (/Volumes/Supaku/deleteme/node_modules/.pnpm/next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:105:20)
    at async /Volumes/Supaku/deleteme/node_modules/.pnpm/next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/index.js:1513:17
    at async Span.traceAsyncFn (/Volumes/Supaku/deleteme/node_modules/.pnpm/next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:105:20)
    at async build (/Volumes/Supaku/deleteme/node_modules/.pnpm/next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/index.js:185:29) {
  code: 'NEXT_EXPORT_ERROR'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by SimYunSup** [comment] 2024-01-04 06:02
To fix your error, you have to upload about operation environment.

To me, My computer doesn't reproduce it.

## Operation Env

```
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: 1.22.21
  pnpm: 8.10.5
```

<details>
  <summary>First Try Version</summary>
  
package.json
```json
{
  "dependencies": {
    "@payloadcms/bundler-webpack": "^1.0.0",
    "@payloadcms/db-mongodb": "^1.0.0",
    "@payloadcms/plugin-cloud": "^2.0.0",
    "@payloadcms/plugin-nested-docs": "^1.0.8",
    "@payloadcms/plugin-redirects": "^1.0.0",
    "@payloadcms/plugin-seo": "^1.0.10",
    "@payloadcms/richtext-slate": "^1.0.0",
    "cross-env": "^7.0.3",
    "dotenv": "^8.2.0",
    "escape-html": "^1.0.3",
    "express": "^4.17.1",
    "next": "13.5.2",
    "payload": "^2.0.0",
    "payload-admin-bar": "^1.0.6",
    "qs": "6.11.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "7.45.4",
    "react-router-dom": "5.3.4"
  },
  "devDependencies": {
    "@next/eslint-plugin-next": "^13.1.6",
    "@payloadcms/eslint-config": "^0.0.1",
    "@swc/core": "1.3.76",
    "@types/escape-html": "^1.0.2",
    "@types/express": "^4.17.9",
    "@types/node": "18.11.3",
    "@types/qs": "^6.9.8",
    "@types/react": "18.0.21",
    "@typescript-eslint/eslint-plugin": "^5.51.0",
    "@typescript-eslint/parser": "^5.51.0",
    "copyfiles": "^2.4.1",
    "eslint": "^8.19.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-plugin-filenames": "^1.3.2",
    "eslint-plugin-import": "2.25.4",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-simple-import-sort": "^10.0.0",
    "nodemon": "^2.0.6",
    "prettier": "^2.7.1",
    "slate": "0.91.4",
    "ts-node": "10.9.1",
    "typescript": "^4.8.4"
  },
  "resolutions": {
    "jackspeak": "2.1.1"
  }
}
```


```bash
pnpm run build

> test-for-payload-pnpm@1.0.0 build C:\Projects\test-for-payload-pnpm
> cross-env NODE_ENV=production yarn build:payload && yarn build:server && yarn copyfiles && yarn build:next

yarn run v1.22.21
$ cross-env PAYLOAD_CONFIG_PATH=src/payload/payload.config.ts payload build
[05:39:39] INFO (payload): Starting Payload...
Done in 26.18s.
yarn run v1.22.21
$ tsc --project tsconfig.server.json
Done in 2.95s.
yarn run v1.22.21
$ copyfiles -u 1 "src/**/*.{html,css,scss,ttf,woff,woff2,eot,svg,jpg,png,js}" dist/
Done in 0.51s.
yarn run v1.22.21
$ cross-env PAYLOAD_CONFIG_PATH=dist/payload/payload.config.js NEXT_BUILD=true node dist/server.js
[05:40:09] INFO (payload): Connected to MongoDB server successfully!
[05:40:09] INFO (payload): Starting Payload...
[05:40:10] INFO (payload): Payload Admin URL: http://localhost:3000/admin
[05:40:10] INFO (payload): Next.js is now building...
   Creating an optimized production build ..webpack built b2ca5d4e00ee74d792a4 in 21524ms
webpack compiled successfully
 ✓ Creating an optimized production build
 ✓ Compiled successfully
   Linting and checking validity of types .<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: No serializer registered for ConcatSource
<w> while serializing webpack/lib/util/registerExternalSerializer.webpack-sources/ConcatSource -> Array { 2 items } -> ConcatSource
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (7/19) [==  ]
 ✓ Generating static pages (19/19)
 ✓ Finalizing page optimization

Route (app)                              Size     First Load JS
┌ λ /                                    507 B           143 kB
├ λ /_not-found                          872 B          80.5 kB
├ ● /[slug]                              507 B           143 kB
├ λ /account                             3.68 kB        97.8 kB
├ λ /api/exit-preview                    0 B                0 B
├ λ /api/preview                         0 B                0 B
├ λ /api/revalidate                      0 B                0 B
├ λ /login                               3.19 kB        97.4 kB
├ λ /logout                              1.88 kB        88.2 kB
├ ● /posts/[slug]                        3.24 kB         146 kB
├ ● /projects/[slug]                     497 B           143 kB
├ λ /recover-password                    2.15 kB        96.3 kB
├ λ /reset-password                      2.62 kB        96.8 kB
├ λ /styleguide                          306 B          86.7 kB
├ λ /styleguide/buttons                  1.34 kB        87.7 kB
├ λ /styleguide/call-to-action           1.56 kB        87.9 kB
├ λ /styleguide/content-block            1.6 kB           88 kB
├ λ /styleguide/media-block              2.67 kB        94.2 kB
├ λ /styleguide/message                  405 B          86.8 kB
└ λ /styleguide/typography               306 B          86.7 kB
+ First Load JS shared by all            79.6 kB
  ├ chunks/1dd012d3-7dce37a0b516562f.js  50.9 kB
  ├ chunks/892-14cf70af990bffc9.js       26.5 kB
  ├ chunks/main-app-fbc33a3732902daa.js  221 B
  └ chunks/webpack-63996ba46be81b24.js   2.03 kB


λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)

Done in 47.23s.
```
</details>
<details>
  <summary>Second Try Version</summary>

package.json

```json
{
  "dependencies": {
    "@payloadcms/bundler-webpack": "^1.0.5",
    "@payloadcms/db-mongodb": "^1.2.0",
    "@payloadcms/plugin-cloud": "^2.2.6",
    "@payloadcms/plugin-nested-docs": "^1.0.10",
    "@payloadcms/plugin-redirects": "^1.0.1",
    "@payloadcms/plugin-seo": "^1.0.15",
    "@payloadcms/richtext-slate": "^1.3.1",
    "cross-env": "^7.0.3",
    "dotenv": "^8.2.0",
    "escape-html": "^1.0.3",
    "express": "^4.17.1",
    "next": "13.5.2",
    "payload": "^2.5.0",
    "payload-admin-bar": "^1.0.6",
    "qs": "6.11.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "7.45.4",
    "react-router-dom": "5.3.4"
  },
  "devDependencies": {
    "@next/eslint-plugin-next": "^13.1.6",
    "@payloadcms/eslint-config": "^0.0.1",
    "@swc/core": "1.3.76",
    "@types/escape-html": "^1.0.2",
    "@types/express": "^4.17.9",
    "@types/node": "18.11.3",
    "@types/qs": "^6.9.8",
    "@types/react": "18.0.21",
    "@typescript-eslint/eslint-plugin": "^5.51.0",
    "@typescript-eslint/parser": "^5.51.0",
    "copyfiles": "^2.4.1",
    "eslint": "^8.19.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-plugin-filenames": "^1.3.2",
    "eslint-plugin-import": "2.25.4",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-simple-import-sort": "^10.0.0",
    "nodemon": "^2.0.6",
    "prettier": "^2.7.1",
    "slate": "0.91.4",
    "ts-node": "10.9.1",
    "typescript": "^4.8.4"
  },
  "resolutions": {
    "jackspeak": "2.1.1"
  }
}
```

```sh
pnpm run build

> test-for-payload-pnpm@1.0.0 build C:\Projects\test-for-payload-pnpm
> cross-env NODE_ENV=production yarn build:payload && yarn build:server && yarn copyfiles && yarn build:next

yarn run v1.22.21
$ cross-env PAYLOAD_CONFIG_PATH=src/payload/payload.config.ts payload build
[05:52:03] INFO (payload): Starting Payload...
Done in 24.12s.
yarn run v1.22.21
$ tsc --project tsconfig.server.json
Done in 4.23s.
yarn run v1.22.21
$ copyfiles -u 1 "src/**/*.{html,css,scss,ttf,woff,woff2,eot,svg,jpg,png,js}" dist/
Done in 0.49s.
yarn run v1.22.21
$ cross-env PAYLOAD_CONFIG_PATH=dist/payload/payload.config.js NEXT_BUILD=true node dist/server.js
[05:52:34] INFO (payload): Connected to MongoDB server successfully!
[05:52:34] INFO (payload): Starting Payload...
[05:52:35] INFO (payload): Payload Admin URL: http://localhost:3000/admin
[05:52:35] INFO (payload): Next.js is now building...
   Creating an optimized production build ..webpack built b2ca5d4e00ee74d792a4 in 23216ms
webpack compiled successfully
 ✓ Creating an optimized production build
 ✓ Compiled successfully
   Linting and checking validity of types ...<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: No serializer registered for ConcatSource
<w> while serializing webpack/lib/util/registerExternalSerializer.webpack-sources/ConcatSource -> Array { 2 items } -> ConcatSource
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (2/19) [=   ]
 ✓ Generating static pages (19/19)
 ✓ Finalizing page optimization

Route (app)                              Size     First Load JS
┌ λ /                                    508 B           143 kB
├ λ /_not-found                          872 B          80.5 kB
├ ● /[slug]                              508 B           143 kB
├ λ /account                             3.68 kB        97.8 kB
├ λ /api/exit-preview                    0 B                0 B
├ λ /api/preview                         0 B                0 B
├ λ /api/revalidate                      0 B                0 B
├ λ /login                               3.19 kB        97.4 kB
├ λ /logout                              1.88 kB        88.2 kB
├ ● /posts/[slug]                        3.24 kB         146 kB
├ ● /projects/[slug]                     498 B           143 kB
├ λ /recover-password                    2.15 kB        96.3 kB
├ λ /reset-password                      2.62 kB        96.8 kB
├ λ /styleguide                          306 B          86.7 kB
├ λ /styleguide/buttons                  1.34 kB        87.7 kB
├ λ /styleguide/call-to-action           1.56 kB        87.9 kB
├ λ /styleguide/content-block            1.6 kB           88 kB
├ λ /styleguide/media-block              2.66 kB        94.2 kB
├ λ /styleguide/message                  405 B          86.8 kB
└ λ /styleguide/typography               306 B          86.7 kB
+ First Load JS shared by all            79.6 kB
  ├ chunks/1dd012d3-7dce37a0b516562f.js  50.9 kB
  ├ chunks/892-14cf70af990bffc9.js       26.5 kB
  ├ chunks/main-app-fbc33a3732902daa.js  221 B
  └ chunks/webpack-fb9c5795ff438a42.js   2.03 kB


λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)

Done in 60.54s.
```
</details>

**Comment by MarkKropf** [comment] 2024-01-04 14:50
Thank you, here is my information:

## Operation Env
```
Operating System:
  Platform: MacOSX
  Arch: M2 Ultra
  Version: Sonoma 14.2.1
Binaries:
  Node: 21.5.0
  npm: 10.2.4
  Yarn: 1.22.21
  pnpm: 8.13.1
```

**Comment by jmikrut** [comment] 2024-01-04 21:01
Hey @MarkKropf — I can't reproduce this either, unfortunately. You might have some `pnpm` package conflicts or linked packages somewhere on your machine. It looks like this is something outside of Payload's scope to solve.

If you try with Yarn or NPM instead of `pnpm`, does the problem resolve?

I am going to close this for now but if you can figure out how to isolate / reproduce, I am happy to re-open and address accordingly. But this template currently builds and deploys in all ways we've tested and also builds / deploys on CI / Payload Cloud / etc.

**Closed by jmikrut** 2024-01-04 21:01 UTC
Labels: possible-bug

**Comment by MarkKropf** [comment] 2024-01-06 04:55
> Hey @MarkKropf — I can't reproduce this either, unfortunately. You might have some `pnpm` package conflicts or linked packages somewhere on your machine. It looks like this is something outside of Payload's scope to solve.
> 
> If you try with Yarn or NPM instead of `pnpm`, does the problem resolve?
> 
> I am going to close this for now but if you can figure out how to isolate / reproduce, I am happy to re-open and address accordingly. But this template currently builds and deploys in all ways we've tested and also builds / deploys on CI / Payload Cloud / etc.

Wow, I think I found the cause of this one. I had ```NODE_ENV=development``` in my env vars, and the setting of that to production does not carry over to the ```yarn build:next``` for some reason. Once I cleared out the env var everything started working.

**Comment by Enot-Racoon** [comment] 2024-01-19 10:24
> > Hey @MarkKropf — I can't reproduce this either, unfortunately. You might have some `pnpm` package conflicts or linked packages somewhere on your machine. It looks like this is something outside of Payload's scope to solve.
> > If you try with Yarn or NPM instead of `pnpm`, does the problem resolve?
> > I am going to close this for now but if you can figure out how to isolate / reproduce, I am happy to re-open and address accordingly. But this template currently builds and deploys in all ways we've tested and also builds / deploys on CI / Payload Cloud / etc.
> 
> Wow, I think I found the cause of this one. I had `NODE_ENV=development` in my env vars, and the setting of that to production does not carry over to the `yarn build:next` for some reason. Once I cleared out the env var everything started working.

Hi. I have save issue.

Operating System:
  Platform: MacOSX
  Arch: M1
  Version: Sonoma 14.2.1

node: v18.19.0
npm: 10.2.3
yarn: 1.22.10
pnpm: 8.14.1

I tried yarn and npm it doesn't help
npm on install cannot install modules
yarn on build have same problem

**Comment by Enot-Racoon** [comment] 2024-01-19 12:49
> > > Hey @MarkKropf — I can't reproduce this either, unfortunately. You might have some `pnpm` package conflicts or linked packages somewhere on your machine. It looks like this is something outside of Payload's scope to solve.
> > > If you try with Yarn or NPM instead of `pnpm`, does the problem resolve?
> > > I am going to close this for now but if you can figure out how to isolate / reproduce, I am happy to re-open and address accordingly. But this template currently builds and deploys in all ways we've tested and also builds / deploys on CI / Payload Cloud / etc.
> > 
> > 
> > Wow, I think I found the cause of this one. I had `NODE_ENV=development` in my env vars, and the setting of that to production does not carry over to the `yarn build:next` for some reason. Once I cleared out the env var everything started working.
> 
> Hi. I have save issue when use Vite bundler. I use this manuals: https://payloadcms.com/docs/admin/vite and https://payloadcms.com/docs/admin/excluding-server-code. And dev mode work is good, but cannot build
> 
> Operating System: Platform: MacOSX Arch: M1 Version: Sonoma 14.2.1
> 
> node: v18.19.0 npm: 10.2.3 yarn: 1.22.10 pnpm: 8.14.1
> 
> I tried yarn and npm it doesn't help npm on install cannot install modules yarn on build have same problem
> 
> alexeykarasev@Alexeys-MacBook-Air pbtours-web % pnpm build
> 
> > pbtours-web@1.0.0 build /Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web
> > cross-env pnpm run build:payload && pnpm run build:server && pnpm run copyfiles && pnpm run build:next
> 
> > pbtours-web@1.0.0 build:payload /Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web
> > cross-env PAYLOAD_CONFIG_PATH=src/payload/payload.config.ts payload build
> 
> > pbtours-web@1.0.0 build:server /Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web
> > tsc --project tsconfig.server.json
> 
> > pbtours-web@1.0.0 copyfiles /Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web
> > copyfiles -u 1 "src/**/*.{html,css,scss,ttf,woff,woff2,eot,svg,jpg,png,js}" dist/
> 
> > pbtours-web@1.0.0 build:next /Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web
> > cross-env PAYLOAD_CONFIG_PATH=dist/payload/payload.config.js NEXT_BUILD=true ts-node -r tsconfig-paths/register dist/server.js
> 
> [17:48:01] INFO (payload): Connected to MongoDB server successfully! [17:48:01] INFO (payload): Starting Payload... [17:48:01] INFO (payload): OS: arm64, cores: 8 [17:48:01] INFO (payload): Payload Admin URL: http://localhost:3000/control [17:48:01] INFO (payload): Next.js is now building... ✓ Creating an optimized production build ✓ Compiled successfully ✓ Linting and checking validity of types ✓ Collecting page data Generating static pages (0/25) [ ] ⨯ TypeError: Cannot read properties of null (reading 'useContext') at _ (/Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web/.next/server/chunks/4467.js:1:20344) at f (/Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web/.next/server/chunks/4467.js:1:11618) TypeError: Cannot read properties of null (reading 'useContext') at t.useContext (/Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web/node_modules/.pnpm/next@[13.5.2_@babel](mailto:13.5.2_@babel)+core@[7.23.7_@opentelemetry](mailto:7.23.7_@opentelemetry)+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:1:197837) at _ (/Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web/.next/server/chunks/4467.js:1:20344) at f (/Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web/.next/server/chunks/4467.js:1:11618) at xs (/Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web/node_modules/.pnpm/next@[13.5.2_@babel](mailto:13.5.2_@babel)+core@[7.23.7_@opentelemetry](mailto:7.23.7_@opentelemetry)+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:1:271988) at /Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web/node_modules/.pnpm/next@[13.5.2_@babel](mailto:13.5.2_@babel)+core@[7.23.7_@opentelemetry](mailto:7.23.7_@opentelemetry)+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:1:276795 at Ds (/Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web/node_modules/.pnpm/next@[13.5.2_@babel](mailto:13.5.2_@babel)+core@[7.23.7_@opentelemetry](mailto:7.23.7_@opentelemetry)+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:1:278550) at Us (/Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web/node_modules/.pnpm/next@[13.5.2_@babel](mailto:13.5.2_@babel)+core@[7.23.7_@opentelemetry](mailto:7.23.7_@opentelemetry)+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:1:286122) at Ls (/Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web/node_modules/.pnpm/next@[13.5.2_@babel](mailto:13.5.2_@babel)+core@[7.23.7_@opentelemetry](mailto:7.23.7_@opentelemetry)+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:1:284340) at Ms (/Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web/node_modules/.pnpm/next@[13.5.2_@babel](mailto:13.5.2_@babel)+core@[7.23.7_@opentelemetry](mailto:7.23.7_@opentelemetry)+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:1:273376) at /Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web/node_modules/.pnpm/next@[13.5.2_@babel](mailto:13.5.2_@babel)+core@[7.23.7_@opentelemetry](mailto:7.23.7_@opentelemetry)+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:1:278526
> 
> Error occurred prerendering page "/logout". Read more: https://nextjs.org/docs/messages/prerender-error TypeError: Cannot read properties of null (reading 'useContext') at t.useContext (/Users/alexeykarasev/Projects/js/pattaya-buddy/pbtours-web/node_modules/.pnpm/next@[13.5.2_@babel](mailto:13.5.2_@babel)+core@[7.23.7_@opentelemetry](mailto:7.23.7_@opentelemetry)+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:1:197837) .....

I tried a lot of things, in the end what helped in my case was downgrading the next version to 13.4.9

**Comment by Enot-Racoon** [comment] 2024-01-19 17:48
Now i have problem with hot reload HMR
Hot reload work good for pages site.com/admin/*, but pages site.com/* not reload on files changes.
For pages site.com/* i see ws://localhost:3000/_next/webpack-hmr connection in developer network panel, but this connection not receives anything
