### ISSUE TITLE
findByID() type error 

### ISSUE THREAD

**Issue by muperdev** [payloadcms/payload#4711] opened 2024-01-06 18:40 UTC
### Describe the Bug

I have a collection of users and there is a field inside of it with number type. 
when I want to get this collection in Local API and update it, by using the findByID() I get the field and want to decrement something from it, I face the error of : The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type

### To Reproduce

1. create a collection with a field of type number
2. use Local API to call this collection in another process
3. try to decrement something from your number type field in a payload.update() 

### Payload Version

2.0.0

**Comment by paulpopus** [comment] 2024-01-08 19:45
Hey @muperdev are you able to share the exact code you wrote? For me I'm able to update the number field as expected and it's typed correctly as well
![image](https://github.com/payloadcms/payload/assets/35137243/3f39ca2f-6bd5-445c-a0de-c6e45f69b89f)

**Comment by muperdev** [comment] 2024-01-10 18:33
@paulpopus this is the code 
![image](https://github.com/payloadcms/payload/assets/85489543/ad0649a7-6ad9-4a54-9a6d-5802ff73b9e1)

**Comment by AlessioGr** [comment] 2024-06-15 06:49
Closing this as we cannot reproduce this. If you're still experiencing this issue on the latest version of payload, please open up a **new** issue linking to a repository with a minimal reproduction

**Closed by AlessioGr** 2024-06-15 06:49 UTC
Labels: status: cant-reproduce, status: needs-repro
