### ISSUE TITLE
Lexical / Paragraph menu fails in modal view

### ISSUE THREAD

**Issue by patricsgamma** [payloadcms/payload#4410] opened 2023-12-07 11:14 UTC
### Link to reproduction

https://github.com/patricsgamma/payload/tree/test/modal_slash

### Describe the Bug

At the start of a new Paragraph within a lexical richtext field, when entering a slash `"/"` a menu for paragraph options appears.

✔️  This works well within a normal create or edit page
❌  It does not work when the lexical editor is embedded within a modal view. The slash "/" is just typed as such but not triggering the menu.

### ✔️ Video of working menu in create view
Creating a ConversationText within its own collection create view works.

https://github.com/payloadcms/payload/assets/87857953/2583edfe-f8cc-4717-b715-ded40929f330

### ❌ Video of failing modal view:
Creating a ConversationText within its parent Conversation fails.

https://github.com/payloadcms/payload/assets/87857953/cb809dc5-164e-4eba-a7b6-689cd2e681b3

### To Reproduce

-

### Payload Version

`"payload": "^2.3.1"`

### Adapters and Plugins

```
"@payloadcms/bundler-webpack": "^1.0.5",     
"@payloadcms/db-mongodb": "^1.1.0",     
"@payloadcms/plugin-cloud-storage": "^1.1.1",     
"@payloadcms/plugin-sentry": "^0.0.6",     
"@payloadcms/richtext-lexical": "^0.3.1"
```

**Comment by AlessioGr** [comment] 2023-12-07 13:38
Hey @patricsgamma , I cannot reproduce it - even for very deeply nested drawers:


https://github.com/payloadcms/payload/assets/70709113/a3043eda-0ab9-43c5-babb-9eecf5f0070a

When used inside a Blocks field, like you did:

https://github.com/payloadcms/payload/assets/70709113/7cb9dbd7-4acd-4fef-bb96-6232ce931f54

Could you attach a reproduction, following **[this reproduction guide](https://github.com/payloadcms/payload/blob/main/.github/reproduction-guide.md)**?

**Comment by patricsgamma** [comment] 2023-12-18 13:38
Reproduction added

**Comment by AlessioGr** [comment] 2023-12-20 20:01
https://github.com/payloadcms/payload/assets/70709113/b5ef00de-add6-4eb5-ad72-5d2cf64f244f

The issue seems to be due to the condition in your `navigation` group thing. The condition is running infinitely, which'd probably cause a buunch of issues.

You need to make sure you're returning a boolean, e.g. changing `return props?.navigation` to `return !!props?.navigation` already fixes this issue.

That being said, it seems weird that simply not returning a boolean causes this issue - I'll dig into that

**Comment by AlessioGr** [comment] 2023-12-20 20:07
Closing this in favor of #4577 which describes the _**core**_ issue. Will investigate this there

**Closed by AlessioGr** 2023-12-20 20:07 UTC
Labels: possible-bug, plugin: richtext-lexical, correct-reproduction
