### ISSUE TITLE
Internal links in rich text broken after adding enableRichTextLink to collection

### ISSUE THREAD

**Issue by femkeklaver** [payloadcms/payload#3861] opened 2023-10-25 05:59 UTC
### Describe the Bug

After changing the number of collections with enableRichTextLink from one to two, the API's data model changes. In stead of just including the entry, it returns an object `doc`:

```
{
type: link,
linkType: internal,
doc: {
value: {
•••
 16 elements },
relationTo: articles
},
children: [
{
text: tofu
}
```

The frontend still seems to rely somewhere on the old data model, with just one collection enabled. The first time it saves perfectly, but when updating the entry all the internal links disappear.

[See message on Discord](https://discord.com/channels/967097582721572934/1166030905844977735/1166030905844977735)

### To Reproduce

These steps apply for Payload@1.15.7

* Create project with the create-payload-app blog template
* Add at least one collection with a richText field (not sure if it's in the Template)
* Include the `enableRichTextLink: false` in all but one collection
* Add some data with internal links in the richText field

* Remove `enableRichTextLink: false` from one collection
* Create an entry in a collection with a richText field and include an internal link - probably one to each linkable collection
* Save once, and it seems fine
* Edit data in the richText-field
* Save again. The internal links dissapear

### Payload Version

1.15.7

**Comment by JarrodMFlesch** [comment] 2023-10-25 18:25
@femkeklaver are you using the slate or lexical RTE adapter?

**Comment by AlessioGr** [comment] 2023-11-15 20:40
Hey @femkeklaver I have tried reproducing this on 2.0, but it works for me.

Could you
1) Check if this issue still happens in 2.0 and
2) If yes, link me to a repository where this happens?

**Comment by AlessioGr** [comment] 2023-11-28 20:30
Closing this, feel free to re-open if you're able to reproduce it in 2.0 :)

**Closed by AlessioGr** 2023-11-28 20:30 UTC
Labels: cant-reproduce, base: 1.x
