### ISSUE TITLE
CSS z-hight for lexical toolbar is off

### ISSUE THREAD

**Issue by exoer** [payloadcms/payload#8740] opened 2024-10-16 14:39 UTC
### Describe the Bug

The toolbar for lexical editor appears over a dropdown menu:
![Image](https://github.com/user-attachments/assets/80ceb1e1-0997-413a-ba66-175bdf9fe43a)

![Image](https://github.com/user-attachments/assets/02fb56e9-ede5-4c97-8bca-afd926d5ab6d)

I use PayloadCMS v3 beta-114

### Link to the code that reproduces this issue

npx create-payload-app@beta -t website

### Reproduction Steps

> npx create-payload-app@beta

Visit  http://localhost:4444/admin/collections/pages/670fcbf993abb42cdb3e4bd7

### Which area(s) are affected? (Select all that apply)

Not sure

### Environment Info

Node.js v22.6.0

Binaries:
  Node: 22.6.0
  npm: 10.9.0
  Yarn: N/A
  pnpm: 9.7.1
Relevant Packages:
  payload: 3.0.0-beta.114
  next: 15.0.0-canary.173
  @payloadcms/db-mongodb: 3.0.0-beta.114
  @payloadcms/email-nodemailer: 3.0.0-beta.114
  @payloadcms/graphql: 3.0.0-beta.114
  @payloadcms/live-preview: 3.0.0-beta.114
  @payloadcms/live-preview-react: 3.0.0-beta.114
  @payloadcms/next/utilities: 3.0.0-beta.114
  @payloadcms/plugin-cloud: 3.0.0-beta.114
  @payloadcms/plugin-cloud-storage: 3.0.0-beta.114
  @payloadcms/plugin-form-builder: 3.0.0-beta.114
  @payloadcms/plugin-nested-docs: 3.0.0-beta.114
  @payloadcms/plugin-redirects: 3.0.0-beta.114
  @payloadcms/plugin-search: 3.0.0-beta.114
  @payloadcms/plugin-seo: 3.0.0-beta.114
  @payloadcms/richtext-lexical: 3.0.0-beta.114
  @payloadcms/storage-s3: 3.0.0-beta.114
  @payloadcms/translations: 3.0.0-beta.114
  @payloadcms/ui/shared: 3.0.0-beta.114
  react: 19.0.0-rc-3edc000d-20240926
  react-dom: 19.0.0-rc-3edc000d-20240926
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64
  Available memory (MB): 32768
  Available CPU cores: 16

**Comment by akhrarovsaid** [comment] 2024-10-16 14:41
Hey @exoer,

I believe this to be a duplicate of #8728 - which already has a [PR up for a fix](https://github.com/payloadcms/payload/pull/8735).

**Comment by r1tsuu** [comment] 2024-10-16 14:45
@akhrarovsaid is right, closing

**Closed by r1tsuu** 2024-10-16 14:45 UTC
Labels: status: needs-triage, v3
