### ISSUE TITLE
local API's `forgotPassword` throwing errors.

### ISSUE THREAD

**Issue by MoSattler** [payloadcms/payload#2170] opened 2023-02-23 18:18 UTC
# Bug Report

local API's `forgotPassword` is throwing errors when used:
```
TypeError: Cannot read properties of undefined (reading 'config')
    at forgotPassword (/Users/user/directory/node_modules/payload/src/auth/operations/forgotPassword.ts:51:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Steps to Reproduce

I am trying this
```ts
await payload.forgotPassword({
  collection: "users",
  data: {
    email,
  },
});
```

reseting the password via the `/admin/forgot` works without a problem though. So it cannot be my email setup I guess.

## Other Details
```
"payload": "1.6.15",
```

**Comment by jmikrut** [comment] 2023-02-24 00:48
Hey @MoSattler — we'll check into this to see what we can discover.

Thanks for the report - will have more info for you shortly!

**Comment by linobino1** [comment] 2023-02-25 10:29
I've been experiencing a similar problem in the same project with `payload.create()` and payload.update()`.

I have a collection of countries with an alpha2 country code and a country name. I couldn't get the local API to set any other fields of the collection than `country.name`, even if I configured them similarly and fed the same data.

Again, with the REST API it works seamlessly.

**Comment by denolfe** [comment] 2023-02-27 19:16
I've found the root cause here, fix incoming.

@linobino1 I that doesn't seem to be related specifically to the fix I'll be making. Feel free to open a separate issue with recreation steps for the issue you're seeing.

**Comment by denolfe** [comment] 2023-02-27 19:32
Thanks for the report @MoSattler! This fix will be in the next release 👍

**Closed** 2023-02-27 19:31 UTC
Labels: bug
