### ISSUE TITLE
searching id generates error

### ISSUE THREAD

**Issue by GeorgeHulpoi** [payloadcms/payload#4227] opened 2023-11-20 19:15 UTC
### Link to reproduction

https://github.com/GeorgeHulpoi/payload-searchable-id

### Describe the Bug

Trying to search an id on search input will generate the following error:

```
[18:12:53] ERROR (payload): Error: Can't use $regex
    at ObjectId.SchemaType.castForQuery (C:\Projects\project\project.api\node_modules\mongoose\lib\schematype.js:1632:13)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Projects\project\project.api\node_modules\mongoose\lib\schematype.js:1603:22)
    at cast (C:\Projects\project\project.api\node_modules\mongoose\lib\cast.js:321:39)
    at cast (C:\Projects\project\project.api\node_modules\mongoose\lib\cast.js:71:18)
    at cast (C:\Projects\project\project.api\node_modules\mongoose\lib\cast.js:71:18)
    at cast (C:\Projects\project\project.api\node_modules\mongoose\lib\cast.js:71:18)
    at cast (C:\Projects\project\project.api\node_modules\mongoose\lib\cast.js:71:18)
    at model.Query.Query.cast (C:\Projects\project\project.api\node_modules\mongoose\lib\query.js:5351:12)
    at model.Query.Query._castConditions (C:\Projects\project\project.api\node_modules\mongoose\lib\query.js:2229:10)
    at model.Query.<anonymous> (C:\Projects\project\project.api\node_modules\mongoose\lib\query.js:2256:8)
```

### To Reproduce

1. Create a item in `Test` collection.
2. Try to search the ID in search input.
3. It should generate the error

### Payload Version

2.1.1

### Adapters and Plugins

MongoDB

**Comment by denolfe** [comment] 2023-11-20 20:29
Possible dupe of https://github.com/payloadcms/payload/issues/4081

**Closed** 2023-12-12 19:02 UTC
Labels: possible-bug
