### ISSUE TITLE
payload@2.0.6~11 w/ @payloadcms/richtext-lexical LinkFeature broken

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload#3809] opened 2023-10-22 12:13 UTC
### Describe the Bug

From payload@2.0.6, through 2.0.11, the `LinkFeature` from `@payloadcms/richtext-lexical` does not work.

![something-went-wrong-link](https://github.com/payloadcms/payload/assets/38236585/d5cb915d-9741-4821-a356-c2487ce8bd67)

(browser console):
```
Uncaught TypeError: Cannot read properties of undefined (reading 'text')
    at filterFields.js:16:40
    at Array.reduce (<anonymous>)
    at filterFields (filterFields.js:14:24)
    at RenderFields (index.js:102:56)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
```

### To Reproduce

I do have localization enabled for two languages and I'm also using nested docs, but I do not think they are creating the issue.

Simply try to create a Link with the LinkFeature.

### Payload Version

2.0.11

### Adapters and Plugins

richtext-lexical, db-mongodb, plugin-nested-docs, plugin-seo, bundler-webpack

**Comment by AlessioGr** [comment] 2023-10-23 10:05
Works on my machine! Could you provide a link to a reproduction?

**Comment by TimLanzi** [comment] 2023-10-23 12:41
I had a similar issue, though not the exact same, and I just had to update `@payloadcms/richtext-lexical`. Currently using these versions and it is working fine:

```json
"@payloadcms/richtext-lexical": "^0.1.14",
"payload": "^2.0.11"
```

**Comment by AlessioGr** [comment] 2023-11-03 17:12
Closing this, as it seems to be fixed in the latest version

**Closed by AlessioGr** 2023-11-03 17:12 UTC
Labels: cant-reproduce, missing-reproduction, plugin:richtext-lexical
