### ISSUE TITLE
REST API Query returns not as expected

### ISSUE THREAD

**Issue by zhounewz** [payloadcms/payload#2323] opened 2023-03-15 13:15 UTC
# Bug Report

## Steps to Reproduce

please look at the query below:
<img width="936" alt="image" src="https://user-images.githubusercontent.com/16400882/225318630-085e0803-54e2-4335-8a2c-b42027423675.png">

<img width="776" alt="image" src="https://user-images.githubusercontent.com/16400882/225318686-79ed56b2-66bd-46c3-aeaa-5821bc7f5c14.png">

**Why is the id of some returned data not equal to the query id**
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/16400882/225319757-ac3a83c7-78ee-4ad4-b138-1f962def5adb.png">

**Comment by jmikrut** [comment] 2023-03-15 21:28
Hmm, this is certainly strange. Can you create a minimally reproducible example of this? I just tried testing but could not replicate.

Do you have any access control set on this collection?

**Comment by zhounewz** [comment] 2023-03-16 01:41
<img width="687" alt="image" src="https://user-images.githubusercontent.com/16400882/225487102-8175a83d-ccf8-4650-bc6f-75f1ab6ed94e.png">

The below method works fine.
<img width="909" alt="image" src="https://user-images.githubusercontent.com/16400882/225487708-5bba7454-240a-40d7-a30b-7673f29c39ab.png">

**Comment by zhounewz** [comment] 2023-03-19 11:29
@jmikrut  I noticed that the storage type of id is not a string but an ObjectId;
The id in the parameter in the above screenshot is a string, whether the type here needs to be adjusted
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/16400882/226172119-80d779f4-dc0c-40b5-b372-ca9ec7abe75d.png">

**Comment by PatrikKozak** [comment] 2023-03-20 20:02
Hey @zhounewz - I manually adjusted my data to use your exact IDs and matched it up with your queries and I was not able to reproduce the behavior. I will attach some screenshots below.

I am going to close this for now but we can definitely continue this conversation if this is a persisting issue but we will need a reproducible repo to get to the bottom of it. 

![rest-api-query](https://user-images.githubusercontent.com/35232443/226452374-e729738b-8439-43fd-8f21-f2e06944aa1d.png)
![graphql-query](https://user-images.githubusercontent.com/35232443/226452370-064af2d7-3c38-4422-a45c-ef7bbeade2b8.png)
![test-db-data](https://user-images.githubusercontent.com/35232443/226452375-38579178-f63c-4755-8b12-dab48c951b0b.png)

**Closed by PatrikKozak** 2023-03-20 20:02 UTC
Labels: possible-bug, cant-reproduce
