### ISSUE TITLE
Resizing image requires local storage

### ISSUE THREAD

**Issue by cbratschi** [payloadcms/payload#4336] opened 2023-11-30 19:41 UTC
### Link to reproduction

private repo

### Describe the Bug

I am trying to resize an image from an upload collection using disableLocalStorage set to true. In this case the image can be resized in the edit view but fails during the save operation:

```
ERROR (payload): Error: ENOENT: no such file or directory, open '/Users/.../media/Bildschirmfoto 2023-11-08 um 23.00.53.png'
    at Object.open (node:internal/fs/sync:78:18)
    at Object.openSync (node:fs:565:17)
    at Object.readFileSync (node:fs:445:35)
    at getFileByPath (/Users/.../node_modules/payload/src/uploads/getFileByPath.ts:13:21)
    at generateFileData (/Users/.../node_modules/payload/src/uploads/generateFileData.ts:68:41)
    at updateByID (/Users/.../node_modules/payload/src/collections/operations/updateByID.ts:142:79)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async updateByIDHandler (/Users/.../node_modules/payload/src/collections/requestHandlers/updateByID.ts:36:17)
```

Payload tries to load the image from the file system.

If local storage is disabled, the image should be loaded through a network call using the API endpoint.

### To Reproduce

- Use upload collection with disableLocalStorage set to true.
- Upload an image.
- Edit the image.
- Save the resized image.

### Payload Version

2.3.0

### Adapters and Plugins

db-mongodb, bundler-webpack, live-preview

**Comment by ssyberg** [comment] 2023-12-01 14:10
I believe this is a duplicate of https://github.com/payloadcms/plugin-cloud-storage/issues/81

**Comment by JessChowdhury** [comment] 2023-12-12 11:44
Hi @cbratschi - try setting your upload collection `staticURL` to your API endpoint.

Although you're not using a plugin, you could take a look at the `payload-cloud-storage` plugin, and how each adapter has a custom `generateFileURL` function, then apply something similar to your own code, see example [here](https://github.com/payloadcms/payload/blob/main/packages/plugin-cloud-storage/src/adapters/s3/generateURL.ts).

**Comment by cbratschi** [comment] 2023-12-13 10:53
We set the staticURL to:

```
staticURL: `/${slug}`,
```

With the latest version which supports fetching uploaded files the error is different:

```
ERROR (payload): FileUploadError: Es gab ein Problem während des Hochladens der Datei.
    at generateFileData (/.../node_modules/payload/src/uploads/generateFileData.ts:81:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async updateByID (/.../node_modules/payload/src/collections/operations/updateByID.ts:142:57)
    at async updateByIDHandler (/.../node_modules/payload/src/collections/requestHandlers/updateByID.ts:36:17)
```

I see the code expects a complete URL:

https://github.com/payloadcms/payload/blob/f86879940430782cbad0ef3c3ec8dd2759d5954a/packages/payload/src/uploads/generateFileData.ts#L70

We store the images in GridFS i.e. there is not an external URL. Will look for a workaround to get this running. Probably adding localhost is enough.

**Comment by cbratschi** [comment] 2023-12-13 11:02
The problem is the other code expects a slash at the beginning to server the file:

https://github.com/payloadcms/payload/blob/f86879940430782cbad0ef3c3ec8dd2759d5954a/packages/payload/src/express/static.ts#L15

As said, we use GridFS i.e. files are served from MongoDB through the modified Express endpoint.

A solution would be that Payload checks if disableLocalStorage is true and in this case always uses fetch (there is no local file for sure):

https://github.com/payloadcms/payload/blob/f86879940430782cbad0ef3c3ec8dd2759d5954a/packages/payload/src/uploads/generateFileData.ts#L70

```JS
if (url && url.startsWith('/') && !config.upload.disableLocalStorage) {
```

This won't break anything and supports our use case.

**Closed** 2023-12-13 15:22 UTC
Labels: possible-bug

**Comment by JessChowdhury** [comment] 2023-12-13 15:30
> A solution would be that Payload checks if disableLocalStorage is true and in this case always uses fetch (there is no local file for sure)

@cbratschi this change has been made [here](https://github.com/payloadcms/payload/pull/4461) and will be in our next release. Let us know if you need anything else.
