### ISSUE TITLE
Cannot customize root level admin route

### ISSUE THREAD

**Issue by thgh** [payloadcms/payload#8886] opened 2024-10-28 00:03 UTC
### Describe the Bug

Following https://payloadcms.com/docs/beta/admin/overview#customizing-root-level-routes does not allow updating `routes.admin`

1. It's not allowed by Typescript
2. It cannot find a place to put import map as the admin folder was moved

### Link to the code that reproduces this issue

https://github.com/payloadcms/payload/blob/a8569b9e782ca70bcdbb2f7f6aaf5e1b98f949d7/packages/payload/src/bin/generateImportMap/index.ts#L177-L180

### Reproduction Steps

1. Move any files from `src/app/(payload)/admin` one folder up
2. Set routes.admin = '/' in payload config
3. Start dev server

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

Binaries:
  Node: 22.5.1
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  payload: 3.0.0-beta.117
  next: 15.0.1
  @payloadcms/db-mongodb: 3.0.0-beta.117
  @payloadcms/email-nodemailer: 3.0.0-beta.117
  @payloadcms/graphql: 3.0.0-beta.117
  @payloadcms/next/utilities: 3.0.0-beta.117
  @payloadcms/plugin-cloud: 3.0.0-beta.117
  @payloadcms/richtext-lexical: 3.0.0-beta.117
  @payloadcms/translations: 3.0.0-beta.117
  @payloadcms/ui/shared: 3.0.0-beta.117
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020

**Comment by jeffreylouden** [comment] 2024-10-29 10:53
Is this a duplicate of #7803?

**Comment by paulpopus** [comment] 2024-10-29 17:47
1. Setting `routes.admin` on the top level (note: not inside `admin`) worked for me just fine on the latest beta TS wise
2. Yeah I can confirm this is an issue and duplicate of ^

Will look into the attached PR, closing this and we'll track progress in that issue

**Closed by paulpopus** 2024-10-29 17:47 UTC
Labels: v3, created-by: Contributor
