### ISSUE TITLE
useAllFormFields() => weird behavior for blocks field

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#1882] opened 2023-01-15 15:39 UTC
# Bug Report

The output of useAllFormFields() is... weird for the blocks field (named `content` in this screenshot):

![image](https://user-images.githubusercontent.com/70709113/212550765-3c0911fb-1d57-40b5-829e-351c3bbcc9c0.png)

My expectation would be for it to be an array, and not split up into many different entries. `useAllFormFields()` is used in the SEO plugin in the custom react components to get access to the document's fields. If this is expected behavior (why?), is there an alternative hook I can use there which works better?

## Steps to Reproduce

Can use the seo plugin and have a `blocks` field in your collection: https://github.com/payloadcms/plugin-seo/blob/1ce76df409723e13c12af5871ee5776edafe667d/src/fields/MetaTitle.tsx#L39

## Other Details

Payload version: 1.5.9

**Comment by jmikrut** [comment] 2023-01-15 15:42
Hey @AlessioGr — this is indeed intended behavior. Forms in payload use dot notation to nest their values, because each field has more than a value stored in its state. For example, in addition to field values, we need to store `valid`, `passesCondition`, etc.

What you're looking for is form `data`. You can convert form state back and forth between the shape of the data and the shape of the form state itself.

Check out the following:

```
import { reduceFieldsToValues } from 'payload/components/forms'
```

This is what you should use. But I'll close this for now because it's working as intended.

How's that? 👍

**Closed by jmikrut** 2023-01-15 15:42 UTC
Labels: possible-bug

**Comment by AlessioGr** [comment] 2023-01-15 16:16
> Hey @AlessioGr — this is indeed intended behavior. Forms in payload use dot notation to nest their values, because each field has more than a value stored in its state. For example, in addition to field values, we need to store `valid`, `passesCondition`, etc.
> 
> What you're looking for is form `data`. You can convert form state back and forth between the shape of the data and the shape of the form state itself.
> 
> Check out the following:
> 
> ```
> import { reduceFieldsToValues } from 'payload/components/forms'
> ```
> 
> This is what you should use. But I'll close this for now because it's working as intended.
> 
> How's that? 👍

Hey, thank you! `reduceFieldsToValues` works perfectly for me!

**Comment by remy90** [comment] 2024-03-19 15:30
@AlessioGr did you ever find yourself requiring the total number of, in your image, the expanded node `content`? I've noticed `reduceFieldsToValue` doesn't include these important array length nodes
