### ISSUE TITLE
Problem to fetch doc (drafted version) but ?draft=false

### ISSUE THREAD

**Issue by ClementLaval** [payloadcms/payload#3626] opened 2023-10-13 08:38 UTC
### Link to reproduction

none

### To Reproduce

none

### Describe the Bug

In this short video, I show you after pushing a new draft, I'm not longer able to fetch the data (I use a fetch from Nextjs with ?draft=false).
Fetch return an empty doc array, then zod throw an error telling me that doc.id is missing.

I didn't change this part of my code since v1, so it should work.

Thank you !

https://github.com/payloadcms/payload/assets/82887830/1e981bd8-2934-4b0b-8c8a-76848fc2e5dc

### Payload Version

2.0.5

### Adapters and Plugins

"@payloadcms/db-mongodb": "^1.0.3", "@payloadcms/bundler-webpack": "^1.0.3"

**Comment by jmikrut** [comment] 2023-10-13 12:56
Hey @ClementLaval — I tried reproducing this in a thousand ways, but it works as expected for me. Unfortunately I will need some more information to be able to determine what is causing this. 

If you can update this issue with your hooks and / or access control on the pages collection, maybe that would help. 

It would also be great to have the full stack trace for the error that is created in your backend so I can see what the full error is, and where it's coming from.

But ideally, we would love to have a minimally reproducible demo. Can you hook me up with some further info?

**Comment by jmikrut** [comment] 2023-11-06 16:22
Hey @ClementLaval just checking back on this one. Did you ever figure out how to resolve this? I still can't reproduce but I wonder if you updated to the newest Payload, if the problem would just resolve at this point.

Let me know. I will close this in the interim but if you can help me reproduce, I will happily respond accordingly / reopen the issue.

Thank you! PS, your portfolio site is great. I just checked it out.

**Closed by jmikrut** 2023-11-06 16:22 UTC
Labels: possible-bug, cant-reproduce
