### ISSUE TITLE
Auto imports in webstorm are pointing to wrong files

### ISSUE THREAD

**Issue by genox** [payloadcms/payload#6649] opened 2024-06-05 23:44 UTC
### Payload Version

beta40

### Node Version

20

### Next.js Version

15rc0

### Describe the Bug

I checked out the payload 3.0 demo to start dabbling with it and noticed that auto imports of dependencies (hooks, components, ..) are always resolving to `../dist/..` directories, resulting in imports not working. Removing /dist/ resolves the issue. Payload's libraries are the only libraries that seem to have this issue in my setup. Everything else works fine.

I am using the suggested version of modules, default webstorm (with some autosave options). I wonder if this happens to other webstorm users as well and if not, what the difference could be between their setup and mine.

I noticed this behaviour as soon as i checked out the first betas, maybe this could be related to the way the packages' ts definitions are built and vscode is smart enough to figure it out. :) who knows.

Let me know if there is anything I can do to help troubleshoot this.

### Reproduction Steps

- Check out the repo
- Open in webstorm
- Make custom component with some ui and hook imports (like a custom field)
- Notice the import pointint to the `dist` directory

**Comment by AlessioGr** [comment] 2024-06-06 00:24
I can reproduce this. Typing `useFormFields` gives me autocompletion suggestions for the `@payloadcms/ui` import while I'm typing. Accepting that suggestions incorrectly imports from `dist` (`'@payloadcms/ui/dist/forms/Form'`). Not accepting it and opening the context menu manually gives me suggestions for `'@payloadcms/ui/forms/Form'` (correct) as well as `'node_modules/@payloadcms/ui/dist/forms/Form/context'`.

If, within the `@payloadcms/ui` package.json, we remove the `/exports/` package.json exports (which I believe may have been incorrect), webstorm does not give us any immediate autocompletion at all anymore, as if `useFormFields` does not exist. If I type it and manually open the suggestions context menu, it suggests me the correct import (`'@payloadcms/ui/forms/Form'`), as well as another incorrect one prefixed with `node_modules` (`'node_modules/@payloadcms/ui/dist/forms/Form/context'`). Sadly, immediate autocompletion (the one you get while typing) stays broken.

We've had TypeScript autocompletion issues ever since payload 1.x, experimenting with multiple different ways of exporting things since then. None of them worked without issues like these. At this point I'm inclined to think autocompletion is just straight up broken within either webstorm or TypeScript itself, or both. It's a badly designed black box which is a nightmare to debug. I'll do some more experimenting with this and see if I can find a better solution, to get those autocompletions to work properly

**Comment by genox** [comment] 2024-06-06 21:39
I wonder if anybody using other editors has the same issue with auto imports/resolution in editors, this would make it a systemic issue and not an IDE specific one. But I never read anything on discord or here. What strikes me as peculiar is that this seems to be limited to the payload UI package as far as I can tell so chances are high that this could be due to the structure of said project, the way it is bundled etc. Might as well be the location of the d.ts files, they seem to be in the dist directory. I wonder if it would work if they would be one level up or in the root of the project. But I can't tell for sure, way too little experience with the nitty gritty of outputting ts definitons in packages.

**Comment by AlessioGr** [comment] 2024-06-19 16:40
Fixed in https://github.com/payloadcms/payload/pull/6848. Our exports were already correct, but webstorm seems to handle the "main" and "types" props a lot better than package.json exports. Their support for package.json exports seems broken or incomplete.

By moving most of the ui exports to the root (@payloadcms/ui) this should be mostly resolved.

This should get any "root" imports from '@payloadcms/ui' to work again. As for other potential import suggestion issues specifically with sub-path exports (e.g. @payloadcms/ui/shared') I'd open up an issue with Webstorm. VS Code seems to handle those as expected

**Closed by AlessioGr** 2024-06-19 16:40 UTC
Labels: status: verified, v3

**Comment by AlessioGr** [comment] 2024-06-27 21:14
I have opened a Webstorm issue for package.json#exports auto-import suggestions which remain incorrect: https://youtrack.jetbrains.com/issue/WEB-67859/Incorrect-auto-import-suggestions-from-package.jsonexports
