### ISSUE TITLE
CastError: Cast to ObjectId failed when duplicating content with a relationship field

### ISSUE THREAD

**Issue by frederico-taramaschi** [payloadcms/payload#8479] opened 2024-09-30 13:15 UTC
### Describe the Bug

When duplicating a document which contains a RelationshipField, the duplication is successful but it does throw an error which is confusing to the user.
Checking the logs it shows a "ERROR (payload): CastError: Cast to ObjectId failed for value ..." where you get "(type Object) at path "_id" for model"

### To Reproduce

Create a collection with a RelationshipField field
Create a document and link it to a document via the relationship
Duplicate the document

### Payload Version

2.24.2

**Comment by frederico-taramaschi** [comment] 2024-09-30 14:18
The field config I used to get the error:
{
	name: 'fieldname',
	label: 'Related to',
	type: 'relationship',
	index: true,
	hasMany: true,
	relationTo: ['collectionslug'],
	admin: {}
}

And just to clarify, yes the document has to have at least one document linked for the error to occur. If the field is empty there is no issue.

**Comment by PatrikKozak** [comment] 2024-10-02 15:51
Hey @frederico-taramaschi - I'm unable to reproduce this on latest v2 (`2.30.1`). Can you give this another shot on latest v2 and let me know if you're still experiencing this?

**Comment by frederico-taramaschi** [comment] 2024-10-08 11:05
Sorry I have not yet been able to make time to test it out on latest, hoping to do it soon

**Comment by PatrikKozak** [comment] 2024-11-21 21:05
Hey @frederico-taramaschi - I'm going to close this issue for now - if you are still experiencing the above behavior on latest v2, please send me a reproduction repo and I'll be happy to re-open this issue and take another look.

**Closed by PatrikKozak** 2024-11-21 21:05 UTC
Labels: status: cant-reproduce, v2
