### ISSUE TITLE
Performance issues with many lexical rich text editors in one document

### ISSUE THREAD

**Issue by smoores-dev** [payloadcms/payload#7366] opened 2024-07-25 19:36 UTC
### Link to reproduction

https://github.com/smoores-dev/payload-3-perf-repro

### Payload Version

3.0.0-beta.68

### Node Version

20.12.2

### Next.js Version

15.0.0-canary.76 (also reproduced with 15.0.0-canary.53 and 15.0.0-canary.58)

### Describe the Bug

There is a threshold of rich text editors in a given document that will trigger a performance degradation that is so severe that it actually prevents saving (auto saving or manual saving).

#### To reproduce

**See comment, this is actually simpler to reproduce than I thought!**

1. Copy `.env.example` to `.env`
2. Install dependencies: `yarn`
3. Make a production build: `yarn build`
4. Start the server: `yarn start`
5. Create a new `Page` document
6. Create a PageContent Panel
7. Insert a Cards block in the `Content` field
8. Add about 13 cards to the Cards block
9. Type two or three sentences (actually type, don't copy/paste) into one of the card content fields

#### Observations

1. The card content fields become very high latency at this point. There is a large delay between keyboard input and feedback.
2. More importantly, saving will essentially stop occurring. Sometimes a single autosave will trigger after the first few characters, but none of the remaining content will ever be saved, even after waiting several minutes. If you disable autosave in the config, you'll be able to manually click the Save button, but the saved content will similarly be missing all but the first few characters of the change.

### Adapters and Plugins

db-mongodb

**Comment by smoores-dev** [comment] 2024-07-30 22:16
Just a few more notes in case it's helpful to anyone looking into this:

I think that this title actually isn't entirely accurate. The issue seems to be with the `BlocksFeature`, not with having many Lexical editors on the page at once. If you simply create a single PageContent panel, add a single CardBlock to it, and then add 14 cards to that CardBlock, the same issue occurs!

**Comment by alexmelman** [comment] 2024-08-01 14:59
Chiming in to add that this issue is blocking us from moving our site to production - we migrated an existing site to Payload and generally love it but this issue is making the CMS unusable for our content editors on several key pages. So any fix will be GREATLY appreciated! Thanks.

**Comment by AlessioGr** [comment] 2024-08-14 16:19
Please test out 3.0.0-beta.79 - we've made some performance improvements there. 

> More importantly, saving will essentially stop occurring
I was able to reproduce this in the payload version you used. In 3.0.0-beta.79 this issue seems to be completely fixed. There's still delay while typing when you have thousands of richtext fields & blocks on the same page, but no delay when saving the document.

To further improve performance, we'll ship our packages pre-compiled by the new React 19 compiler in the future. When I tested it, this came with huge performance improvements when typing in richtext fields, if there are thousands of them on the same page

**Comment by AlessioGr** [comment] 2024-08-15 04:37
Here's a canary optimized using the react compiler: `3.0.0-canary.12a836c`

Would be great if you can compare this version with 3.0.0-beta.81, and lmk how noticeable the difference is

**Comment by smoores-dev** [comment] 2024-08-15 14:54
Thank you for looking into this, @AlessioGr!

I'm trying to upgrade to the beta.81 version, but I'm having some trouble with the breaking changes in 79 (at least I think that's the issue).

I don't seem to be able to run the `payload generate:importMap` command on either beta.79 or beta.81. On beta.79, I get the error that payload.config.ts is using ESM syntax but the project isn't `"type": "module"`:

```
import { mongooseAdapter } from "@payloadcms/db-mongodb";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:128:18)
    at wrapSafe (node:internal/modules/cjs/loader:1280:20)
    at Module._compile (node:internal/modules/cjs/loader:1332:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)

Node.js v20.12.2
```

This suggests to me that the `generate:importMap` command isn't correctly transpiling/loading the config file?

On beta.81, I get past that initial error, but it still seems to be having an issue with loaders, this time for CSS files:

```
/path/to/project/node_modules/react-datepicker/dist/react-datepicker.css:1
@charset "UTF-8";
^

SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:128:18)
    at wrapSafe (node:internal/modules/cjs/loader:1280:20)
    at Module._compile (node:internal/modules/cjs/loader:1332:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Object.transformer [as .js] (file:///home/smoores/code/mvpsite-new/node_modules/tsx/dist/register-B_eFQvfc.mjs:2:878)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at <anonymous> (/home/smoores/code/mvpsite-new/node_modules/@payloadcms/ui/dist/exports/client/chunk-HR5HEGNB.js:14:102589)

Node.js v20.12.2
```

Any guidance on what I might be missing here? Thanks!

**Comment by AlessioGr** [comment] 2024-08-15 14:59
@smoores-dev beta.79 had some loader issues, so I'd ignore that error. As for beta.81, given that the payload config is supposed to be 100% server-only, our loaders do not handle client modules anymore.

I would first try and finish the migration of your payload config - make sure all components are now component paths instead of being imported into the payload config, get rid of any client-side code you're importing, and also be wary of older plugins that might be importing client code into your config.

**Comment by smoores-dev** [comment] 2024-08-15 15:15
Ah, got it! Ok yeah, fixing my custom lexical features to avoid importing client code fixed those issues. So far beta.81 is looking good on the minimal reproduction repo!! With a production build, there's almost no lag, even with 14 blocks in a single editor, and on both dev and prod I'm not seeing any indication of a failure to trigger a save. I'm going to test the optimized canary here, and then I'll test our actual application repo and make sure everything is working there. Should have more info shortly!

**Comment by smoores-dev** [comment] 2024-08-15 15:19
It's hard to say for sure, but it does seem like the optimized canary has less typing delay than beta.81 does. Actually, I don't perceive _any_ typing lag in richtext blocks in the canary, where there was still a small but perceptible lag even on production builds on beta.81. I suspect that this will be more noticeable in the real application, so I'll try to confirm there

**Comment by smoores-dev** [comment] 2024-08-15 15:46
Ok, cool, here's what I've got!

On our worst-performing page, which has about 35 total rich text editors and about 15 uses of the blocks feature, editing is still pretty broken in dev mode. The actual text editing is way less laggy, but it will still only successfully save one time; after that, manual and automatic saving become unresponsive.

HOWEVER! With a production build, everything is now working on beta.81! Text editing has a perceptible lag, but not disastrous, and most crucially, saving is indeed working.

And on the optimized canary build, text editing has _no_ perceptible lag, and autosaving is working perfectly!

**Comment by AlessioGr** [comment] 2024-08-15 16:13
Amazing! And just to clarify, the canary build has no lag in BOTH production and dev?

**Comment by smoores-dev** [comment] 2024-08-15 19:23
The canary build has _almost_ no lag in dev, and fixes the auto save issue there as well. There's like very slight periodic lag in dev, but it's barely noticeable.

**Comment by AlessioGr** [comment] 2024-08-19 21:31
Fixed by https://github.com/payloadcms/payload/pull/7688

**Closed by AlessioGr** 2024-08-19 21:31 UTC
Labels: v3
