### ISSUE TITLE
@payloadcms/plugin-cloud-storage/s3 needs to be updated to work with vite.

### ISSUE THREAD

**Issue by iamacup** [payloadcms/payload#5124] opened 2024-02-20 21:12 UTC
As requested by @denolfe here: https://discord.com/channels/967097582721572934/1209274888028946522

### Describe the Bug

There is only webpack aliases, using @payloadcms/plugin-cloud-storage/s3 will import fs and other backend modules to the frontend and break the admin panel.

### To Reproduce

install and use `@payloadcms/plugin-cloud-storage/s3` with vite

### Payload Version

latest

![image](https://github.com/payloadcms/payload/assets/12894620/1389057a-0bb9-42dd-af15-b3bf6c22813a)

**Comment by denolfe** [comment] 2024-02-21 20:42
Dupe of #4844

**Closed by denolfe** 2024-02-21 20:42 UTC
Labels: [possible-bug]
